### ISSUE TITLE
Lost peers due to state-cache

### ISSUE THREAD

**Issue by GopherJ** [paritytech/substrate#10130]
After upgrading to polkadot-v0.9.10 & polkadot-v0.9.11, we start to observe `no peers` issue on some of our collators, while turning on `sync=trace` I found the following logs:

![image](https://user-images.githubusercontent.com/33961674/139563509-d578d0e9-0748-4e93-9bbe-522b124a2f8c.png)

**Comment by GopherJ** [comment]
I'd really like to know why it's refused? is it because of a bad reputation? how can I check this, thanks

**Comment by GopherJ** [comment]
the connection to another bootnode is refused:
```
2021-10-31 02:04:46.972 DEBUG tokio-runtime-worker sync: [Parachain] Connected 12D3KooWLUTzbrJJDowUKMPfEZrDY6eH8HXvm8hrG6YrdUmdrKPz
2021-10-31 02:04:46.973 DEBUG tokio-runtime-worker sync: [Parachain] Request to peer PeerId("12D3KooWLUTzbrJJDowUKMPfEZrDY6eH8HXvm8hrG6YrdUmdrKPz") failed: Refused.
2021-10-31 02:04:46.974 DEBUG tokio-runtime-worker sync: [Parachain] 12D3KooWLUTzbrJJDowUKMPfEZrDY6eH8HXvm8hrG6YrdUmdrKPz disconnected
```

**Comment by GopherJ** [comment]
https://github.com/paritytech/substrate/blob/5e2b0f041c8a10c3ceb06721389e1d5c95380e65/client/network/src/protocol.rs#L1480-L1483

**Comment by GopherJ** [comment]
@tomaka sorry to ping you, we would like to fix this issue as it's on live, do you mind having a look?

**Comment by GopherJ** [comment]
just discoverred it's back now with 17 peers

**Comment by GopherJ** [comment]
this error happened again on one of our collator: https://telemetry.polkadot.io/#list/0x64a1c658a48b2e70a7fb1ad4c39eea35022568c20fc44a6e2e3d0a57aee6053b
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/33961674/139608788-72ac64ad-723a-435c-9ad5-714c0bbcf0f3.png">

**Comment by tomaka** [comment]
The `Refused` error happens if the reputation of the source node is too low, or if the node targeted by the request is overloaded and is uncapable of processing more block requests (to prevent DoS attacks)

**Comment by GopherJ** [comment]
> The `Refused` error happens if the reputation of the source node is too low, or if the node targeted by the request is overloaded and is uncapable of processing more block requests (to prevent DoS attacks)

How to check the reputation? The latter shouldn't be our case because it's our own node and we didn't find any potential DDOS attack yet.

**Comment by tomaka** [comment]
You can use `-l peerset=trace` to see all reputation changes. If there's no error in the logs, it is likely that this doesn't relate to reputations but that the CPU or disk the nodes are running on isn't powerful enough.

**Comment by GopherJ** [comment]
ok let me test

**Comment by GopherJ** [comment]
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/33961674/139680439-97392036-3e21-45c4-a6f6-752f3a44313a.png">

I saw this, from this disconnected collator's perspective, the others have a pretty bad reputation

**Comment by tomaka** [comment]
Reputations start being "bad" below approximately `-2^28` if I remember correctly.
The reputations displayed here shouldn't have any consequence.

**Comment by GopherJ** [comment]
@tomaka so you are saying that we should increase VPS's size right. Currently we are using 8Cores + 16GB and 10Gbps for our collators, do you have suggestions?

**Comment by tomaka** [comment]
This should be more than enough, as far as I know.
In my opinion, *something* (i.e. some event) happened and caused the nodes to act very slowly for a few hours. It would be nice to figure out what this "something" is, but we don't have any clue here unfortunately.

**Comment by GopherJ** [comment]
@tomaka ok we will investigate it and let you know, great thanks on the help

**Comment by GopherJ** [comment]
@tomaka we didn't find any attack, so I believe it's ok on this part, also we don't have any error logs yet, but we constantly have one collator disconnected with the others

https://telemetry.polkadot.io/#/0x64a1c658a48b2e70a7fb1ad4c39eea35022568c20fc44a6e2e3d0a57aee6053b

this time it's `heiko-collator-0`

**Comment by GopherJ** [comment]
hi @tomaka I think there is a bug, restarting the nodes can help for some hours but then it starts to lose peers again.

**Comment by GopherJ** [comment]
<img width="1369" alt="image" src="https://user-images.githubusercontent.com/33961674/140699544-41c66fd1-140e-46e0-9a51-83b8abf7d9f1.png">

this really doesn't look cool, what type of information can I post to help fixing this issue?

**Comment by tomaka** [comment]
Please check the CPU usage of the nodes and see if it correlates with the disconnections.

**Comment by GopherJ** [comment]
@tomaka 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/33961674/140760677-7f460eb4-5869-49a2-a8fc-36ebf6671283.png">

**Comment by GopherJ** [comment]
hi @tomaka we are still suffering from this issue, we are restarting our collators everyday:) it helps but not much

https://telemetry.polkadot.io/#/0x64a1c658a48b2e70a7fb1ad4c39eea35022568c20fc44a6e2e3d0a57aee6053b

**Comment by GopherJ** [comment]
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/33961674/142357173-28a38eb2-e311-4dce-b0cc-202d6c696915.png">

**Comment by GopherJ** [comment]
after adding `--state-cache-size 1` it looks much better now but not sure yet if it's resolved

**Comment by GopherJ** [comment]
since these three days our collators are working fine by adjusting `--state-cache-size` to `1`, I think this issue can be closed

**Comment by nazar-pc** [comment]
I see the same issue on my network with a few nodes. There was nothing special happening there, node was working fine for a few days and suddenly that happened. Shouldn't it "just work" without need to disable state cache?

I think this should be reopened for further investigation, there is clearly something wrong if it happens on simple network with no misbehavior.

**Comment by GopherJ** [comment]
@tomaka @bkchr @nazar-pc I'm reopening this because there are definitely some issues with the cache.

**Comment by bkchr** [comment]
With what cache? The state cache?

**Comment by nazar-pc** [comment]
We have a simple and reliable way to reproduce it (though inconvenient).

With blockchain size (`chains` directory) of ~200G and 2 nodes available, third node joining the network is fairly quickly banned by other nodes. This happens every time long before 100G mark. Last attempt failed after just a few gigabytes.

Are there some parameters right now that can be tweaked to fix this behavior?

**Comment by bkchr** [comment]
@nazar-pc is this still relevant?

**Comment by nazar-pc** [comment]
Likely yes. What we did on our side is forking Substrate to decrease amount of data that block range response can contain and together with https://github.com/paritytech/substrate/pull/12146 it got much better, but I don't believe it is solved fundamentally.

**Comment by bkchr** [comment]
What limit did you decrease?

**Comment by bkchr** [comment]
CC @altonen the title here is probably misleading at this should not be related to the state-cache (which also not exists anymore today), but maybe some networking issue when it is improved by decreasing the mentioned max body size.

@nazar-pc could you provide your mentioned reproduction?

**Comment by nazar-pc** [comment]
I'm afraid it is no longer there as we are in the middle between previous and current testnet right now. I can request the team to try and reproduce it, but it may take a while.

The gist of our observation is the following: node was making request, but response was so big (initially significantly bigger than default `MAX_BODY_SIZE` due to old implementation logic) that node wasn't able to always pull it within keepalive timeout (I believe this is how it is called). With https://github.com/paritytech/substrate/pull/12146 and `MAX_BODY_BYTES` decrease we achieved lower maximum expected bandwidth requirement from nodes before timeout kicks in and that way connection wasn't dropped. So the peers are connected to each other and they successfully transfer data, but because a single response takes so long (it shouldn't block TCP connection though because messages are fragmented by muxer anyway) it was having such effect as if connection was idling for a long time and timing out.

This was primarily reproducible in slow network conditions, like pulling something behind Chinese firewall from server in EU as one of easier to reproduce examples. Those who had strong connectivity didn't have issues, but we are supporting diverse set of users in our protocol and need to be prepared to these less than optimal conditions.

**Comment by altonen** [comment]
> I can request the team to try and reproduce it, but it may take a while.

This would be much appreciated. @dmitry-markin @melekes  could you take a look at this?

**Comment by bkchr** [comment]
> So the peers are connected to each other and they successfully transfer data, but because a single response takes so long (it shouldn't block TCP connection though because messages are fragmented by muxer anyway) it was having such effect as if connection was idling for a long time and timing out.

Ty! Yeah maybe our time out mechanism isn't implemented properly. I don't know how it works exactly, but it should detect that there is progress being made and not require some kind of ping-pong (I think that is what we are doing) in these cases.

**Comment by dmitry-markin** [comment]
> > I can request the team to try and reproduce it, but it may take a while.
> 
> This would be much appreciated. @dmitry-markin @melekes could you take a look at this?

I can have a look at this and try reproducing the issue with slow networks / keepalives after merging some in-progress PRs.

**Comment by dmitry-markin** [comment]
May be connected issue: https://github.com/paritytech/substrate/issues/12105

**Comment by dmitry-markin** [comment]
So far it looks like the theoretical bandwidth requirements based on [`MAX_BODY_BYTES`](https://github.com/paritytech/substrate/blob/7d767195cb60b00309c4c95e362df67244f63ad5/client/network/sync/src/block_request_handler.rs#L51) of 8 MB and [block request protocol timeout](https://github.com/paritytech/substrate/blob/7d767195cb60b00309c4c95e362df67244f63ad5/client/network/sync/src/block_request_handler.rs#L77) set to 20 s is 8 MB / 20 s = 3.4 Mbit/s. In my (arbitrary) tests with syncing polkadot chain, 1 Mbit/s was enough to download blocks around block number `14357815`, but 512 kbit/s connection limit lead to block request protocol timing out after 20 seconds, and the peer we are syncing from being backed-off. The things can be theoretically improved client-side by reducing the number of blocks requested in a single request in [`MAX_BLOCKS_TO_REQUEST`](https://github.com/paritytech/substrate/blob/7d767195cb60b00309c4c95e362df67244f63ad5/client/network/sync/src/lib.rs#L107). Reducing it from 64 to 32 made sync work in my setup on 512 kbit/s.

It looks like there is no solution other than "turning knobs here and there" without modifying libp2p, because libp2p considers the whole request to be timed out if the response was not received in full. On the other hand, I'm not sure that keeping connections alive if they can't meet our timeout requirements and just transmit _something_ really makes sense (e.g., slowloris attack?)

**Comment by nazar-pc** [comment]
Yes, we have decreased requirements in our protocol to ~1Mbps, unfortunate things is that those are constants and we had to fork Substrate to make those changes.

**Comment by bkchr** [comment]
> It looks like there is no solution other than "turning knobs here and there" without modifying libp2p, because libp2p considers the whole request to be timed out if the response was not received in full. On the other hand, I'm not sure that keeping connections alive if they can't meet our timeout requirements and just transmit _something_ really makes sense (e.g., slowloris attack?)

But could we not be smarter by starting with less blocks, calculate the bandwidth and then increase the blocks to request based on what we measured? We would then only need some minimum bandwidth requirements.

**Comment by dmitry-markin** [comment]
> But could we not be smarter by starting with less blocks, calculate the bandwidth and then increase the blocks to request based on what we measured? We would then only need some minimum bandwidth requirements.

In theory we could, but adaptive congestion control on the application layer would be more complicated than just calculating the bandwidth once and setting the block count in the request. We should also account for the change of network conditions, influence of parallel transmission of data by other protocols / parallel download from multiple peers (not sure if we have this), control stability issues. I.e., the congestion control algorithms in TCP are there for a reason.

We can implement some POC, but the algorithm must be extremely dumb and straightforward to not introduce new issues (especially I worry for the stability of the feedback loop).

**Comment by altonen** [comment]
I agree with @dmitry-markin here

There's already so much abstraction below the request-response protocol that implementing adaptive streaming all the way up there sounds quite difficult get it working properly, except for the dumb case. The request-response protocol would have imperfect information as to what is happening in the stream because other protocols are also being multiplexed and consume some amount of the available bandwidth. Also once the amount of bandwidth is over-estimated and too much data is sent, the connection is closed which is quite a bit more harsh than TCP dropping packets, adjusting window size and resending those packets.

Maybe we could make those knobs more available to people wouldn't have to fork Substrate.

**Comment by bkchr** [comment]
Good points! Was some random idea by me that I just wanted to write down. Hadn't put that much thoughts into it!

> Maybe we could make those knobs more available to people wouldn't have to fork Substrate.

Yes! This wasn't really possible up to now, but now with sync almost being independent it should work!
