### ISSUE TITLE
Resarch a XMCP MVP for contracts in order to support statemine

### ISSUE THREAD

**Issue by athei** [paritytech/substrate#10136]
We ideally want to have a canvas parachain without `pallet_asset`.  This means that we need to interact via XCMP with statemine in order to manage assets. We want to research a way to add a minimal version that allows some useful interaction so that ERC20 contracts are not needed.

Also, we should look into making the issuer for a new assert in `pallet_asset` a `MultiLocation` so that  it can be a contract on canvas.

**Comment by HCastano** [comment]
We had a chat with @gavofyork and here are some of the main takeaways from our discussion:
- We should try and reduce the amount of async specific support
- We're okay with contracts breaking due to different XCM versions (at least initially)
- We should send and receive raw XCM messages initially
- We don't need to decode any received messages, we should just match on the raw bytes
- We should have a way for users to manually poll XCM results (e.g, custom `ink!` message) for XCM messages which a contract has sent
- We should include `pallet-assets` in the Canvas runtime
- We should support teleported/reserve assets from Statemint (would be user initiated)
- We should implement a send XCM host function, a receive XCM exported function, and MultiLocation support for smart contract account IDs
- We should not launch on Kusama without minimal XCM support
