### ISSUE TITLE
Create generic notifications channel type that cleans subscriptions when receiver is dropped

### ISSUE THREAD

**Issue by acatangiu** [paritytech/substrate#10576]
_As described by @koute_:

Alas, I didn't add a generic utility to clean up the subscriptions when the receiver is dropped, although that *might* actually be a good idea seeing that we have a very similar situation here.

What I did is basically [I wrapped the `TracingUnboundedReceiver` into a newtype and made it unsubscribe on drop](https://github.com/paritytech/substrate/pull/10454/files#diff-ece03d48ef90111c19d13e2b3a77068eeda4eaedad0b033dd9b18303bf63b538R84).

So I see four possibilities here:

1) Ignore the problem. *If* the notifications are sent relatively often then it won't become a critical problem. (Not a fan of this one though, as it just creates a subtle footgun which can blow up someday.)
2) Create another single-use newtype to use here.
3) Create a generic newtype to use both here, and in storage subscribers where I've previously fixed this problem.
4) Refactor the sender/receiver types (`TracingUnboundedReceiver` etc.) so that they have this functionality built-in, so that everywhere they're used we get an unsubscribe-on-drop behavior essentially for free.

Personally I'd probably go for (4), although that would be the most work.

_Originally posted by @koute in https://github.com/paritytech/substrate/pull/10568#discussion_r777483403_

**Comment by andresilva** [comment]
I am not sure how to go about implementing 4) since it seems to me that the problem is clearing up stale senders whenever there's no one listening, this assumes that there is some central registry where subscribers are accumulated which isn't the case for 4). 

It seems to me that 3) is the most actionable way to go with https://github.com/paritytech/substrate/blob/master/client/utils/src/notification.rs being the "registry" types I alluded to above. I think it should be possible to extend the `NotificationStream` type to clear `SharedSenders` on drop. These types could then be re-used to implement the functionality in https://github.com/paritytech/substrate/blob/master/client/api/src/notifications.rs#L83-L123.

@koute Do you agree? I can extend this issue with more details once you confirm.

**Comment by koute** [comment]
> I am not sure how to go about implementing 4) since it seems to me that the problem is clearing up stale senders whenever there's no one listening, this assumes that there is some central registry where subscribers are accumulated which isn't the case for 4).

@andresilva By "built-in" I didn't mean that it will automatically work in every case; I meant that you won't be able create a channel without also providing some sort of an "unsubscribe" callback (or an `Arc`/`Weak` handle with such, etc.), so it wouldn't be possible to ignore this problem without *explicitly* passing in an empty one which does nothing.

Basically, make it harder to do the wrong thing by default. Not clearing the subscription on drop should be opt-out, and *not* opt-in as it currently is.

**Comment by RGafiyatullin** [comment]
### `tokio::sync::broadcast`?
Can we opt into using `tokio::sync::broadcast::{Sender,Receiver}` to do the whole heavy lifting with subscribe/unsubscribe routines?

I understand that it has a completely different approach to handling slow-consumers: drop the items that haven't been consumed in-time and inform the consumer that it is lagging.

But configuring a large but predictable channel-capacity in my opinion is better that having  an unbounded buffer per each consumer.

**Comment by koute** [comment]
Well, unbounded buffers are currently used where they're used for a reason (otherwise we would have made them bounded already I assume), so just blindly replacing them with bounded buffers will most likely not be appropriate without a deep case-by-case understanding of the consequences.

It's a worthwhile goal, but it's kinda out-of-scope of this issue, and I'm guessing it'd be orders of magnitude more work. As a first step we probably just want to make sure that we won't leak any subscriptions, and then we can think about getting rid of unbounded buffers.

**Comment by RGafiyatullin** [comment]
Within that issue nothing will be done to the pair of `::sc_utils::mpsc::{TracingUnboundedSender, TracingUnboundedReceiver}`: those are to remain just the MPSC channel with metrics.

As per @andresilva 's comment I will think what can be done in order to generalise the pub-sub in `sc_client_api::notifications` and `sc_utils::notification`, starting with the common way to perform un-subscription eagerly upon rx-side being dropped (so that the stream liveness would not be essential for "garbage collection" on the tx-side).

**Comment by andresilva** [comment]
I feel like that's the most straightforward way, it's essentially the same as @koute suggested in the chat earlier today but we re-use a type for the registry (from `sc_utils::notification` instead of creating a new trait for the registry) and we don't make any changes to the channels themselves.

**Comment by RGafiyatullin** [comment]
> I did not yet analyzed the entire pr very close, but are there any implementation details besides the removal of this one clean up method?

Both `sc-utils::notification` and `sc-client-api::notifications` have been reworked so that
- they preserve the existing interface;
- the logic for subscription and sending the messages is moved into the implementaiton of the traits defined in `sc-utils::pubsub`;
- the logic for management of the underlying channels is moved to the implementation of `sc-utils::pubsub::Channel` (implemented by `sc-utils::pubsub::channels::TracingUnbounded<T>`).

Specifically, the `sc-utils::notification::Registry` implements:
- `Subscribe<()>` — any subscriber will receive all the messages from the hub;
- `Dispatch<Message, Item = Message> where Message: Clone` — each `Message` sent through this hub will be cloned and passed to all the subscribers.

Specifically, the `sc-client-api::notifications::Registry` implements:
- `Subscribe<( FilterKeys, ChildFilterKeys )>` — subscribers specify the keys they are interested in;
- `Dispatch<( Hash, ChangeSet, ChildChangeSet ), Item = ( Hash, StorageChangeSet )>` — the registry delivers the pair of Hash and StorageChangeSet only to those subscribers that are interested in the currently propagated changes.

> I also did not really followed the initial discussion about the issue that should be solved, but I would have expected that we also see changes outside of the definition of these utils because we want to simplify other code?

The original discussion raised the question of the same job (unsubscribe upon rx drop) is being solved in several places several different ways. 
Hence the PR addresses that particular issue by making the similar components to use the single generic backend.

**Comment by RGafiyatullin** [comment]
[Done (PR#10708)](https://github.com/paritytech/substrate/pull/10708)
