### ISSUE TITLE
Events from on_runtime_upgrade are unavailable

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#10603]
`on_runtime_upgrade` hook is executed before `initialize` and which initialize fields like block number as well as kill all the events from previous block. This means events from `on_runtime_upgrade` are also removed by `initialize`.

This makes debugging harder as well as make events incomplete. It will not be possible to observe changes by only look at events.

I can see reason why it is executed before `initialize` but most of the time, the reason doesn't apply and that means code from `on_runtime_upgrade` will have no event, read old block number, read bad execution phase, etc.

**Comment by bkchr** [comment]
The idea would be to move these lines of code:
https://github.com/paritytech/substrate/blob/master/frame/system/src/lib.rs#L1323-L1327

That is currently being called here:
https://github.com/paritytech/substrate/blob/master/frame/executive/src/lib.rs#L301-L306

Above these lines here:
https://github.com/paritytech/substrate/blob/master/frame/executive/src/lib.rs#L298-L300

I think the best would probably be to create a special `clear_events` functions this would then be called inside `Executive`. We should then also be able to drop the `InitKind` enum because we can control from the outside when the events are being cleared.
