### ISSUE TITLE
host-perf-check sub command

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#10818]
Inspired by https://github.com/paritytech/polkadot/pull/4342

A subcommand that runs the [baseline benchmarks](https://github.com/paritytech/substrate/blob/master/frame/benchmarking/src/baseline.rs) and output a score (or a set of scores) indicating the performance of the machine.

This will help node runners (especially collators and validators) to check if their machine is up to the spec by comparing the score with numbers from reference hardware.

**Comment by ggwpez** [comment]
I generally like the idea to make it simpler to gauge new hardware.  
The baseline benchmarks are probably not enough to do that. Running all benchmarks (~6 hrs) and then comparing the results to a worst-cast hardware could work though.  
Currently there is no proper tooling in place to easily compare results, so that would need to come first.

CC @shawntabrizi

**Comment by xlc** [comment]
Closed by https://github.com/paritytech/substrate/pull/11198
