### ISSUE TITLE
Add ability for try runtime hooks to directly pass data

### ISSUE THREAD

**Issue by emostov** [paritytech/substrate#10824]
Currently, if a user of the hooks `fn pre_upgrade() -> Result<(), &'static str> {}` & `fn post_upgrade() -> Result<(), &'static str> {}` wants to persist data between the two functions they must use runtime storage (see https://paritytech.github.io/substrate/master/frame_support/traits/trait.OnRuntimeUpgradeHelpersExt.html#method.get_temp_storage). This approach is suboptimal for users who may want to ensure that the storage root has not changed during the execution of either hook (ref: https://github.com/paritytech/polkadot/pull/4772#discussion_r801707223).

Instead, a user should be able to persist some information to help verify a migration has executed successfully without modifying the runtime state. A proposed approach is that the functions be modified to output and accept some data. For example the new hook signatures could something look like:

```rust
trait OnRuntimeUpgrade {
    ...
    fn pre_upgrade<O>() -> Result<O, &'static str> {}
    fn post_upgrade<I>(_input: I) -> Result<(), &'static str> {}
}
```

**Comment by ayevbeosa** [comment]
I am interested in working on this. Where would you suggest would be a good place to start.

**Comment by emostov** [comment]
I would start by modifying the trait functions signatures and docs here

https://github.com/paritytech/substrate/blob/66ff3a566e6ee7d85f30fc11d45047bd41854b9e/frame/support/src/traits/hooks.rs#L176-L187

and here

https://github.com/paritytech/substrate/blob/66ff3a566e6ee7d85f30fc11d45047bd41854b9e/frame/support/src/traits/hooks.rs#L263-L274

to roughly:

```rust
    fn pre_upgrade<O>() -> Result<O, &'static str> {}
    fn post_upgrade<I>(_input: I) -> Result<(), &'static str> {}
```    

To prove to yourself it works, in the tests mod of `hooks.rs` you could impl the trait for a dummy struct and write a simple test showing the intended behavior. This isn't necessary though and probably wouldn't get merged in, just recommending if you feel your understanding is shaky. 

Then you can go through pallets that have impls for `pre_upgrade` and `post_upgrade` and update their function signatures. For all pre-existing cases the signature should look like something like `pre_upgrade() -> Result<(), &'static str>` and `post_upgrade<I>(_: I) -> Result<(), &'static str>`.

Once that is done you will also need to create polkadot companion that updates the method signatures in polkadot. See here for instructions: https://github.com/paritytech/substrate/blob/master/docs/CONTRIBUTING.adoc#updating-polkadot-as-well

**Comment by emostov** [comment]
Let me know if this sounds ok and you intend to start working on this so I can assign the issue to you.

**Comment by ayevbeosa** [comment]
This sounds okay to me and I intend to start working on it. Thank you very much for the explanation, I have a clearer idea on what to do now.

**Comment by ayevbeosa** [comment]
This is looking more complicated than I anticipated, I am considering dropping it.

**Comment by daanschutte** [comment]
Hey @emostov, I'd like to give this one a go.

**Comment by emostov** [comment]
> Hey @emostov, I'd like to give this one a go.

@[daanschutte](https://github.com/daanschutte)  Sounds good, let me know if you have any questions

**Comment by daanschutte** [comment]
@emostov I've been stuck on this for way to long so thought I'd make use of the `mentor` tag ;)

In my tests, it appears that the `#[cfg(feature = "try-runtime")]` attribute is somehow preventing the functions from being called correctly.

If I drop the attribute altogether (including the trait definition) everything works as expected. If it is present somewhere I get a ```no function or associated item named `pre_upgrade` found for struct `hooks::TestOnRuntimeUpgrade` in the current scope``` or some kind of variation thereof, depending on what I change.

If I add the attribute everywhere the tests run (and pass, somehow) but the functions aren't actually called (expected debug output from the function is not printed).

I suspect the root cause of this is the `no_std` of the `#![cfg_attr(not(feature = "std"), no_std)]` set in `try-runtime`, and I understand that we would probably want this feature enabled, but I'm having a hard time trying  to get them to play together. 

Any pointers would be appreciated!

**Comment by daanschutte** [comment]
Of course 10 minutes after I sent that I figured out the problem... Turns out if I want to test the feature I should enable it when running the tests :facepalm:

**Comment by daanschutte** [comment]
This one is turning out to be lot more complicated than I anticipated, and unfortunately I just don't have the time available at the moment to dedicate finding a solution. I'll keep following it since I'd really like to see the solution here but if someone else wants to pick it up in the meantime it may be resolved sooner.

**Comment by kianenigma** [comment]
additionally, as @shawntabrizi pointed out in other mediums, we should assert that `pre_upgrade` and `post_upgrade` are actually `storage_noop!`. A `pre_upgrade` should never alter the storage, because then it can, in principle, affect the `on_runtime_upgrade` itself.

**Comment by NingLin-P** [comment]
Here come the next challenger :) , I'm going to have a try.
