### ISSUE TITLE
Convenience flags for `benchmark-storage`

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#10929]
Some low hanging fruits that were omitted in the first iteration:  
- [ ] `--no-json`: Do not create json files.
- [ ] `--json-path`: customize the json output path. Maybe with string interpolation of `"$DB"` and `"$RUNTIME"` variables.
- [ ] `--template-path`: override the HBS template to use.
- [ ] Extend the warmup round to include write benchmarks.
- [ ] Add the Blocknumber that was used to the HBS template.

**Comment by daanschutte** [comment]
Hi @ggwpez, I'm interested in attempting this one (new to the project and to rust). 

Any pointers for where to start?

**Comment by ggwpez** [comment]
Hey @daanschutte!  
Nice to hear. The `--no-json` is really simple to implement, if you are just starting out.  
  
Its about adding a flag that prevents the JSON files to be written, currently they are always written.  
The code is in `utils/frame/benchmarking-cli/src/storage/cmd.rs`.  
You can also do more than that but decide for your self.

**Comment by daanschutte** [comment]
@ggwpez could you please provide some clarity on the intended behaviour of `--json-path`?

Since a single, user-specified path name would not work (the output of the write data will overwrite the output of the read data),
- Do we want to in fact just specify a `--json-prefix` to the current filename scheme (e.g. `<prefix>_db_read.json`)?
- Alternatively, would it be useful to give the user full control with both a `--json-read-path` and a `--json-write-path`?

**Comment by ggwpez** [comment]
> Since a single, user-specified path name would not work (the output of the write data will overwrite the output of the read data),

Yea, did not think about that. 

Maybe you can turn the behaviour of JSON generation around and only generate the specific files when  `--json-read-path` or `--json-write-path` is present. Then we do not need the `--no-json`.  
I think this would be the easiest for now, unless you find something even better 😊 @daanschutte

**Comment by daanschutte** [comment]
Sounds good 👍

I'll think it over a bit.
