### ISSUE TITLE
Recovery pallet does not have benchmarking, or weights measured

### ISSUE THREAD

**Issue by NukeManDan** [paritytech/substrate#11093]
There are only hard-coded weights in the [pallet presently](https://github.com/paritytech/substrate/tree/master/frame/recovery) and no `benchmarking.rs` enabling `runtime-benchmarks` feature to measure/produce them.

**Comment by ayevbeosa** [comment]
I am interested in working on this.

**Comment by ggwpez** [comment]
> I am interested in working on this.

Nice. Have you done benchmarking before? @ayevbeosa   
Looking at the code of the recovery pallet; some extrinsics seem rather complex. So you can start with the easy ones like `set_recovered`.  
That should already help to get the structure in place to further extend it. Otherwise if you aleady know benchmarking you can obviously do more.

**Comment by ayevbeosa** [comment]
> Nice. Have you done benchmarking before? @ayevbeosa

I haven't really. I guess I will start from where you suggested. Thank you.

**Comment by ayevbeosa** [comment]
I am having issues getting the tests to pass, I was hoping you could me out.

**Comment by ayevbeosa** [comment]
Noted, thank you very much
