### ISSUE TITLE
conditional compilation not possible on pallet calls

### ISSUE THREAD

**Issue by nbaztec** [paritytech/substrate#11151]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

A pallet with a conditional compilation directive fails to compile as there are still references to it in the [generated code](https://github.com/paritytech/substrate/blob/master/frame/support/procedural/src/pallet/expand/call.rs#L171).

### Steps to reproduce

Attempt to compile:

```rust
#[frame_support::pallet]
pub mod pallet {
	#[pallet::pallet]
	pub struct Pallet<T>(_);

        #[pallet::call]
	impl<T: Config> Pallet<T> {
		#[cfg(feature = "foobar")]
		#[pallet::weight(0)]
		pub fn foobar(_origin: OriginFor<T>) -> DispatchResult {
			Ok(())
		}
        }
}
```

Fails with compilation errors in the `Call` implementations:

```
function or associated item not found in `pallet::Pallet<T>`
```

**Comment by ggwpez** [comment]
I remember doing something like this for non-extrinsic functions of a pallet [here](https://github.com/perun-network/perun-polkadot-pallet/blob/b5a1897cdf5c7755cddfb2b1841331acab349aba/src/lib.rs#L476).  
You could use that approach to put the actual logic into an associated non-member function and have a no-op in the case that the feature is not enabled.  

I'm not sure if it makes sense to have feature-enabled functions in frame, since then a pallets API easily breaks.

**Comment by nbaztec** [comment]
> You could use that approach to put the actual logic into an associated non-member function and have a no-op in the case that the feature is not enabled.

Yeah that was plan B, albeit ugly :) 

> I'm not sure if it makes sense to have feature-enabled functions in frame, since then a pallets API easily breaks.

Fair enough. The functionality would definitely have been useful for in case of providing configurable hotfix functions as a library.
