### ISSUE TITLE
RPC metadata with types

### ISSUE THREAD

**Issue by ascjones** [paritytech/substrate#11181]
Currently all client implementations must maintain manual mappings for available RPC methods. 

We should provide metadata for the available RPC calls, together with [ `scale-info`](https://github.com/paritytech/scale-info/) type information for the parameters and return types. The metadata for an RPC call could take the following form:

```rust
struct RpcMetadata<T: scale_info::form::Form> {
    name: T::String,
    args: Vec<(T::String, T::Type)>,
    return_type: T::Type,
}
```
So this metadata would need to be generated at the site of the RPC definition, and then collected together with other RPC definitions and made available via an RPC call itself.

Raised in this SE question: https://substrate.stackexchange.com/questions/1631/rpc-full-type-specification-from-metadata. Related: https://github.com/paritytech/subxt/issues/416

**Comment by bkchr** [comment]
I'm still not convinced that we need this. We already had this discussion once here: https://github.com/paritytech/substrate/issues/10065

**Comment by bkchr** [comment]
I mean I'm not against having some proper documentation, this is for sure required. @tomaka's approach [here](https://paritytech.github.io/json-rpc-interface-spec/) looks really good. 


> This is the one area where, as soon as you customize types or adding new endpoints, it requires code updates somewhere. (Your own chain, it gets added to your published JS type bundle, on the stock-standard Substrate/Polkadot/Kusama chains, this means you need to update your JS API version.

While I get this, it would still need the "end user dev" to change its code to use the new RPC method. We could cut out the middle man, aka you, to add these new rpc methods. However, I really hope that with the new RPC interface description the core RPCs don't get changed that often. If someone defines their own RPC for their chain, adding support for it in their own libs is probably not that hard?

**Comment by tomaka** [comment]
This feels very strongly like solving an XY problem.

Adding metadata to the RPC calls that can be automatically parsed is cool if your objective is to just query data through an RPC call is display it to the user.

If you want to actually programmatically interpret the response (which is arguably what the JSON-RPC API is about), then this metadata is useless. You can't for example write a program that automatically understands what the fields in a header are. You need to assume for example that this header contains a block number and a parent hash. In other words, generating metadata for the RPC calls would only duplicate the information that you need to put in the program that calls the functions.

**Comment by tomaka** [comment]
What, for example, if the `RpcMetadata` struct that Andrew suggest above is modified?
You could add some meta-metadata that contains metadata about `RpcMetadata`, but then this meta-metadata could be modified as well. If you add a meta-meta-metadata, then it can be modified as well.
At some point you need stable foundation that is standard and is the same everywhere and whose definition is copy-pasted everywhere, and I think we all agree that if we add this `RpcMetadata` then it should never have any breaking change.

My point, however, is that this foundation shouldn't be `RpcMetadata`, as proposed here, but instead the list of JSON-RPC functions themselves.

The API that I've put up at https://paritytech.github.io/json-rpc-interface-spec/ is designed to be the same for every chain, and doesn't requiring interpreting any SCALE-encoded piece of data in order to be used, thus rendering `RpcMetadata` useless.

**Comment by jacogr** [comment]
The modification of the `RpcMetadata` struct, like with `Metadata` is alongside a version bump. The `rpc_methods` already provides it, but in this case I would suggest an endpoint in the same fashion as `getMetadata()`, i.e. no re-use altyhough the version _can_ be changed, since you need to convey information.

- in the runtime world, when the description structure changes, the version is bumped
- in the RPC world, when the description structure changes, the version is bumped

**Comment by dvdplm** [comment]
The API is the stable foundation, I don't think anyone here is arguing otherwise. Adding a machine readable and versioned description of that API's arguments and return types seems like a useful addition to me and I don't see a contradiction between the two. 
I'm more sensible to @bkchr's argument of "do we really need this?"

**Comment by tomaka** [comment]
There's no contradiction between the two, I'm also defending the point of view that this is a useless addition that adds more complexity again and again.

**Comment by tomaka** [comment]
> In your example, for instance I see functions that return of both Header and Block. For these the structure is important. As is types in those structures. We say for instance ["String containing an opaque value representing the operation"](https://paritytech.github.io/json-rpc-interface-spec/api/archive_unstable_header.html) so need to know how to do the opaque.

This is a string representing the operation, similar to a `subscriptionId`. It _must not_ be interpreted by the client.

> Is BlockNumber a u32 or a u64? Are there extra fields that are not in the Substrate Header? So the types remain. This is what the RPC metadata is supposed to address - the type definitions. It is no less important than on the runtime knowing these, although it is certainly less likely to change.

In my new API you never need to know the block number in order to use the API. For example you can follow storage items without any problem without having to decode a header at any point.

If you need to know the block number, the `BlockNumber` type and the format of `Header` are extractable (or if they're not, they should be) from the on-chain metadata. And you don't need to know anything about the chain in order to obtain the on-chain metadata.

**Comment by tomaka** [comment]
As a more meta remark, I think that proposals need to be better argued, presenting some context and motivation, rather than saying "hey I want to do X, what do you think?". One should explain why a change is desired, what its drawbacks are, and what the possible alternatives are and why they're not better than the proposed change.

**Comment by jacogr** [comment]
Ok. So I still want the header - I need to access it to get the parent hash and logs as an example. So I cannot get away from decoding it. Any API that doesn’t give me headers or blocks doesn’t quite expose the chain :)

You are only thinking of storage. It is a solved problem since we have the types in metadata.

**Comment by ascjones** [comment]
> As a more meta remark, I think that proposals need to be better argued, presenting some context and motivation

FWIW I am agnostic on this feature, I didn't spend a lot of time thinking about it (hence the underspecified issue). I have received multiple requests for this, so worth putting an issue to point people at if nothing else, and to spark the debate.

I think this _might_ be useful, but the question is would it be useful enough to be worth the costs (implementation, complexity etc.).

One pro would be to avoid having to copy rpc request/response types e.g. https://github.com/paritytech/cargo-contract/blob/3db4734c1a056f8834f0b0e35a77a4ef334fc79f/src/cmd/extrinsics/call.rs#L164. OTOH they may not change that often so :shrug:

**Comment by tomaka** [comment]
> Ok. So I still want the header - I need to access it to get the parent hash and logs as an example. So I cannot get away from decoding it. Any API that doesn’t give me headers or blocks doesn’t quite expose the chain :)

The new API gives you the parent hash of each block when it notifies it: https://paritytech.github.io/json-rpc-interface-spec/api/chainHead_unstable_follow.html#newblock

**Comment by jacogr** [comment]
I'm not fighting your specification, I'm saying I still need to decode the encoded values inside it and have a specification for it.

If I request and receive a `Header`, I need to know what is in it and how to decode it - these are not fixed, chain add fields to their own specification. When I get a block body, the same thing. If I request data from a contract RPC, I need to know what is inside it and how to decode it. Unless I want to still [continue answering](https://substrate.stackexchange.com/questions/530/invalid-params-unknown-field-storagedepositlimit-error-when-getting-contract) [the same question](https://github.com/polkadot-js/api/issues/4643) because a structure changed on an RPC call.... incidentally the same link Andrew pointed to above.

The RPCs have an insane amount of types that go in and out, not storage, blocks or headers. A sample - `ExtrinsicStatus` (it is an enum, it is not fixed), `EpochAuthorship`, `BeefySignedCommitment`, `Header`, `SignedBlock`, `ContractCallRequest`, `ContractExecResult`, `ContractInstantiateResult`, `CodeUploadRequest`, `CodeUploadResult`, `BlockStats`, `CreatedBlock`, `Justification`, `EncodedFinalityProofs`, `ReportedRoundStates`, `JustificationNotification`, `MmrLeafProof`, `StorageKind`, `RuntimeDispatchInfo`, `FeeDetails`, ... there are more, just grabbed the first one that fit on a screen.

I certainly welcome a well-specified RPC interface, and quite happy to hardcode those - but types returned...

**Comment by tomaka** [comment]
If you take all the contracts-related JSON-RPC calls, they do nothing but call in the runtime. In other words, they're literally nothing more but shortcuts for the `state_call` function. And the list of runtime calls and the format of their parameter and return value is already in the on-chain metadata.

Don't you find this design completely insane? We're adding RPC shortcuts that add no value, and then we realize that the shortcuts are unusable, so we add even more features to make the shortcuts usable?

**Comment by jacogr** [comment]
I love a coherent API - where I can map the responses to be decoded.

`RpcCallRequest` does not appear in the metadata since -

(a) it is not used in storage
(b) it is not in an event
(c) it is not in an extrinsic
(d) ... it is only used on RPC

Point (d) is what I would like fixed and what this issue is all about :)

**Comment by tomaka** [comment]
`RpcCallRequest` is just [the list of parameters of `Contracts_call`](https://github.com/paritytech/substrate/blob/ded44948e2d5a398abcb4e342b0513cb690961bb/frame/contracts/rpc/runtime-api/src/lib.rs#L44-L49), right?
If so, then they *are* in the metadata that you've linked.

Again, `RpcCallRequest` is just part of a shortcut for `state_call`. You could simply directly call `state_call` with the list of parameters.

**Comment by jacogr** [comment]
You are linking to a call which takes discrete params, the RPC call takes a struct. So basically in this case you the SDK developers me to map the runtime call and create and own struct out of it to pass? This means I need to have an in-depth understanding of the RPC myself to re-implement it.

I'm not suggesting the RPC _should_ be there - I'm suggesting that I cannot make stuff up here.

**Comment by seunlanlege** [comment]
Having rpc metadata greatly simplifies the lives of people who directly use substrate.

Here i am writing a relayer and having to have a tab open of my custom rpc methods, when intellisense + subxt generated types would've made this a breeze. 

the old jsonrpc actually supported this by generating a client interface, i'm not sure if the new one does.

**Comment by xlc** [comment]
I think this one could be closed in favor of https://github.com/paritytech/substrate/issues/11648 
Implementation-wise it is more easier to annotate runtime APIs compare to custom RPCs.

**Comment by ascjones** [comment]
Agreed
