### ISSUE TITLE
Custom Voting Rules for GRANDPA

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#1125]
This should allow us to additionally restrict the chain being voted upon based on chain-specific voting rules.

**Comment by rphmeier** [comment]
We will probably want to do this in some more generic way so the same rule can simultaneously be used to restrict e.g. the chain heads we are willing to build on in Aura or some other block production rule

**Comment by rphmeier** [comment]
Still in favor for doing this in 1.0-final

**Comment by gnunicorn** [comment]
So, just to share my current line of thought and approach I am taking:

 1. Consensus shouldn't rely on `Client` to calculate `best_chain`, but rather on a new `trait ChainSelectionStrategy`
 2. this `CCS` can then be implemented in a variety of ways, depending on your local needs, with our default implementation providing a `LongestChainRule`
 3. This means, for the most part, refactoring `client` to remove the existing proxy calls to `Backend` out of it and into a the new implementation

I am currently thinking of putting that base trait into `consensus-common`, but I am not sure the dependency tree will allow that. It will looks something like this:

```rust
/// Define how to select the best chain if there was a fork
trait ChainSelectionStrategy<B: Block> {

	/// Get best block header
	pub fn best_block_header(&self) -> Result<B::Header>;

	/// Get the most recent block hash of the best chain
	/// that contain block with the given `target_hash`.
	pub fn best_containing(&self, target_hash: B::Hash, maybe_max_number: Option<NumberFor<B>>) -> error::Result<Option<B::Hash>>;
}
```

`client` would provide a `LongestChain` implementation based on block-count (as we do now), but we could also provide an example implementation, that picks the chain with the highest transaction count rather than just blocks. From what I can see so far, these implementations would probably require to have an access to `Arc<Backend>`, which is fine, as `client` already provides that (they could technically also bind to `client` but that is more dirty IMHO). The developer would then be able to configure it through the usual services-definition. On `node` we could, further more, provide a proxy-implementation that picks from the implementations based on a `yaml`- or genesis-config value.

I'll start coding up some first steps into this direction later this, early next week.

**Comment by rphmeier** [comment]
> Consensus shouldn't rely on Client to calculate best_chain, but rather on a new trait ChainSelectionStrategy

bikeshed: `trait SelectChain`. The docs make it sound like a fork-choice rule for consensus, which it isn't. Also, are you proposing that `best_block_header` on `client` directly be removed and that we have instead multiple possible "best block" rules?

The goal is to generalize a bit over things like "select the longest chain containing X" to e.g. "select the best chain containing X". We might have multiple criteria of "best" at the same time, so making them all fit together is kind of hard. A `&Backend` parameter might might nesting easier.

The main challenge I see is that some of these chain selectors will want to use arbitrary metadata associated to each block (in Polkadot's case: use whatever "consensus" says is the best chain, but limit it to the blocks where we've received availability data for each of them). That probably means tying them to the DB a little bit more closely.

**Comment by gnunicorn** [comment]
> bikeshed: `trait SelectChain`
ack

> The docs make it sound like a fork-choice rule for consensus, which it isn't.

docs are copy-pasted from client. however, that is what I thought this was about: a mechanism you could provide to figure out an arbitrary definition of "best". right now, best is defined as "longest', but you then could also implement a version that has more complex behavior describing that definition (like for polkadot). I'd still put that into one particular implementation rather than have multiple singular ones, because then you'd have to weight them or find some other way to describe the priority to one another (and we don't really know any of these yet).

Anyhow, I think we are saying the same things but think of it from opposite directions and as such use different wording. I'll get going on that and we'll see if that in code the ideas do match up :) .

**Comment by rphmeier** [comment]
> I'd still put that into one particular implementation rather than have multiple singular ones, because then you'd have to weight them or find some other way to describe the priority to one another (and we don't really know any of these yet).

Unfortunately, we will need multiple ones for Polkadot because BABE and GRANDPA will use slightly different chain-selection strategies -- BABE will allow missing availability chunks for some K recent blocks, while GRANDPA will tolerate none.

**Comment by gnunicorn** [comment]
I see ... :thinking: hmmm... this makes it quite a bit more complicated I guess...

Or maybe... the distinct factor is whether it is `authoring` (as `BABE`) or finalisation (as for `GRANDPA`), is that correct? Are these the only two cases? In that case, we could have two distinct functions to calculate each for the operation necessary (and by default, in the main trait, one is just an alias for the other). Would that do? Or do we have even more complex cases?

**Comment by gnunicorn** [comment]
Just some quick info. Multiple attempts in refactoring this nicely all ended up in some ugly way: 
 - adding the new trait right on the client or having the client provide the implementation of the new trait, leads to adding _yet another `where`-bounds_ to _every instance_ using the `client`, which is already polluting (imho) a lot of places as it stands and I don't want to add yet another that 99% of code doesn't care about
 - thus externalising it completely from client worked resonably well, until you realise it isn't only bound to `backend` (that worked fine) but also accesses `client.import_lock`, which either means connecting client to the trait (yikes, and not possible, as it would create a circular dependency), leaking `import_lock`, which create an ugly (and otherwise unnecesary) `'a` lifetime bound to everything touching the trait or - and that is the approach I'll try next - we can't have this happen automatised but instead must provide another `fn build_select_chain` (next to the type we need anything) in the ServiceFactory definition..

I tried to prevent the later, but already our `LongestChain` implementation can only work once it has access to a `client` instance.. :( ...

(client really needs some cleaning up and refactoring...)

**Comment by gavofyork** [comment]
@gnunicorn i presume this is sorted now? Please reopen if not.
