### ISSUE TITLE
Allow multiple sudo keys in the sudo pallet

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#11409]
With all having the same permission. Simply helps with testnet management, and makes calls traceable to a particular key that a team might know is owned by a certain person. All keys can add or remove keys. 

> Or, perhaps only the first sudo can add or remove keys, but even that seems too complicated. Since sudo is not really meant for production, probably allowing all to do everything is easier. 

Does this make sense? if so, this will make a perfect task for an interview candidate, or a first issue for an external contributor. 

cc @lovelaced

**Comment by xlc** [comment]
just add some proxy?

**Comment by kianenigma** [comment]
Hmmm yeah now I actually recall that we we did discuss this as well. @lovelaced was there any advantage to having multiple sudo keys than multiple Any proxies that I can't recall? otherwise I think this is superfluous.

**Comment by lovelaced** [comment]
The current state of the options we have is (quote from @SBalaguer ):

- Using the SUDO account.
   1. The most secure thing to do is to use a keyless account as a SUDO account, and not the original account when the runtime is created.
   2. The new SUDO keyless account could then have a bunch of proxies to act on behalf of it.
   3. It's going to be key to discuss if a multisig with a 1/n schema is actually needed or if it's best to create proxies for different accounts for different users.

- Using the Proxies
   1. Instead of creating proxies directly and sharing the private keys, each team member can create its own account and then these can be added to the keyless SUDO.
    2. Once the keyless SUDO (or any other SUDO for the matter) has a proxy, then the team member needs to have his/her account (the one added as proxy) and add the SUDO (keyless or not) as proxy on PolkadotJS. This was the step we were missing.
    3. Unfortunately, Proxy 'types' are very limited, and only a very specific list of actions can be used. In order to extend the usage, the idea is to create time-delayed proxies with a type of 'any', and a script that can cancel a proxy transaction if the proxy executing that should not do that type of transaction. For example, the idea is that I have control only for the parachain stuff. If I use my Proxy of type 'Any' to execute a balance transfer, then the script would pick this up and submit a cancellation of the call and therefore I would not be able to complete the call. This has to be developed, and therefore the idea is not to use time-delayed proxies yet, but have that as a possible feature in the future.

**Comment by bkchr** [comment]
I also don't see why you need multiple sudo keys. All of this can be done with proxies. I also don't see that we need some offchain functionality that observes all the calls. At some point you have to trust people that they don't fuck it up.

**Comment by lovelaced** [comment]
The way I'm framing it in my head is just thinking about if we were to admin a production chain that still retained sudo (like a private PoA chain or whatever). In this setup you would probably want some level of distribution of privileges and never share private keys. The way I would expect it to look would be, from a high level:

a sudo account, probably a multisig
various accounts which have abilities to call certain types of things which would normally require sudo, which have different accounts associated, so there is an audit trail rather than sharing private keys. Proxies work pretty well here as long as the stuff we want to do is contained in an existing proxy, but that's not the case in this particular circumstance.

Sorry if there's any misunderstandings by me in here, but for example it would be nice to not have to share the sudo key and instead just create separate accounts for everyone who wants to do various privileged actions (usually a particular subset/type).

**Comment by bkchr** [comment]
Proxy supports all pallets, not sure which one it doesn't support?

**Comment by SBalaguer** [comment]
May I misexplained myself or I'm outdated on the information, but AFAIK the `proxy_types` do not cover all the range of permissions that the SUDO pallet will want to give different users. For example for testnet management, a proxy can't only control parachain onboardings; for doing so it needs complete access which would be of type `Any`.

**Comment by bkchr** [comment]
The proxy type is defined in the runtime and it is completely up to you, how to design this. We can just add a variant for parachain related stuff.

**Comment by SBalaguer** [comment]
Perfect, that was my intended point! Not that it _didn't_ work, but we needed to configure it :)

**Comment by lovelaced** [comment]
Ok sgtm, then that is my request :)

**Comment by xlc** [comment]
You either have sudo or not. If you have sudo access directly or indirectly, you have maximum permission. If you don't, you don't. There is not such mechanism that only allow limited sudo.

If you really need to only allow some account have limited access to parachain related calls, just write a custom pallet for it. It is easy.

**Comment by kianenigma** [comment]
Clearly proxies are the way to go.
