### ISSUE TITLE
Latest tagged ci-linux Docker image failing

### ISSUE THREAD

**Issue by ntn-x2** [paritytech/substrate#11731]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

It seems that using the latest tagged `ci-linux` Docker image fails to compile/test our project in a GitLab runner.

We have an [open PR](https://github.com/KILTprotocol/kilt-node/pull/370) to upgrade deps to 0.9.24, but it seems that anything different than `paritytech/ci-linux:production` fails to build the project because of an error related to `prost-build v0.10.4`.

[Here is a link](https://gitlab.com/kiltprotocol/mashnet-node/-/jobs/2623116066) to the latest failed CI job that was trying to use `paritytech/ci-linux:eb1f6a26-20220518` (the latest image that is not `production` nor `staging`), while [here is a link](https://gitlab.com/kiltprotocol/mashnet-node/-/jobs/2623205567) with a successful job using `patitytech/ci-linux:production`.

We would rather upgrade the CI image version ourselves rather than always using the latest `production`. Is using `production` now the recommended way?

**Comment by bkchr** [comment]
CC @TriplEight

**Comment by TriplEight** [comment]
> anything different than `paritytech/ci-linux:production`

This is correct. `error: failed to run custom build command for `prost-build v0.10.4` [error](https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/1624127/raw) was caused by the fact is started to require `protoc`, which wasn't installed into a CI image. Now it is [added](https://github.com/paritytech/scripts/blob/master/dockerfiles/base-ci-linux/Dockerfile#L43) (the base image for `ci-linux`) and exists in `paritytech/ci-linux:production` only. The reason it's alone is that we're not pinning stable Rust there and it [tries](https://gitlab.parity.io/parity/mirrors/scripts/-/pipelines/200156) to upgrade the stable version, but we're not yet there with some updates to a new stable. Then the tests will succeed and there will be another images.

> Is using `production` now the recommended way?

Yes, It's automatically released nightly after being tested against Substrate and Polkadot, you can rely on it. And it's been like that for quite some time.

**Comment by TriplEight** [comment]
@ntn-x2 usually, we've had every `production` image also released with a SHA, it's just wasn't the case this time. Thanks for the headsoup anyway, I'll have this in mind the next time.
