### ISSUE TITLE
Fast path for importing locally-authored or consensus-checked blocks

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#1232]
Right now, we have a block-authoring pattern in Aura where we a) build the block and b) re-execute and import.

In Rhododendron, we either build a proposal or evaluate someone else's and then re-execute and import.

In both situations, there should be a shortcut-path through `BlockImport` for blocks which already have been executed.

**Comment by gnunicorn** [comment]
> and b) re-execute and import.

You sure? Because the [importer does commit the changes](https://github.com/paritytech/substrate/blob/691e6e8f1c3b9e8f3b54a8c78183469f3472e293/core/client/src/client.rs#L640) (even from the proposer) for said block to the database and the next time `execute_and_import` is triggered, it should [stop early with the success-code `AlreadyInChain`](https://github.com/paritytech/substrate/blob/691e6e8f1c3b9e8f3b54a8c78183469f3472e293/core/client/src/client.rs#L552), no? 

What conditions would lead to us executing the block twice? Which code path even allows for that to happen?

**Comment by rphmeier** [comment]
As far as i know, we don't pass the state changes generated by building the block to the client. And `execute_and_import_block` calls the `execute_block` api, which, if this was a locally authored block, is a re-execution.

**Comment by rphmeier** [comment]
This will require altering the `Proposer` trait so some kind of "execution result" is returned as opposed to just the block.
