### ISSUE TITLE
Support "non longest" chain fork choice rules

### ISSUE THREAD

**Issue by sorpaas** [paritytech/substrate#1237]
Refer to this TODO: https://github.com/paritytech/substrate/blob/8a19aa544fc45c662f54c7717fb87702028dc4e5/core/client/src/client.rs#L666

This is needed to implement Shasper fork choice rule.

**Comment by rphmeier** [comment]
From @sorpaas on Riot:

>For the fork choice rule issue / backend plugins, I'm thinking about bring back global and per-block metadata.

>Allow storing global metadata extending META/Blockchain::info.
Add a per block metadata column in the database.
When BlockImport calling Client::import_block, it can pass parameters to modify global metadata and per block metadata (head and ancestry).
We may need an extra function on Client that locks the whole block import process, because consensus layer may need to fetch some data first before calling Client::import_block. Or equivalently, change Client::import_block to accept a closure that returns ImportBlock struct.
I think this interface works for total difficulty. It also works for LMD-GHOST (at least current spec) by storing the latest attestation target in global metadata, and vote count in per block metadata. After that, use tree_route to determine the value of is_new_best.

**Comment by tomaka** [comment]
The `SelectChain` trait allow customizing the chain fork choice.
Does this cover what this issue is about?

**Comment by andresilva** [comment]
This should be supported now with `ForkChoiceStrategy::Custom` and `SelectChain`.
