### ISSUE TITLE
Vested balance can be immediately used as a free balance if there are enough bonded tokens

### ISSUE THREAD

**Issue by filippoweb3** [paritytech/substrate#12555]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

If I have X bonded tokens that I am not using for anything else (no governance), if I receive a vested transfer of Y tokens where Y << X, those tokens are immediately available for transfer without waiting for the vesting schedule to complete. What happens is that some bonded tokens used for staking are getting labeled as "vested". If the vesting schedule is shorter than the unbonding period, those labeled tokens will be available after unlocking. 

This allows large token holders to potentially transfer vested tokens without waiting for the unlocking period, and still receive staking rewards without even unbonding. The sender of the vested amount probably has good reasons for keeping it a vested transfer. The receiver could use those tokens for instant selling depending on market conditions, potentially leading to price manipulation (and without having to unbond).

The issue can be viewed as leverage of the bonded tokens. Ideally, bonded tokens in staking should not be labeled as "vested".

[This issue](https://substrate.stackexchange.com/questions/5503/when-a-vested-transfer-is-sent-to-an-account-with-vested-and-staked-funds-the-r) described on the stack exchange is probably related to this.

### Steps to reproduce

1) Bonded 0.5 KSM in staking in Account A
2) Sent a vested transfer of 0.2 KSM to A from Account B

Those 0.2 KSM are immediately transferrable, while 0.2 KSM of the already bonded tokens are now labeled as "vested".

**Comment by bkchr** [comment]
I get the confusion. However, I don't think there is any bug or something as all requirements are holding. The point here being that `Locks` are not stacking and instead the lock with the highest locked value determining the amount of locked tokens. Here in your case `0.5KSM` should be locked because they are staked and `0.2KSM` should be locked as they are vested. Both requirements are still true. If you would unbound, you would get access to the other `0.3KSM`, but `0.2KSM` would still be vested. No security requirements are broken and the user also has access to all the funds they are allowed to access.

**Comment by filippoweb3** [comment]
@bkchr I see alright then it makes somehow sense. Thanks a lot for the reply!
