### ISSUE TITLE
Locked fund unable to unlock

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#12863]
https://polkadot.subscan.io/account/12Y8b4C9ar162cBgycxYgxxHG7cLVs8gre9Y5xeMjW3izqer?tab=extrinsic

This account has 240 DOT locked by democracy.

However, I cannot find any corresponding record in the democracy pallet. Polkadot.js apps also doesn't show unlock options.

I suspect there was some bad / missed migration in the past in Polkadot.

<img width="507" alt="Screenshot 2022-11-30 at 2 34 41 PM" src="https://user-images.githubusercontent.com/1201310/206139147-5a89cd66-b51e-4cc2-9eff-0f52abc66585.png">

We should also implement `try_state` for bunch pallets to assert the reserve / lock matches to the pallet internal assumption and there shouldn't be reserve/lock without matched entry in other pallet.

**Comment by jacogr** [comment]
It could very well be from the first generation of democracy - I cannot remember the exact details of that, but do know when the migration was done the old locks stayed. 

As I recall (and it honestly has been a long time since dealing with these) the `democracy.unlock(target)` extrinsic _may_ make it available again.

**Comment by xlc** [comment]
Thanks @jacogr ! You are absolutely correct that `democracy.unlock(target)` unlocks the fund.

My only remaining compliant is that there is no event emitted for the unlock. But I can live with that. https://polkadot.subscan.io/extrinsic/13250814-3
