### ISSUE TITLE
Merkle proof with unused entry

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#13357]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

When asking Substrate a call proof of `TaggedTransactionQueue_validate_transaction` in order to do a simple transfer on Westend, it sends back a Merkle proof that I think contains an unused entry. In other words, an entry in the proof that is there for no reason.

Smoldot considers proofs with unused entries as invalid.

You can find an example proof (undecoded) here: https://github.com/smol-dot/smoldot/issues/154#issuecomment-1425617192

The unused entry is the second item. In other words, if you decode the proof into a `Vec<Vec<u8>>`, then the unused entry would be `decoded[1]`.

The reason why I'm confident that the entry is unused is because its hash is `[194, 64, 98, 178, 166, 67, 204, 119, 7, 210, 16, 237, 205, 36, 201, 61, 141, 167, 156, 61, 71, 134, 57, 105, 131, 191, 68, 14, 186, 12, 75, 253]`, and this sequence of bytes isn't found anywhere in the proof.

**Comment by tomaka** [comment]
cc @cheme I guess

**Comment by tomaka** [comment]
To clarify, it's not "unused" in the sense that it contains a storage item that is not necessary for the call. It's unused in the sense that it contains a node that is completely disconnected from the other nodes of the proof.

**Comment by cheme** [comment]
I also can't seem to be able to decode this node. The size of the node is 32 byte so cannot be a detached value, and trying to decode it, it is not valid content (header is branch V1 with value, 10 nibbles, then child map show multiple child which cannot be in this 32 byte node).

Is this proof comming from a trusted source, does it happen regularily?
Could be that value of 32 byte length are added to proof due to a bug (should be inline).
I did find this node as an inline value of the node at position 5:
So this is probably it, something that add inline 32 byte node to proof as if they are detached nodes.

**Comment by cheme** [comment]
I did identify the issue, was a bug from the substrate trie crate (inline value where recorded as node value when get_hash was called).

**Comment by tomaka** [comment]
@cheme Would it be possible to open a PR with a `cargo update -p trie` so that the fix is in?

**Comment by tomaka** [comment]
Reopening because it's not fixed yet

**Comment by bkchr** [comment]
> #13284 is needed for 0.25.0, so it needs to be merge first (iirc all was fine in this PR).

The pr was merged. @tomaka do you still want to reopen this issue?

**Comment by tomaka** [comment]
No, I just wanted `is_issue_open` to be equal to `is_the_bug_fixed`
