### ISSUE TITLE
Emit generic `PeerConnected`/`PeerDisconnected` event from `sc-network`

### ISSUE THREAD

**Issue by altonen** [paritytech/substrate#13405]
Emit generic `PeerConnected`/`PeerDisconnected` event from `sc-network`, carrying the protocol name of the connection

https://github.com/paritytech/substrate/pull/12828#discussion_r1108651090

**Comment by bkchr** [comment]
I would not do this on the networking level. Because that would still mean that you need filter based on the protocol somewhere. Yeah okay, I mean this is discussable. We could have this stream from the network and then `filter_map` before we pass it somewhere else. However, we don't really need this functionality of following other protocols. So still not sure we need this on the network crate level.

**Comment by altonen** [comment]
I would like to rework the event stream system either way. Now we send every event of every protocol to every other protocol and have these `if protocol != self.protocol { continue }` checks in every event stream handler. What we could instead do is create a subscription-based mechanisms whereby protocols could subscribe to each other's events if they so desire and each protocol would obviously automatically subscribe to its own events. This would reduce unnecessary message passing in the system and would also achieve what I think you're referring to.

**Comment by altonen** [comment]
Superseded by https://github.com/paritytech/substrate/issues/13532, https://github.com/paritytech/substrate/issues/13531, and https://github.com/paritytech/substrate/issues/13554
