### ISSUE TITLE
Consider further isolation of consensus related code

### ISSUE THREAD

**Issue by davxy** [paritytech/substrate#13449]
We already have `primitive/consensus` and `client/consensus` folders to keep together consensus related code.

Currently these folders contains code for protocols related to block authoring such as BABE, AURA, PoW and some shared utility code.

I propose to add to these folders **everything** related to consensus (thus also finality) such as grandpa and beefy crates.

Even though this is not paramount, I can't see any good reason to have these crates floating with the rest of the code.
In general  I think is a good practice to logically organize the code.

If there isn't any drawback I can easily take on this trivial chore.

**Comment by abebeos** [comment]
> If there isn't any drawback I can easily take on this trivial chore.

(commenting in the role of an outside observer)

## https://github.com/paritytech/substrate/labels/I7-refactor

The question is: Can this task ("further isolation of consensus related code") be done by strict refactoring?

(**Strict Refactoring:** zero functional change)

Because even a strict refactoring can still introduce side-effects (things usually visible only in the machine-code, link long vs. short jumps etc.).

## https://github.com/paritytech/substrate/labels/Z0-trivial

Refactoring should **not** be labeled as trivial - because it is not trivial.

(Should have own label, like `Z9-The-Art-of-Code`)

**Comment by davxy** [comment]
This is mostly about renaming
