### ISSUE TITLE
Running try-runtime with try-state option doesn't fail

### ISSUE THREAD

**Issue by liamaharon** [paritytech/substrate#13837]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Using the `try-runtime` `--try-state <PALLET>` flag appears to break the try-state checks in the pallet. 

Originally reported in [this SE question](https://substrate.stackexchange.com/questions/7938/running-try-runtime-with-try-state-option-doesnt-fail).

**Comment by Szegoo** [comment]
After doing some testing myself I realized that running try-runtime with try-state option does actually fail.

When running try-state for some specific pallet we execute the following code: 
```rs
Select::Only(ref pallet_names) => {
	let try_state_fns: &[(
		&'static str,
		fn(BlockNumber, Select) -> Result<(), &'static str>,
	)] = &[for_tuples!(
		#( (<Tuple as crate::traits::PalletInfoAccess>::name(), Tuple::try_state) ),*
	)];
	let mut result = Ok(());
	for (name, try_state_fn) in try_state_fns {
		if pallet_names.iter().any(|n| n == name.as_bytes()) {
			result = result.and(try_state_fn(n.clone(), targets.clone()));
		}
	}
	result
},
```
The reason it did not fail is that the Collective pallet was not found anywhere inside `try_state_fns`, so the try-state for the Collective was never actually run.

Tbh I am not entirely sure why the Collective pallet was not found in `try_state_fns` since the kitchensink runtime does implement the pallet it three instances(CouncilCollective, TechnicalCollective, AllianceCollective).

I have opened a PR that adds a warning message in case the pallet provided to `try-state` was not found since that could save some time in the future for someone in scenarios like this. #13858

**Comment by liamaharon** [comment]
Nice catch.

To confirm, were you able to get `try-state` working when you used it with the name of an instantiated pallet like `--try-state CouncilCollective`?

**Comment by Szegoo** [comment]
> To confirm, were you able to get `try-state` working when you used it with the name of an instantiated pallet like `--try-state CouncilCollective`?

No, it did not work.

**Comment by liamaharon** [comment]
Hey @Szegoo, I wasn't able to replicate this on this branch: https://github.com/paritytech/substrate/tree/try-state-works-collective

1. `substrate --dev`
2. `cargo run --features=try-runtime try-runtime --runtime=existing follow-chain --uri ws://localhost:9944 --try-state=Council`

<img width="1184" alt="Screenshot 2023-04-14 at 12 27 14" src="https://user-images.githubusercontent.com/16665596/231988746-be02adff-e5ab-40d8-9b11-9508dd01c3f7.png">

I believe the problem was that you're trying to select the collective pallet with the wrong name, you need to use the name of the pallet as specified in the `construct_runtime!`:

<img width="596" alt="Screenshot 2023-04-14 at 12 26 08" src="https://user-images.githubusercontent.com/16665596/231988495-a5c0b607-6722-4d02-8986-e13f27257ca6.png">

Let me know if you're able to reproduce the issue using the name of the pallet as defined in `construct_runtime!` and I'll reopen this issue.

**Comment by Szegoo** [comment]
@liamaharon Yes, it was my fault. For some reason, I was testing with `CouncilCollective` 🤦.
