### ISSUE TITLE
try-runtime: execute a range of past blocks

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#13840]
An extension to the existing `execute-block` that, instead of re-executing one block, it executes a range of past blocks, as long as they are one continuous range. 

Should be tested with the new testing infra added in https://github.com/paritytech/substrate/pull/13794.

**Comment by PieWol** [comment]
Hey, I would really like to work on this issue but my experience in try-runtime is absolutely zero. This looks like you want a new fn in the `impl frame_try_runtime::TryRuntime<Block> for Runtime` Block that takes a range of blocks as an argument instead of the single block as execute_block does. Is that correct? So it would be a simple wrapper function using the already existing `execute_block` fn I'll just try to figure out a correct way to implement that function so it is available via the cli. Regarding the continous range, does it mean the new fn should check for the user that every block is in the correct order so a failure would be detectable before the actual execution?

**Comment by cheme** [comment]
This would probably require https://github.com/paritytech/substrate/issues/14150 (I did multiple runtime run (hacky change of onruntime upgrade in https://github.com/cheme/substrate/tree/try-runtime-mig and got add to patch with a memory-db that do not remove content in order to get some data).
(actually this branch could be use to simulate running multiple block on_init (which I needed to get input for state-trie-migration)

**Comment by cheme** [comment]
actually this is not directly related to the issue (I was thinking multiple block execution, but here it is pas block), I am removing my comment thus.

**Comment by liamaharon** [comment]
Moved to https://github.com/paritytech/try-runtime-cli/issues/11
