### ISSUE TITLE
[meta] `try-runtime-cli` `fast-forward` 

### ISSUE THREAD

**Issue by liamaharon** [paritytech/substrate#13887]
Partial https://github.com/paritytech/substrate/issues/14031

High-ish priority improvements to get `fast-forward` into a healthy state

- [ ] Support arbitrary inherents required by the runtime. ideas:
    - ~allow configuration of inherents using cli args (probably simplest, but least flexible and bad developer UX)~
    - ~when try-runtime feature is enabled, add a special runtime api (or some other method) to expose some information about which basic inherents are expected by the runtime. this way, fast-forward can query that api when it boots up and know which inherents it needs to apply in its otherwise empty blocks (more complex but would support any runtime, seems like a good option if it's possible)~
    - How I am going to approach solving this in the new [try-runtime-cli repo](https://github.com/paritytech/try-runtime-cli):
        - Create a file `inherents_configurations.rs` containing inherent configurations similar to https://github.com/paritytech/substrate/blob/master/utils/frame/try-runtime/cli/src/block_building_info.rs
        - When a command like `fast-forward` that requires inherents is used, the CLI will attempt to build blocks using each of these inherent options until it finds one that works
        - If it finds one that works, it will memoize it for the rest of the run
        - If it cannot find one that works it exits with a helpful message to the user linking to documentation explaining how to add their inherent configuration to `inherents_configurations.rs`
- [ ] Needs documentation

**Comment by ggwpez** [comment]
>when try-runtime feature is enabled, add a special runtime api (or some other method) to expose some information about which basic inherents are expected by the runtime. 

Isnt this exactly what the `BlockBuilder` does?

In general just building a generic block in substrate is rather difficult IMHO.  
I dont think a config TOML file will work, rather it needs some code injected that provides the inherents. Note that inherents can depend on the block number. In the benchmarking this is solved by using the `BlockBuilderProvider` from the [`client`](https://github.com/paritytech/polkadot/blob/7d61927f3e7ed771c071b1e59ae2a56be16b789b/cli/src/command.rs#L554) itself.  
It is slightly hacky, but 10x easier than trying to rebuild it. Not sure if you can use that though, since the try-runtime CLI is independent of the node.  

So it will probably need some custom code integration for the `fast-forward` command for each chain that wants to support it, that provides the inherent data.    
Tagging @bkchr, since maybe i am over complicating something.

**Comment by liamaharon** [comment]
> I dont think a config TOML file will work, rather it needs some code injected that provides the inherents.

Yeah, when I say config here I am referring to a file containing injected code for different para/relaychains, like the custom code integration you described.

> Isnt this exactly what the BlockBuilder does?

I'll take a look at this, thanks.

> Note that inherents can depend on the block number. In the benchmarking this is solved by using the BlockBuilderProvider from the [client](https://github.com/paritytech/polkadot/blob/7d61927f3e7ed771c071b1e59ae2a56be16b789b/cli/src/command.rs#L554) itself.

I wasn't aware of this, thanks.

**Comment by ggwpez** [comment]
Yea I think the [`BlockBuilderProvider`](https://github.com/paritytech/substrate/blob/b1b4b434f9769cf32a4a6ad6cbea3b9dfe6074ef/client/block-builder/src/lib.rs#L119) trait has the right abstraction (since it can account for the block-number).  
So that would have to be injected. But please double-check this with someone from the SDK node team. I am not that proficient with the process myself.

**Comment by bkchr** [comment]
> So it will probably need some custom code integration for the `fast-forward` command for each chain that wants to support it, that provides the inherent data.

Yeah sounds correct to me and there not being any more easier way for this.

**Comment by liamaharon** [comment]
How I am going to approach solving this in the new [try-runtime-cli repo](https://github.com/paritytech/try-runtime-cli):
  - Create a file `inherents_configurations.rs` containing inherent configurations similar to https://github.com/paritytech/substrate/blob/master/utils/frame/try-runtime/cli/src/block_building_info.rs
  - When a command like `fast-forward` that requires inherents is used, the CLI will attempt to build blocks using each of these inherent options until it finds one that works
  - If it finds one that works, it will memoize it for the rest of the run
  - If it cannot find one that works it exits with a helpful message to the user linking to documentation explaining how to add their inherent configuration to `inherents_configurations.rs`

**Comment by liamaharon** [comment]
Moved to https://github.com/paritytech/try-runtime-cli/issues/12
