### ISSUE TITLE
Increase staking pallet version after #14039

### ISSUE THREAD

**Issue by fgamundi** [paritytech/substrate#14385]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

PR #14039 introduced breaking changes to the staking pallet, but the pallet version was not increased to reflect it.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/staking-controller-deprecation-plan-staking-ui-leads-comms/2748/25

**Comment by bkchr** [comment]
CC @rossbulat

**Comment by rossbulat** [comment]
From what I understand we will be bumping staking pallet versions  as the `STORAGE_VERSION` changes, which is subject to new migrations on chain state. The 0.9.43 runtime has been cut off now so if we were to bump the version it'll be the next. The idea of a "silent migration" has been discussed, in order to bump storage & pallet version, but I don't think this will go ahead.
