### ISSUE TITLE
Refactor timestamp.period to become double its value and called .expected_period

### ISSUE THREAD

**Issue by webmaster128** [paritytech/substrate#1493]
In Substrate 0.9 and 0.10 (0.10.0-78bb4c0) blocks are produced every 40 seconds when the genesis.runtime.timestamp.period is set to 20. Is this intended?

See "TSP antnet" in https://telemetry.polkadot.io/#/TSP%20antnet using the chainspec from https://github.com/webmaster128/tsp-networks/tree/master/chainspecs

**Comment by rphmeier** [comment]
The `timestamp.period` member is the minimum block period. In Aura we want to make sure that each slot author has the maximum possible time to author their block. Since the author of slot A can release at the very end of their slot, to make sure the author of slot A+1 has at least half of their slot to make a block, we have to make the expected block time double the `timestamp.period` in order to prevent a force-skip.

I'm open to any API alterations that make this more ergonomic; I agree the usage is not obvious right now, but there is not a clear alternative that is also correct.

**Comment by webmaster128** [comment]
Thanks @rphmeier. I think _expected block time_ perfectly describes the user's expectation. This is what I'd like to specify in the config and the underlying engine can split that time frame into whatever period it needs.
