### ISSUE TITLE
Bandwidth usage is ludicrously high

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#1645]
Full nodes on Alexander are reporting 1-3MiB/s regularly. This should be more in the range of 25-100Kib/s

**Comment by gavofyork** [comment]
Where did the 100KB/s figure some from? I would say that's still way too much for a network of 30-50 peers with no transactions and just one empty block every 6 seconds.

**Comment by gavofyork** [comment]
Bandwidth is still super high, even outgoing data on recent builds.

**Comment by rphmeier** [comment]
> Where did the 100KB/s figure some from? I would say that's still way too much for a network of 30-50 peers with no transactions and just one empty block every 6 seconds.

Factoring in serving syncing nodes it is the upper end of my estimate. Typically 30-50 with transactions would be expected

**Comment by gavofyork** [comment]
Right, and without transactions, as we are now, should be way less.

**Comment by tomaka** [comment]
This is caused by duplicate node addresses in Kademlia. We receive huge Kademlia messages containing the same node address repeated thousands of times.
https://github.com/libp2p/rust-libp2p/pull/906 fixed the problem already, and #1634 will bring the fix into Substrate's code base.

In order to prevent DoS attacks, there is a limit to the size of packets that we accept. However it is of 128MiB by default, because the Substrate protocol sometimes sends huge packets.
I will also open a PR in libp2p to limit to 4kiB the size of Kademlia packets, however I would recommend not deploying it immediately to Polkadot because we would then refuse legitimate packets.

**Comment by tomaka** [comment]
After #906, and before closing this issue, let's modify the discovery test to check whether the bandwidth during the test is under a certain threshold.

**Comment by tomaka** [comment]
> [libp2p/rust-libp2p#906](https://github.com/libp2p/rust-libp2p/pull/906) fixed the problem already, and #1634 will bring the fix into Substrate's code base.

This is actually not correct.
https://github.com/libp2p/rust-libp2p/pull/906 fixed a problem introduced when we branched libp2p 0.3. The bug that https://github.com/libp2p/rust-libp2p/pull/906 fixes is therefore not in Substrate yet.

Instead I think the problem is that we don't check for duplicates here: https://github.com/paritytech/substrate/blob/64cde6f9bb2fab6e8f6c0d6f29a1f4c14851d9ed/core/network-libp2p/src/topology.rs#L152
This piece of code is removed by #1634 as the logic of external addresses has been moved within libp2p.

**Comment by gavofyork** [comment]
Looks to be fixed with latest PRs.

**Comment by tomaka** [comment]
Note that the reason why we had large packets is fixed, but we still need to upgrade Polkadot to `libp2p-kad` in order to refuse large packets.

I didn't do this all at once as that could have caused a netsplit.
