### ISSUE TITLE
Method not found when calling chain_getRuntimeVersion

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#1683]
`chain_getRuntimeVersion` no longer exists, possibly related to #1679 

```
curl -H 'Content-Type: application/json' -d '{ "jsonrpc": "2.0", "method":"chain_getRuntimeVersion", "params":[], "id": 1 }' http://localhost:9933/
{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":1}
```

@jacogr Maybe should fix it on polkadot.js side to use `state_getRuntimeVersion` and remove `chain_getRuntimeVersion`? but `state.getRuntimeVersion` is missing anyway

**Comment by jacogr** [comment]
Ok, this is problematic. Since the APIs needs to support both old and new chains and this is not detectable without a call. (If moved and not just deprecated with new version)

If this was a move of endpoints, will look at it a bit later to try and find a solution for this ASAP since we seem to have broken apps out there.

**Comment by ascjones** [comment]
Probably a bug in `jsonrpc-derive`. Investigating.

**Comment by jacogr** [comment]
@ascjones Tested, does the trick for me on latest master, thank you.
