### ISSUE TITLE
Better support of StorageDoubleMap

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#1715]
It will be good if `decl_storage` macro have support of [StorageDoubleMap](https://github.com/paritytech/substrate/blob/master/srml/support/src/double_map.rs) so fields with double map format can be exposed in metadata

**Comment by thiolliere** [comment]
I can work on that if it is wanted. Also StorageDoubleMap doesn't seem optimal: on contrary of StorageMap that use Borrow<Key> as an argument for get and etc... StorageDoubleMap use Key directly.

Also this would avoid some clone like in substratekitties https://shawntabrizi.github.io/substrate-collectables-workshop/#/3/transferring-a-kitty line 125

**Comment by thiolliere** [comment]
OK I'm not sure about the way to go here, these are my current thought on it:

#### Current state:
* `StorageDoubleMap` is used by contract, for specific reason it uses `blake2_256` instead of `twox_128` for the second key.
* All `StorageThing` generated with `decl_storage!` are using twox_128 hasher.
* `StorageDoubleMap` is implemented in support but modules could implement their own storage using get/put/take/kill... exposed functions of `support::storage` and `support::storage::unhashed`

#### What could be done
I don't know about how much metadata is required.
* If we expect some user to implement their own storage. And if metadata is required then we should provide user ways to implement metadata on it (maybe some helping macro also). And implement metadata in contract.
* If we expect some user to implement their own storage but metadata is not required, (it is just easier for UI to interact with ?) then we could implement metadata in contract for our own usage.
* We can implement a double map (the most interesting feature is to be able to remove everything with the first key (`remove_prefix` method)) that uses twox_128 for both keys as other storage in `decl_storage!` but that won't help for `srml-contract`
* We may want to generalize `decl_storage!` to be able to specify hasher optionally. But that won't help for user defined storages, but at this point they may master enough to implement their own metadata

I would go for generalization of `decl_storage!` but also keep in mind that some user will implement their own storage isn't it ? in this case I don't know how metadata fits.

**Comment by xlc** [comment]
A generalized `decl_storage!` will be very helpful. At least for me I can't think any reason to define my own storages other than the use case of DoubleMap (multi asset module where free balance keys have common prefix which is the hash of the asset id). I can think some possible use cases to use multiple level nested map, but it will just be a more generalized double map.

**Comment by thiolliere** [comment]
But is the choice of the hasher something very useful ?
I mean implementing a DoubleMap with twox_128 hasher could be quite straightforward.
Generalize Hasher seems doable but would require more works and could be made in a second time.

**Comment by thiolliere** [comment]
OK, blake2 was used because second key of the DoubleMap comes from untrusted source, and a malicious one could craft keys specifically to make trie less efficient.

I don't know yet how to think about those vulnerabilities but it seems build a storage like DoubleMap does `key=hash(prefix+key1) hash(key2)` can bring some other features like being able to iterate on elements of the map with just a `for_key_with_prefix` (this method is not exposed in the storage but clear_prefix is and requires some kind of this method). And this would be probably more efficient than our actual ListedMap.

**Comment by xlc** [comment]
Still needs https://github.com/polkadot-js/api/issues/776
Substrate side closed by #1918
