### ISSUE TITLE
Fix tests that randomly hang

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#1777]
One offender:
```
test many_nodes_connectivity ... test many_nodes_connectivity has been running for over 60 seconds
ERROR: Job failed: execution took longer than 1h0m0s seconds
```

**Comment by tomaka** [comment]
Some update on this: it turns out that [the test in rust-libp2p that makes sure that simultaneous connections work](https://github.com/libp2p/rust-libp2p/blob/6cb2c71ca3f3dc7e3e9581414787635ba2037941/core/tests/raw_swarm_simult.rs) has a bug (we only apply the muxer as an outbound upgrade).
Fixing the bugs makes the test fail.

It is probable that fixing this test will fix this issue as well.

**Comment by gavofyork** [comment]
@tomaka is this sorted now?

**Comment by tomaka** [comment]
No, and #1891 somehow makes it worse.
I'm actively working on that now. #1870 should greatly help.

**Comment by svyatonik** [comment]
@tomaka I've tried today's master (https://github.com/paritytech/substrate/commit/1408efdb2e65bc481af67d3178ab1a398245b5bf) and now I'm hitting this on every run:
```
running 1 test
test chain_spec::tests::test_connectivity ... test chain_spec::tests::test_connectivity has been running for over 60 seconds
```
I have run it 7 times in a row && every time I keep getting this error => looks like it isn't spurious anymore. Seems like the test eventually completes on CI (https://gitlab.parity.io/parity/substrate/-/jobs/132205), though CI also hit 60-seconds timeout.

Just in case it could help, here's [the trace](https://gist.github.com/svyatonik/1274f406647394419e79a04b8d85625f) of this test (collected with `reset && RUST_LOG=sub-libp2p=trace,network=trace,sync=trace cargo test -p node-cli --release -- test_connectivity`)

**Comment by svyatonik** [comment]
Oh, sorry! @arkpar has pointed me to #2073, so just ignore my comment :)
