### ISSUE TITLE
Slash for previous eras

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#1810]
Currently we can only slash stakers at the current block (using the `Stakers` storage item). We should be able to slash a validator (controller) account at a previous block number which would fall into a previous era. To do this we'll need to store a digest of the `Stakers` contents when the era ends in `HistoricalStakers`. It would be .good to use a Merkle tree to do this rather than a straight hash so that the information concerning a specific validator can be provided and verified. In addition, full/fishermen nodes should store the preimage data in a local database.

A node that is issuing the punishment transaction will need to be able to reconstruct this from the local database (assuming it exists - worst case they'll need to manually create it from an archive node's state) and present the relevant data as witness with the transaction that initiates punishment.

It will be checked against the hash stored in `HistoricalStakers` to ensure that the witness is correct for the era in question and then acted upon accordingly (by slashing the validator and their nominators).

Since this has offline components, particularly the need to store of historical eras, it'll be dependent to a large degree on https://github.com/paritytech/substrate/issues/1458 

- [ ] Determine Merkle trie root of current `Stakers` contents and maintain `HistoricalStakers`.
- [ ] Introduce off-line component that places `Stakers` contents into local database at end of era.
- [ ] Introduce witness-verification function that verifies a historical `Stakers` key/value corresponds truthfully to the (known) historical trie root.
- [ ] Introduce final `historical_slash(era: T::BlockNumber, who: T::AccountId, exposure: Exposure<T::AccountId, BalanceOf<T>)` function.

**Comment by rphmeier** [comment]
We will also want to keep old random seeds so we can slash based on pseudo-random manipulations of the staking set.

**Comment by rphmeier** [comment]
As an MVP:
  - Session stores a `LastSessionMerkleCommitment: Hash` which is the merkle root of an ordered trie formed from the last session's keys. This is updated on session rotation.
  - Every session gets a sequence number.
  - `enum Inclusion { Current(SequenceNum, SessionKey), Prior(SequenceNum, MerkleProof) }`
  -  `fn session::check_inclusion(Inclusion) -> Option<AccountId>` (`AccountId` so we know who to slash).

Nodes submit misbehavior reports (typically UnsignedTransaction) as they sync. Since they are syncing, state is available and they know the `authorities` set and sequence number and can prove inclusion. Also since they are syncing, they don't necessarily know if the `authorities` set they're using is current. They can opt to use `Inclusion::Prior` unless they have a high degree of confidence that the report is recent.
