### ISSUE TITLE
(consensus & grandpa module) SessionKey is inconsistent

### ISSUE THREAD

**Issue by gguoss** [paritytech/substrate#1840]
https://github.com/paritytech/substrate/blob/f8b0e7db4bb5d64e68752435e424814f607a0f82/node/runtime/src/lib.rs#L117
https://github.com/paritytech/substrate/blob/f8b0e7db4bb5d64e68752435e424814f607a0f82/node/runtime/src/lib.rs#L190

If you need to be consistent, delete grandpa directly, grandpa trait inherits from consensus。
Conversely, grandpa's sessionkey can only be converted from account_id , not set_authority

**Comment by rphmeier** [comment]
Why should it be consistent?

**Comment by gguoss** [comment]
- if not consistent: 
There are some bug:  
  bug 1: grandpa's session key  can't set. but  (aura)consensus's session key can set. 
  bug 2: grandpa and aura  session key are fetch from session modules' validator. these is consistent. 
- if consistent: 
There are a bug:  SessionKey not consistent, As I said above.

**Comment by rphmeier** [comment]
Don't know what you mean. The authority sets are separate but can be synchronized via `SyncedAuthorities` based on the start of each session.

But if they are not synced then they should be allowed to use different key types, and this is something that makes a lot of sense because there are voting optimizations that you can implement for e.g. BLS signatures.

**Comment by gguoss** [comment]
That is to say, consistent or non-consistent, by the implementer to customize the implementation
