### ISSUE TITLE
Why p2p not use Ed25519?

### ISSUE THREAD

**Issue by gguoss** [paritytech/substrate#1953]
https://github.com/paritytech/substrate/blob/c4ca27f7121f37172ae0d2d92280a947ca77edd8/core/network-libp2p/src/secret.rs#L41

Will p2p use Ed25519 or Sr25519?

**Comment by bkchr** [comment]
CC @tomaka

**Comment by tomaka** [comment]
Yes, we want to use ed25519. See #1494. 
I'm going to close as duplicate.

**Comment by burdges** [comment]
There is no advantage to using Sr25519 at the transport layer, especially since our "session keys" already contain several key types.  There are reasons to avoid using secp256k1 at the transport layer though.  So yes we'll use Ed25519 down there.

Sr25519 exists primarily to provide (1) a more unified presentation of features expected and [saught](https://github.com/sipa/bips/blob/bip-schnorr/bip-schnorr.mediawiki) from account keys, along with (2) the improved strength of Edwards curves, and (3) improved forward compatibly with more complex protocols, including zero knowledge proofs starting with VRFs.  None of this sounds too relevant to authenticating connections.
