### ISSUE TITLE
balances module issues

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#1962]
`ensure_account_can_withdraw` should be in `TransferAsset` trait, so the user of `TransferAsset` is able to check before calling `transfer`/`withdraw`

`_amount: T::Balance` should be removed from `ensure_account_can_withdraw`
https://github.com/paritytech/substrate/pull/1921/files#r264076663

`make_transfer` should call `Self::ensure_account_can_withdraw(transactor, fee, WithdrawReason::TransactionPayment, new_from_balance)?`
https://github.com/paritytech/substrate/pull/1921/files#r264077649

**Comment by thiolliere** [comment]
indeed it seems TransferAsset should be extended to include checks, (and I would also include can_transfer as a wrapper around can withdraw)

I agree on _amount removal,

> `make_transfer` should call `Self::ensure_account_can_withdraw(transactor, fee, 
> WithdrawReason::TransactionPayment, new_from_balance)?`
> https://github.com/paritytech/substrate/pull/1921/files#r264077649
Interesting it seems true to me, also maybe we should write ensure_account_can_withdraw having a WithdrawReasons instead of a WithdrawReason.

(Also there can be Transfer without TransactionsPayment isn't it ? otherwise TransactionsPayment is just a subset of Transfer and this could be checked automatically.)

**Comment by xlc** [comment]
Yes please support transfer without `TransactionsPayment`. It may not be needed in substrate itself but definitely useful for parachains.

**Comment by thiolliere** [comment]
removal of _amount [here](https://github.com/paritytech/substrate/pull/1998)

**Comment by xlc** [comment]
Fixed by #2048 and #1998
