### ISSUE TITLE
Do not panic in telemetry drop without special handling

### ISSUE THREAD

**Issue by bkchr** [paritytech/substrate#1973]
Everyone needs to copy the following piece of code into their node when using our telemetry: https://github.com/paritytech/substrate/blob/c8212c43724258d270ea578ba62882705fabde56/node/cli/src/lib.rs#L129

We should not force users to copy this piece of code and instead fix telemetry.

**Comment by andresilva** [comment]
IIRC this is because telemetry is using `slog-scope`  to set a global logger, but it only works if the `GlobalLoggerGuard` that's returned here https://github.com/paritytech/substrate/blob/master/core/telemetry/src/lib.rs#L97 isn't dropped.

I don't know if it's possible, but maybe we could check here https://github.com/paritytech/substrate/blob/master/core/telemetry/src/lib.rs#L166 whether there's any global logger set (instead of panicking).

**Comment by bkchr** [comment]
CC @maciejhirsz maybe you have an clear overview what is happening and how this can be fixed :)

**Comment by tomaka** [comment]
Since we're setting a slog logger that is global to the program, we should in my opinion make that clear and obvious.

There are two ways to fix that:

- Not set a global logger but a local one instead. This could easily be done after #2536.
- Somehow split the telemetry from the service and let the user call `init_telemetry` themselves, similar to the way we do with the informant.
