### ISSUE TITLE
Fix wasm module reuse

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/substrate#2051]
CC: @pepyakin 

Seems that the original cause for #2022 is somewhere in wasm module re-use.

```
diff --git a/core/executor/src/native_executor.rs b/core/executor/src/native_executor.rs
index 0944cbdb..f0793af3 100644
--- a/core/executor/src/native_executor.rs
+++ b/core/executor/src/native_executor.rs
@@ -58,6 +58,7 @@ fn fetch_cached_runtime_version<'a, E: Externalities<Blake2Hasher>>(
                Some(code_hash) => code_hash,
                None => return Err(ErrorKind::InvalidCode(vec![]).into()),
        };
+       cache.borrow_mut().remove(&code_hash[..]);
        let maybe_runtime_preproc = cache.borrow_mut().entry(code_hash.into())
                .or_insert_with(|| {
                        let code = match ext.storage(well_known_keys::CODE) {

```

This change causes the issue to disappear.

See branch https://github.com/paritytech/substrate/tree/td-debugging it's forked off from the #1800 that introduced `spin::Once`, but contains all the fixes that allow to reproduce currently using deployed version of https://polkadot.js.org/apps

Note that last commit is the patch above, so revert if you want to reproduce the issue:
1. Send one transaction from any account
2. Send 1-2 more transactions form the same account, they will fail with `InvalidTransaction`

**Comment by tomusdrw** [comment]
Potential culprit: #1345

**Comment by gguoss** [comment]
Good,  waiting fix

**Comment by gguoss** [comment]
> Potential culprit: #1345

Before c4ca27f7121f37172ae0d2d92280a947ca77edd8 is ok,  Our branch from this commit fork is good, and there is a problem with a commit after this.

Although this code **cache.borrow_mut().remove(&code_hash[..]); ** is added, this problem is solved -- （in the wasm state, runtime-api cannot be called）, but the performance of the chain is fatal.

**Comment by pepyakin** [comment]
Note that this line is rather just a hint that the problem might be coming from the memory reusing mechanism. This line effectively disables it.

It is **not** a proper fix.

**Comment by gavofyork** [comment]
@pepyakin @tomusdrw is this something that can reasonably be fixed in the next 48 hours?

**Comment by arkpar** [comment]
As far as I understand the issue is that lazy statics are not working in the runtime properly because of the memory snapshot that is taken after `start`. Current runtime does not use lazy statics anymore, so it is not that critical.

**Comment by gavofyork** [comment]
right. where were they used?

**Comment by arkpar** [comment]
@gavofyork: To cache storage key prefixes it seems
https://github.com/paritytech/substrate/pull/2046/files#diff-96407ba21acc3f08629ab01006199ba8L484

**Comment by pepyakin** [comment]
Ok it seems that I've found the issue.

It is not related to the `.bss` "section" as I've imagined initially, but similar. It is related to the .data "section". 

As a recap, we are trying to reuse the memory in the following manner: we initialize the wasm instance only once, i.e. copy . On each call, we remember the lowest address touched after the instantiation and assume that this address is the start of the volatile part of the memory. After the call is finished we (effectively) zero the memory starting from the remembered address.

This strategy worked until we used mutable statics. Mutable statics are placed into the .data "section" by the current rustc/LLD and are initialized at the instantiation time. Thus, they end up behind the volatile cut off line and not being zeroed. However, they are also wasn't restored to their original values.

I've pushed the proof of concept in the `td-debugging2` branch at https://github.com/paritytech/substrate/commit/3d7b27f3421818e8d6de568e02fbc2947a06246b. It declares a mutable static variable and declares a function, which increments the variable and returns it.
The test expects to call this function twice and get the same result.

The runtime should be safe as long as the compiler doesn't put anything mutable that is not worth preserving. But this means we should keep an eye on the way that rustc/LLD produces binaries and that our wasm binaries don't use static mutables for important data. This also means we should be more careful with dependencies. This is possible, but very burdensome.

If you ask me, I'd go for more conservative optimizations, e.g. a pool of instances that is replenished from a background thread or CoW virtual memory tricks.

**Comment by pepyakin** [comment]
Ah and also the stack pointer and the stack itself are located behind the volatile cutoff address, however, the stack is temporary and the stack pointer is expected to always return to the same value.

well, in theory each wasm runtime panic could hog some stack space and eventualy every call will lead to the stack overflow on each usage of the stack. 

However, I think if the runtime panics we already have a problem, I guess. And this is not a network wide, if you restart a node it will start with the fresh stack.

But definitely makes me anxious, since my analysis might be limited. So ^^ might be worth noting.

**Comment by gavofyork** [comment]
We certainly need to be more careful with dependencies. Unfortunately it's really difficult to diagnose which dependencies are actually going into wasm. Any hints for tools that could help there would be appreciated.

Otherwise, let's make sure we knock this on the head for 1.1.

**Comment by DemiMarie-parity** [comment]
@pepyakin I think we should use COW mappings.  Unix-like systems support this natively via `mmap` and `MAP_PRIVATE`.

**Comment by pepyakin** [comment]
True. However, I was more inclined to think that an instance pool is better to start with since it doesn't require any special features from the wasm VM and seems to be easier to implement in a portable manner. Especially if you consider that it is not yet clear which VM we will end up with.

**Comment by gguoss** [comment]
I tested this commit (e748c33c8ef40bd51dc122b7f11fcf26b8354957) and it seems that this bug has been fixed.

**Comment by pepyakin** [comment]
This issue is about incorrect handling of mutable global variables which is caused by module caching mechanism. The issue is known to cause #2022 which is fixed by now by avoiding usage of  mutable global variables. To my knowledge, nothing has been done on this issue.

The easiest way to reproduce this issue would be to declare a mutable global variable with some initial value, on some runtime entrypoint assert that the value of the global variable is equal to the initial value, then change the global variable. On next call the value is expected to be equal to the initial value, however, due to this bug the value will stay since from the last call.
