### ISSUE TITLE
BABE implementation Phase 1

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#2084]
###  BABE Implementation

https://github.com/w3f/research/blob/master/docs/polkadot/BABE/Babe.md

The BABE implementation is similar to Aura, but uses a VRF for selecting slots instead of a round-robin. The VRF is meant to be computed on the slot number and some global, per-epoch, collaborative randomness. In the first phase of implementation, we will not use the randomness. We will use the Schnorrkel VRF and sr25519 signatures.

For now, we can define the BABE seal signature type as `BabeSealSignature { public_key, vrf_proof, signature }`

**BABE block signing process:**
  - 1. sign `(epoch_randomness, slot_number)` with VRF and stop if it is not below threshold. This produces a proof if it does.
  - 2. propose a block (we'll call the header after this step `pre_header`)
  - 3. add a `DigestItem::Seal(slot_number, BabeSignature {public_key, vrf_proof, signature }))` to the proposed header. The signature should be a regular `schnorrkel` signature on some message incorporating `pre_header`,`slot_number`,`vrf_proof`. One example would be `(pre_header.hash(), slot_number, vrf_proof).encode()`.
  

**BABE block verification process (similar to Aura)**
1. check that the last digest item is a `DigestItem::Consensus([b'B', b'A', b'B', b'E'], msg)`, where `msg` decodes to a `(slot_number, BabeSignature)`
2. check that the public key is actually an authority
3. check the VRF proof. discard if bad
4. check the full signature on the header via the same process as used for signing.
5. the rest will be similar to Aura

**Comment by zmanian** [comment]
Just an FYI, a Boneh Lynn Shacham signature is also a VRF. If substrate is planning to use BLS12-381 public keys as consensus keys in GRANDPA. You can use the same key as your VRF key for BABE.

**Comment by burdges** [comment]
We know, and I put [Ouroboros-style VRF output methods](https://github.com/w3f/bls/blob/master/src/single.rs#L626) into our BLS crate, but the schnorrkel VRF seems preferable here..

In the VRF use case, there are cofactor concerns which look secure, due to how Michele Orru handled hashing-to-the-curve in BLS12-381, but makes hashing-to-the-curve slow.  I would ideally dig more into exactly how the miller function and pairing behave outside the prime order subgroup too, just for my own peace of mind before using BLS as a VRF. 

I actually favor sampling block production delays from a Poisson distribution seeded by the VRF, not checking each slot number.  At present, we check each slot number though, so [`schnorrkel::Keypair::vrf_check_n_sign`](https://github.com/w3f/schnorrkel/blob/master/src/vrf.rs#L648) is a much faster VRF than BLS.

We want small block producers eventually, and originally designed for them, in which case we gain nothing from BLS aggregation for VRF use case.  We'd gain if we want non-winner proofs, but we achieve that better by sampling block production delays from a Poisson distribution seeded by the VRF.  I added sound batch signing and batch verification tooling to the schnorrkel VRF for the non-winner proof case already.

**Comment by zmanian** [comment]
Those reasons sounds sensible!

**Comment by DemiMarie-parity** [comment]
This has long been complete.
