### ISSUE TITLE
Review flaky grandpa tests

### ISSUE THREAD

**Issue by andresilva** [paritytech/substrate#2121]
```
---- tests::finalize_3_voters_no_observers stdout ----
thread 'tests::finalize_3_voters_no_observers' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `20`: Peer #1 failed to sync', core/finality-grandpa/src/tests.rs:481:3
```

I think this is related to the refactoring of sync code to use channels, which also refactored the testnet.

**Comment by andresilva** [comment]
https://gitlab.parity.io/parity/substrate/-/jobs/133841

**Comment by gterzian** [comment]
Ok, I'll take a look

**Comment by gterzian** [comment]
Ok so the actual test failure was because `net.sync()` returned before the peers had actually finished syncing, which made [this assertion](https://github.com/paritytech/substrate/blob/c767d102545b8507ced4331df89bf5c2640bfb1e/core/finality-grandpa/src/tests.rs#L478) failed. 

`net.sync()` essentially keeps running for as long as messages are being routed between peers, which indeed also includes a potential source of flakiness in terms of determining when peers have indeed finished syncing, which is implemented in the form of https://github.com/paritytech/substrate/blob/c767d102545b8507ced4331df89bf5c2640bfb1e/core/network/src/test/mod.rs#L714

So for example if I reduce the value necessary for the syncing to be "done", I get some flakiness with tests failing, and they fail at different points in the syncing process. For example the below is from two different test runs with a low `done` value:

```
thread 'tests::finalize_3_voters_no_observers' panicked at 'assertion failed: `(left == right)`
  left: `5`,
 right: `20`: Peer #2 failed to sync', core/finality-grandpa/src/tests.rs:481:3
```
```
---- tests::finalize_3_voters_no_observers stdout ----
thread 'tests::finalize_3_voters_no_observers' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `20`: Peer #2 failed to sync', core/finality-grandpa/src/tests.rs:481:3
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

So indeed, the `net.sync()` is potentially flaky, and you can certainly make it very flaky by setting the `done` value to 0. However, in practice, we set it to 3 and the results seem pretty good. 

What's interesting in the failure at https://gitlab.parity.io/parity/substrate/-/jobs/133841 is that 5 tests all failed with `left: 0,` and `Peer #1 failed to sync`, which indicates that the peers didn't sync at all, as opposed to `net.sync()` being flaky and returning while syncing isn't finished. 

To reproduce the `left: 0,` and `Peer #1 failed to sync` type of errors reliably on every test-run, one has to break the sync process entirely, for example by removing the call to `self.import_queue.import_blocks(origin, new_blocks);` in `ChainSync.on_block_data`, or by making `net.sync()` return immediately without routing any messages. 

So I haven't found the reason for those failures, and I am inclined to rule-out the flakiness of `net.sync()` as a reason, because I think that would require the test to fail with different values for `left: 0`, and since all 5 tests failed on peer 1 and with 0 blocks synced, I suspect the failure related to a problem inside sync itself, to be determined. 

Any ideas?
