### ISSUE TITLE
Can vector be used in smart contract code? 

### ISSUE THREAD

**Issue by deeper-zjin** [paritytech/substrate#2319]
Hi,

I did some research on the smart contract example from https://github.com/pepyakin/substrate-contracts-adder.
This demo code cannot be deployed in substrate because it imports a non-existent function. By translating the wasm binary generated through this code to wat format, I found "(import "env" "llvm.wasm.grow.memory.i32" (func $env.llvm.wasm.grow.memory.i32 (type $t1)))" caused this issue. As far as I can see, this import declaration is related to the use of vector. 

So here comes my question: Can vector really be used in smart contract code?

Thanks.

**Comment by bkchr** [comment]
CC @pepyakin

**Comment by pepyakin** [comment]
Hello @deeper-zjin !

I am afraid the substrate-contracts-adder is a bit outdated. The problem you are seeing is `adder` uses old version of `wee_alloc` and apeears that you use newer version of nightly, where intrinsics to access `memory.grow` instructions has changed. In newer version of wee_alloc this problem should be resolved. This issue is not exclusively related to `Vec`, you will see it when you use allocator.

I also want to recommend you to check out [pdsl], `examples` in particular. I also would recommend to subscribe to #1607 to see when the smart contract tutorial is out.

[pdsl]: https://github.com/Robbepop/pdsl
