### ISSUE TITLE
syn 0.15.32 breaks srml-support-procedural

### ISSUE THREAD

**Issue by ascjones** [paritytech/substrate#2326]
The recent release (0.15.32) of syn [removed](https://github.com/dtolnay/syn/commit/173a81769a3f1831d02e9aa477783d8305a508eb#diff-25d902c24283ab8cfbac54dfa101ad31) the `CustomKeyword` trait which we are using [here](https://github.com/paritytech/substrate/blob/82744fbb6f4d677f2edfe9d88737c237622c97a4/srml/support/procedural/tools/src/syn_ext.rs#L26).

That trait is behind the `parsing` feature and not part of the public API, hence the "breaking" change in the patch version.

So we need to either update to use the new `CustomToken` trait, or investigate if it's possible to decouple from that internal trait.

As a short term fix we could restrict the version of syn to `< 0.15.32`.

**Comment by xlc** [comment]
I am getting this error and a quick search `syn = ` in the project reveals there are other three references to sync and #2327 is not enough.

https://github.com/paritytech/substrate/blob/de68b7138bf9e140167efdcf7600b9c717676cdf/core/sr-api-macros/Cargo.toml#L12

(Those two are fine because it pin to exact version, but why the inconsistency?)
https://github.com/paritytech/substrate/blob/master/srml/support/procedural/tools/Cargo.toml#L11
https://github.com/paritytech/substrate/blob/de68b7138bf9e140167efdcf7600b9c717676cdf/srml/support/procedural/tools/derive/Cargo.toml#L13

**Comment by bkchr** [comment]
I just used `cargo update` on master and it did what I expected. All dependencies use syn `0.15.31` and one dependency (support/procedural) enforces this. I don't know why your build is acting differently.

**Comment by xlc** [comment]
Maybe related to my project setup. It is based on the old node template project. I have pin the version on my substrate fork and it is fine now.

**Comment by bkchr** [comment]
Yeah, then you probably not point to the correct substrate commit and you get the old behavior.

**Comment by CAD97** [comment]
Based on a quick overview, you should be able to just replace your usage of your `CustomToken<T>` with `T` and it should "just work".

All syn custom tokens created with `custom_keyword!`/`custom_punctuation!` implement `Parse` and `ToTokens` through the (not public API) `CustomToken` trait.

**Comment by thiolliere** [comment]
https://github.com/paritytech/substrate/pull/2386
https://github.com/paritytech/substrate/pull/2383

done and backport
