### ISSUE TITLE
seal: code_hash queries

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#2346]
It might be useful to allow contracts to query their own `code_hash`. One thing that this would allow is to create contracts with identical codes.

Another possibility is to allow contracts to query `code_hash` of another contract specified by some address.

These two are not required for MVP and they are also not interdependent and can be delivered separately.

**Comment by thiolliere** [comment]
> Another possibility is to allow contracts to query code_hash of another contract specified by some address.

This is interesting for a contract to be able to trust another contract. For example a cookie-contract that is only writtable by a erc20 contract. The account will say to erc20 hello I want to use you and this is my cooke-contract, and erc20 will store the data he wants to store in this one and trusting by its code_hash.

Although this mecanism is not entirely needed due to CREATE2 properties because the address of a contract contains the code_hash, user and input_data so user can just say hello use this contract, it has been created by him with that input.
But we might not want to rely on CREATE2 properties.

**Comment by pepyakin** [comment]
Good point on CREATE2. However, I believe that `code_hash` query still provide at least some benefits:

1. As I mentioned in the first comment, `code_hash` query of the caller gives an ability to create instances with the same code that the caller has. Otherwise, the caller would have to have `code_hash` embedded as a literal but this might be not feasible.
2. Proofing that a contract has a certain address becomes more straightforward: you don't have to provide the caller address and data used to compute the address, you just compare hashes.
3. A `code_hash` query can tell whether a given address is a regular account (i.e. its `code_hash` is null) whereas `CREATE2` can only proof that a particular address is a contract.

**Comment by athei** [comment]
Closed by https://github.com/paritytech/substrate/pull/10933
