### ISSUE TITLE
The mul operation of Perbill doesn't work properly

### ISSUE THREAD

**Issue by shaopengw** [paritytech/substrate#2441]
I was trying to calculate multiplying a balance value by a ratio via `Perbill`, like `Perbill::from_percent(90) * my_balance`. But the mul operation of `Perbill` won't work for large values like when balance is `u128` and 1 coin is *10^18*.

As in the `Mul` impl of `Perbill`, rhs is converted to `u64`, and the output would be saturated to `u64::MAX/1_000_000_000`, which around *1.84 * 10^10*. This make it impossible to multiply by a typical balance value.
https://github.com/paritytech/substrate/blob/e2fc0430ab3bcd644cded0353d4514611256ad3c/core/sr-primitives/src/lib.rs#L209-L212

Due to `Currency::Balance :As<u64>`, this implicit saturating is error prune for balances calculation, such as offline slash calculation in staking module if I don't misunderstand: https://github.com/paritytech/substrate/blob/fc836ada049f7e3bafca5414738bb14a027d1937/srml/staking/src/lib.rs#L1018-L1019

Expected behavior: `Perbill` should be capable of `u64` and `u128` multiplying, and saturate the output to be `Output::max_value()`.

**Comment by Kianenigma** [comment]
relating to https://github.com/paritytech/substrate/issues/1572 and https://github.com/paritytech/substrate/issues/1377. 

A bit hacky but afaik, by design, `Perbill` and `Permill` are only safe and sound to be used for balances that are `As<u64>` (i.e. smaller than `u64::max_value`). @thiolliere even has a mention in one of the above discussion about these two being erroneous.

Though, in the grand scheme, the above issues won't solve everything. You have to take into account that the runtime cannot simply interpret a number which is larger than `u128`. Hence, if your balance is already a `u128` and you want to multiply it by a ratio (in this case a scalar) there is always the possibility that it will overflow. I agree with your recommendation of making perbill/permill large enough to handle u128, but think of this:

Hasdow to calculate `Percent(99) * X` where `X` is a very large value in the scale of u128, say almost the `max_value()`. This is why [one proposed suggestion](https://github.com/paritytech/substrate/pull/2205#issuecomment-483551470) is for the modules to always accept a `Convert` config type from the implementer to convert any balance to u64. Only then, applying _any_ arithmetic with u128 will be safe.

You should also look into `phragmen.rs` in Staking as it is dealing with many similar problems w.r.t. accuracy. 

cc @thiolliere @gnunicorn

**Comment by xlc** [comment]
parity-common provides U256 / U512 type, can we use them to do math so that U128 as U256 * 99 / 100 won't have overflowing intermediate state?
I know it have performance implication but a slow chain is better than a broken chain.

u64 is simply too small. People are going to trying to bridge ERC20 tokens into substrate chains and their types are U256. We need to support ERC20 balance types.

**Comment by Kianenigma** [comment]
I am not sure if this is enough to justify bringing types such as U256/U512 into the **runtime** (keeping in mind that it should be used for much more fundamental purposes) but I like to see everyone's opinion on the discussion. 

And I'll try to come up with some temporary ways to harden `Per-X` types for multiplication.

**Comment by xlc** [comment]
What are the downsides of bring U256/U512 into runtime?
Increase runtime size? I don't expect they will increase the side significantly.
They are slow? There must be some way to optimize the calculation performance if those types are actually causing performance issue.
Anything else I have missed?

**Comment by thiolliere** [comment]
I think user should defines its type. and Permill and Perbill should operate in those types.
optimisation is let to user.
This comment shows how to operate in the type: https://github.com/paritytech/substrate/issues/1377#issuecomment-476278870

Also it worth mention that it was the previous behavior before like in January

**Comment by DemiMarie-temp** [comment]
I think that balances should be `u128`.  Ideally, the runtime would use bignums, but that is slow.  Perhaps we could use trapping arithmetic?

**Comment by thiolliere** [comment]
I implemented operations in a better way in the PR, no overflow nor saturation, by differentiating operation on quotient and remainder https://github.com/paritytech/substrate/pull/2501
