### ISSUE TITLE
Make subkey transfer feature optional or disableable via feature flag

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#2477]
I need to be able to do sr25519 in python/go/any non rust non js environment but there is no sr25519 library available AFAIK. So the quick workaround is invoke subkey via command line.

I want an executable that is small and lean but subkey currently depends on node-runtime which bundles the whole substrate runtime, which is not useful for my case and useless for any other non substrate chain.

It also make build slow.

Transfer feature can be enabled by default as long as there is a way to disable it during the build.

**Comment by burdges** [comment]
I think someone should write C bindings for schnorrkel.  See https://github.com/w3f/schnorrkel/issues/32

**Comment by folsen** [comment]
I think it makes sense to just build wrapper libraries around the rust sr25519 libraries here rather than depend on subkey at all, I don't think we should all be building all of our infrastructure around subkey because there is no native language support. The benefit of Rust is that you can generate C-bindings really easily, then use them in Python/Go/whatever.

**Comment by burdges** [comment]
Someone did a partial one https://gitlab.com/kauriid/schnorrpy/
