### ISSUE TITLE
The peerset manager should forget about peers after a while

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#2544]
Situation: we discover a node A, but then that node goes offline and disappears forever.
At the moment, we will periodically try to connect to A, forever, and there is no mechanism to forget about A.

Unfortunately the PSM cannot differentiate between "we are actually connected to a node" and "we are trying to connect to a node". It also cannot differentiate between "we disconnected from a node for which we were connected", and "we failed to connect to a node".

Therefore the way to do this would be, for example, to forget about nodes for which we got disconnected from several times in a row.
The precise mechanism is a bit blurry to me and needs to be determined. We could use the reputation as a hint (a node with a high reputation shouldn't be forgotten).

**Comment by marcio-diaz** [comment]
We could use the same time penalty for peers with positive and negative reputation. Then A will have a negative enough reputation at some point and we will disconnect for good. I think it can be a constant penalty, for efficiency.

If we want to forget reputation, we can do it apart, every M minutes, more efficiently, without eroding the reputation of all peers on every tick. In this case, we could take into account the old reputation while choosing to connect.

Sorry if I'm being repetitive, I'm not sure I was clear enough with my comments on the original issue.

**Comment by tomaka** [comment]
This isn't really about connecting and disconnecting. It's about when to remove any knowledge about a node from our memory, because we think that it is offline and will not come back online any time soon.

**Comment by gavofyork** [comment]
No; the correct way to think about this is purely in terms of cost/benefit.

Connecting to a node exerts a small opportunity cost; in connecting to them we are not connecting to some other node. Therefore their score ("reputation", as it is misnamed all too often) gets reduced proportional to the time that they are assign one of our connections.

Since they never actually connect, we never have a chance to benefit from them. The net outcome is that they get reduced more and more. We can expect nodes that have gone offline for a long while to stay at the bottom of our score table.

Removing them should just be a pruning operation. Basically, we should keep a number of nodes in our table and just drop the nodes whose scores don't make it into the top of the table.

**Comment by gavofyork** [comment]
(If you ever revert to thinking "Unfortunately the PSM cannot differentiate between [low-level-concept-1] and [low-level-concept 2]", then you're probably not thinking about things in the right manner.)

**Comment by tomaka** [comment]
So should we just forget the node with the lowest reputation if the list reaches a certain number of entries?

**Comment by tomaka** [comment]
Done in https://github.com/paritytech/substrate/pull/5108
