### ISSUE TITLE
`substrate-node-new` installs `template.rs` module rather than adapted template file. 

### ISSUE THREAD

**Issue by chrisdcosta** [paritytech/substrate#2547]
When you run `substrate-node-new` specifying a name for your node as an argument, the installation completes creating an initial template module named `template.rs`, and the associated entries for a module named "template" in `lib.rs`. 

In other words neither of these file take the name that was specified as an argument. 

This is somewhat unexpected behaviour as many other files are adapted using the name argument during the installation and also considering that `substrate-module-new` can be used to create a template module file adapted by the name argument. 

This may lead to some confusion, although I concede that it is only a template module used for guidance.

**Comment by bkchr** [comment]
CC @shawntabrizi

**Comment by shawntabrizi** [comment]
@chrisdcosta I don't think it makes sense to rename `template.rs` to the same name as your node. Often, a user's node will not be named the same as a single module you create.

There are 4 thins that need to be kept in sync for something like this to work:
- the name of the module file `example.rs`
- the import of the module `mod example;`
- the declaration of the module Traits: `impl example::Trait for Runtime {...}`
- the addition of the module to the `construct_runtime!` macro: `Example: example::{Module, Call, Storage, Event<T>},`

This seems pretty easy to do to be honest, but it is just whether this is the intended functionality.
I sort of agree that it would be just way more clear to keeps things as "template" and not have the user think that any of these files or lines of code are required.

**Comment by chrisdcosta** [comment]
I agree this is pretty straightforward, it wasn't so much about what needed changing from the basic template, more how a beginner goes about discovering/learning why things are changed given that their intention would likely be to create their own module by name. Again I conceded that once they are building in earnest their project may have multiple module files.

What isn't obvious for the beginner (in my opinion) is the a relationship (or not) between the naming of the template module file and the entries that appear in both `lib.rs` and `template.rs`.

* `mod template;` (and by implication `impl template::Trait for Runtime {...}`) is directly to the name of the module file _in lowercase_.

* in the `construct_runtime!` macro however the declaration 

```Rust
Template: template::{Module, Call, Storage, Event<T>},
``` 

is related to the storage declaration  and must be in _upperFirst_ - I'm pretty sure that the `construct_runtime!` macro is case sensitive, hence `decl_storage` is also sensitive.

```Rust
decl_storage! {
	trait Store for Module<T: Trait> as Template {...
``` 

Case sensitivity is easily overlooked by the beginner. Being explicit with recognisable information that they themselves chose would help make this very obvious.

e.g. argument `<enteredname>` becomes file name `<enteredname>template.rs` becomes `mod <enteredname>template`... etc and it follows:

```Rust
// <enteredname> converted to upperFirst  
EnterednameTemplateModule: enterednametemplate::{Module, Call, Storage, Event<T>},
``` 

leads to...

```Rust
decl_storage! {
	trait Store for Module<T: Trait> as EnterednameTemplateModule {...
``` 

By the way to further add to the confusion `substrate-module-new` can produce a template module file with the storage declaration in lowercase if it is provided as an argument in lowercase.

**Comment by shawntabrizi** [comment]
@chrisdcosta I think you are over analyzing the naming stuff a little bit.

Yes, if you make a `filename.rs` file for a library crate, then you can import it using `mod filename;`. This is just Rust: https://doc.rust-lang.org/book/ch07-02-modules-and-use-to-control-scope-and-privacy.html#separating-modules-into-different-files

The name of the file, and the `mod` import really mean nothing and could be completely abstract, but of course, throughout things like `filename::Trait` and `filename::{Module, Call, Storage...}` you use that specific module name since you have brought it into scope with that name.

So all of these are connected.

Then you have the true "naming of your module" in the construct runtime macro:

```
MyModuleName: filename::{Module, Call, Storage...}
```

in this case `MyModuleName` does not have to be anything related to the module name you imported, but ultimately will be the name that your runtime metadata uses to generate user facing names in the UI/UX. Same with the `decl_storage` naming, it can be whatever you want to name your storage item to be, and should ultimately be unaffected by any other naming in your module/runtime.

In terms of capitalization, we again are just following basic rust practices:
https://doc.rust-lang.org/1.0.0/style/style/naming/README.html

* Modules -> `snake_case`
* Types, Traits, Enum Variants -> `CamelCase`

I get the confusion, but Substrate is a Rust framework, and as such, I do think that it is not really our place to teach Rust in general, but to teach the parts of Rust relevant to Substrate.

Given this explanation, are do you feel the same about what you would like to see changed in the scripts? Could you imagine that better documentation around the specific here could solve your issues?

**Comment by chrisdcosta** [comment]
I agree I may be over thinking this! As far as documentation goes then it may be as simple as putting a comment in the template module, that refers to the relevant code to be changed in `lib.rs`, and vice versa.

**Comment by chrisdcosta** [comment]
Not required to be changed.
