### ISSUE TITLE
How to get an ordered linked_map?

### ISSUE THREAD

**Issue by liuchengxu** [paritytech/substrate#2631]
Currently I don't see an easy way to make a linked_map to be ordered by the value. Do you have a plan to support ordered linked map in substrate? What's the best way to get an ordered linked_map at the moment?

**Comment by burdges** [comment]
Are you asking about the execute block function specifically?  There is no local randomness in the execute block function, so you need the random state to be defined by the chain.  We might worry this creates a DoS vector but nobody analyzed this yet.  BTreeMap works fine.  IndexMap has an interfaces compatible with substrate despite using randomness internally, so maybe eventually.

**Comment by liuchengxu** [comment]
No. I'm actually asking about the provided data structure `linked_map`. Assuming I define a storage item in `decl_storage!`:

```rust
pub Foo get(foo): linked_map T::AccountId => T::Balance;
```

`Foo` could be huge eventually and I do need to sort it by the value `T::Balance`. Currently the `linked_map` seemingly only supports doing inserts from the beginning. I have no idea how to get it sorted at present.

**Comment by tomusdrw** [comment]
@liuchengxu Currently we don't have that implemented, I also didn't hear about any plans or use cases to implement that.
To implement this efficiently you would need a tree structure, but most likely that would make all the operations logarithmic instead of constant time. You could implement that in the runtime itself and store the tree structure as `map`.

Note however that enumerating such (unbounded) structure in runtime is not recommended because it's going to be slow and unpredictable, perhaps there is some other way you could achieve what you need?

**Comment by liuchengxu** [comment]
My use cause is sort of generating a validator set from the top candidates in the staking module. Our election algorithm is similar to the one before phragmen. We have to sort the candidates based on their total nominations to get the top ones. 

It may not be a good choice to storage a possibly enormous Vec(candidates or intentions previously called) than Map from our point of view. So we hope to replace the Vec with linked_map, only to finding it may not easy to get sorted :(.

I notice `enumerate()` is used in L122, `substrate/srml/staking/src/phragmen.rs`. My concern is whether it will result in a performance issue when `Validators` becomes utterly huge?

https://github.com/paritytech/substrate/blob/528db6e13ab9e0d5682d2e960eb1c358ac5b33ae/srml/staking/src/lib.rs#L457-L458

https://github.com/paritytech/substrate/blob/528db6e13ab9e0d5682d2e960eb1c358ac5b33ae/srml/staking/src/phragmen.rs#L109-L133

**Comment by Kianenigma** [comment]
@liuchengxu I don't think the `enumerate()` itself (shown in the code snippet) adds a horrible overhead as in this case it is being called on a Rust `Iterator<T>` (not the `::enumerate()` that you get for free by using `linked_map`). Though,

- You point holds. Such codes need to be audited and made sure that economic security is assured (e.g. becoming a validator is sufficiently expensive so that the price needed to exploit this unbounded Vec or Map is large enough). And we are actually using the `linked_map::enumerate()` here:

https://github.com/paritytech/substrate/blob/528db6e13ab9e0d5682d2e960eb1c358ac5b33ae/srml/staking/src/lib.rs#L940-L941

Which I think does not more than going through all mappings and concatenating them, not really being related to partial order or being sorted.

- As for `lined_map` or `map` being sorted out of the box, as mentioned (@tomusdrw) I don't see that happening in substrate level (in my opinion since everything is key/value under the hood. Sorting is simply inefficient)

**Comment by liuchengxu** [comment]
@Kianenigma @tomusdrw  Thanks for your info.
