### ISSUE TITLE
pull-based SRML validator set changes

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#2656]
Right now, the SRML defines transitions between validator sets in terms of _eras_ and _sessions_.

Each _era_ has a different validator set. Era lengths are defined in number of sessions, but can be forced to end earlier by events such as slashing or sudo.
Each _session_ has the same validator set, but with potentially different session keys. Session lengths are defined in number of blocks, but can end earlier if a session change is _forced_.

Sessions and eras ending abruptly is fine for Aura and GRANDPA consensus, but doesn't work for BABE. 

For BABE's randomness beacon to be secure, it requires a fixed _epoch_ length, which means we can't change the validator set immediately after a slashing. What this roughly means is that rather than `srml-staking` and `srml-session` pushing new validators to a consensus engine, consensus engines should be pulling new validators from `srml-session` and `srml-staking`.

I would propose to do this via some kind abstraction over the current existing function `srml_session::check_rotate_session` which allows different session-rotating criteria to be put in place. BABE would have one which was based purely on block-height, while Aura would have something similar which also accommodates forced changes.

When we can't force an immediate validator set change after slashing/sudo, we would need to set things up so that the next session change triggers a new era.

**Comment by rphmeier** [comment]
cc @gavofyork @Kianenigma @DemiMarie-parity

**Comment by Kianenigma** [comment]
At least from the perspective of the Staking module: 

Both through sudo and/or slashing, the Staking does this:

https://github.com/paritytech/substrate/blob/47ff2c6e02b25c049d924d4068eac05de00a2139/srml/staking/src/lib.rs#L765-L769

And the way I see it `apply_force_new_session` in this case will cause `rotate_session` to happen (with `is_final_block == false` in case it is forced) 

https://github.com/paritytech/substrate/blob/47ff2c6e02b25c049d924d4068eac05de00a2139/srml/session/src/lib.rs#L240-L243

https://github.com/paritytech/substrate/blob/47ff2c6e02b25c049d924d4068eac05de00a2139/srml/session/src/lib.rs#L259-L263

which will lead to authorities being changed in consensus and more importantly `T::OnSessionChange::on_session_change(time_elapsed, apply_rewards);` beforehand.

@rphmeier so it looks like Staking actually does need some change unlike what we discussed.

What we could do is to 
- gently not allow Staking to cause a new `force_session_change`. Not sure about the implications.
- allow consensus to restrict the if-statement of entering to `fn rotate session` even more so that even when staking is asking for a new session, it might not get enacted if the consensus thinks otherwise (a more flexible approach I suppose)

**Comment by burdges** [comment]
I'm unsure how works gets divided between the srml-staking and srml-session, but..

I'd expect the validator "assignments" to remain the same, at least till the next epoch, if not beyond, but some validators are marked as booted.  We might still need access to the booted validator's session key to certify transport layer keys.

**Comment by rphmeier** [comment]
What we could do is add a layer of abstraction in staking for `apply_force_new_session` to be called on a trait as opposed to on `session` directly. Or to have `session::apply_force_new_session` to call the trait internally. The trait implementation for BABE would ignore the call, but for Aura we'd want something that did indeed force the session change.

**Comment by kianenigma** [comment]
I assume this is closed now? @rphmeier @DemiMarie-parity ?

**Comment by DemiMarie-parity** [comment]
@kianenigma This is fixed, thanks to @andresilva’s work on fork trees for BABE.
