### ISSUE TITLE
Store complex data in RAM cache

### ISSUE THREAD

**Issue by enfipy** [paritytech/substrate#2712]
I went through some tutorials and docs but saw only `StorageValue` and `StorageMap` types for the purpose of storing data in runtime. Is there any way to store and retrieve data without [tons of maps](https://github.com/shawntabrizi/substrate-collectables-workshop/blob/master/3/assets/3.5-finished-code.rs#L37)?

It would be great to have something like `Multi Index` tables in Substrate runtime (like in [EOS Smart Contracts](https://developers.eos.io/eosio-cpp/docs/db-api) which stores data in RAM cache).

So the question is simple: __Is there any possibility to add `Multi Index tables` in Substrate Runtime and what is the main issue?__

**Comment by vjoke** [comment]
+1

**Comment by bkchr** [comment]
"The EOSIO Multi-Index API provides a C++ interface to the EOSIO database."
So this is not in a RAM cache.

We currently not support multi indexing.

**Comment by bkchr** [comment]
The main issue of this is mostly the overhead introduced by such a feature. Iterating the storage costs a lot of performance and should not be done on-chain.

**Comment by enfipy** [comment]
> Iterating the storage costs a lot of performance and should not be done on-chain
But it's literally done in EOS - maybe there's some fundamental difference that cannot allow adding this feature? Where can I find more information? Documentation a little scarce.

**Comment by bkchr** [comment]
I don't say that is is not possible. You could write a multi index. But it would probably be slow.

"Unlike some other blockchains that only provide a key-value store, EOSIO Multi-Index tables allow a contract developer to keep a collection of objects sorted by a variety of different key types, which could be derived from the data within the object. This enables rich retrieval capabilities. "
That tells you already the problem we have, we use a key value storage.

**Comment by burdges** [comment]
Indexing should be as much an opposite of "iterating through the storage" as the database design allows, but many designs do require some iteration.  

In particular, we do not support non-unique keys because they'd always requires some "iteration through the storage".  If otoh you want tuples (A,B,C) with A and B unique keys then you can have O(log n) access based on either A or B by using a map A -> (B,C) and an "index" map B -> A, which you update simultaneously, but this still doubles your costs.

In polkadot, we produce parachain blocks on collator nodes, who could do almost anything they like, including using databases with non-unique keys.  To do this, you must build a database with non-unique keys that still maintains some Merkle tree and outputs the root and proofs for database operations.  In essence, this amounts to providing sorted indexes next to a substrate-like key-value store.  I doubt sorting can be done with efficiently proof sizes, in which case you cannot commit to the indexes themselves, and thus cannot provide proofs that transactions operated upon entire ranges correctly.  

As an example, if your parachain ran some lottery where winnings were divided among everyone who met some winning condition, like public key in some random range, then parachain collator would steal the rewards by creating many keys and not saying that anyone but their key lived in the winning range.  You cannot do lotteries anyways until we add better randomness, but this attack works even assuming good randomness. 

There are however schemes called sparse Merkle trees that might admit some degree of operation upon entire ranges.  We do want sparse Merkle trees for other reasons but substrate does not support them currently.  As @bkchr said you cannot efficiently operate on ranges with many entries anyways, so you'd need some criteria to reject transactions grew too big.

**Comment by burdges** [comment]
The word sparse appears once in the EOS whitepaper, and not quite in the right context, so we've no idea if they use them and/or operate on ranges efficiently.

**Comment by burdges** [comment]
I'd love it if anyone wanted to do a good implementation of a sparse Merkle tree for substrate of course, and W3F could probably pay for it.  I'll warn however that doing this means reading some papers to get an idea of what all they're good for.  

As one application, a high performance zero-knowledge parachain could've special nullifier tracker nodes that track a sparse Merkle tree of UTX0 nullifiers, and add current proofs that a UTX0's nullifer was never before spent.
