### ISSUE TITLE
Inconsistent dust removal between bond, bondExtra and unbond

### ISSUE THREAD

**Issue by Tbaut** [paritytech/substrate#2805]
`staking.unbond` checks for minimumBalance but not `bonExtra` nor `bond`.

This means that I can have only 1 unit bonded if I call `bond` or `bondExtra` with an original amount of 0 unit bonded.
However I will not end up with a 1 unit bonded if I call `unbond(9 units)` with an original amount of 10 units because the `unbond` function will automatically add the remaining 1 Unit.

This makes any interface with these functions feel inconsistent  

relevant part: https://github.com/paritytech/substrate/blob/bfabed51cf2c4ead5aca08634ddcaf4b3ba837a9/srml/staking/src/lib.rs#L644-L648

it was noted  here: https://github.com/paritytech/substrate/pull/2694/files#diff-b5a024b4f4ae96b0bfc0681acae56709R567

**Comment by gavofyork** [comment]
`bond` should probably be required to be at least ED (or perhaps more).

`bondExtra` shouldn't check for ED since it's only additive: it should be possible to increment the amount bonded by less than ED.

There should be no need for additional logic unless we require a minimum bond of greater than ED.

**Comment by gavofyork** [comment]
CC #3048
