### ISSUE TITLE
Customize the RPC service close time

### ISSUE THREAD

**Issue by jiangfuyao** [paritytech/substrate#2936]
RPC/WS will close if no connection for more than 1 minute.
Add parameter, set automatic close time, or set cancel automatic close.

**Comment by tomusdrw** [comment]
Is that a feature request? What would be the use case? I don't think the RPC server or WS server closes at all currently.

**Comment by xlc** [comment]
WS server drops idle connections after a minute
https://github.com/polkadot-js/api/issues/804

**Comment by tomusdrw** [comment]
Oh, it seemed that this issue was about closing the entire server not dropping a single connection. While it doesn't seems unreasonable to me, we could however implement pinging on the server side to make sure the client is alive.

**Comment by jiangfuyao** [comment]
Yeap, maybe is the server auto closed WS.

**Comment by bkchr** [comment]
As I understand @jacogr in the linked ticket, the js side already sends a ping. Shouldn't that be enough? I don't understand why both sides should send pings.

**Comment by jiangfuyao** [comment]
Sometime the api layer stop, the node WS/RPC service will close too.
All service will shutdown. Need restart node by manual.

**Comment by jacogr** [comment]
Yes, the polkadot-js api itself sends a keepalive ping - https://github.com/polkadot-js/api/blob/master/packages/api/src/Base.ts#L432

If the API stops being active, it is entirely reasonable for the Node to close that connection with the current timeouts. It can certainly happen that due to network conditions one side doesn't believe it is active anymore, in which case the polkadot-js api will reconnect, however that is just the nature of networking.
