### ISSUE TITLE
Block production stalls at end of presentation period

### ISSUE THREAD

**Issue by mattrutherford** [paritytech/substrate#3073]
If there are too many winners at the end of a presentation period, substrate is unable to produce blocks:

`Discarding proposal for slot 390582419; block production took too long`...
Over 2.8 seconds is spent in `on_initialize()` before it bails out.

I haven't found an absolute limit on my machine, but 200 candidates with 100 winners is ok, whereas 1000 candidates and 500 winners is not.

Seems like a situation that is unlikely to occur, but has severe consequences if it does.

**Comment by mattrutherford** [comment]
^ with
```
--block-construction-execution Native
```

**Comment by en** [comment]
Was substrate running in release mode?

**Comment by mattrutherford** [comment]
> Was substrate running in release mode?

yes

**Comment by Kianenigma** [comment]
Is there any idea of whether this is a 
- tx queue issue due to the high load of inputs?
- runtime issue within the council?  

cc @gavofyork

**Comment by mattrutherford** [comment]
txpool was empty at the time; waiting for presentation period to end before sending `reap_inactive_voter` txs.

**Comment by Kianenigma** [comment]
Might be fixed with #3071 soon but other than that I think this is naturally the upper limit of block production time that we are hitting and not much to do about it right now afaict. For your benchmarks, you should probably split this into multiple blocks and time them separately (needs a lot of setups probably, we know that this tx is expensive, you can ignore it from a benchmarking perspective)

**Comment by mattrutherford** [comment]
Will check when #3071 merges

**Comment by mattrutherford** [comment]
>  ...this is naturally the upper limit of block production time that we are hitting and not much to do about it...

Fair enough, but are we sure we have adequate safeguards against this actually ever happening? Because this is basically a bricked chain once it reaches this point.

I think we need some way to ensure that the conditions (preceding state) that cause this are never allowed to happen.

**Comment by Kianenigma** [comment]
> Fair enough, but are we sure we have adequate safeguards against this actually ever happening? Because this is basically a bricked chain once it reaches this point.

I think the only one would be the weight limit. If the sum of tx weights goes beyond limit, it must mean that it cannot be processed within block time and hence rejected.

**Comment by mattrutherford** [comment]
Weight limit wont help here because the tx that cause this have already been included in chain several blocks previously (up to beginning of last voting/presentation period).

This is more to do with `finalize_tally()`which looks to be triggered at end of presentation period I think and is dependant on state ( candidates/leaderboard/seats etc...).

**Comment by Kianenigma** [comment]
This needs to benchmarked properly and we should see how it can be improved. I will assign myself but if anyone else can look into it earlier, please go ahead. 

Question: with the new BABE stuff, would we be __seriously damaged__ if one block, every day or so, takes too much time to evaluate? I have a clear memory of some small retreats in which we discussed this and the idea was at the time that: yes it is bad, but not a big deal since it can't happen all the time. Worst-case scenario one block will be a fat one and will be delayed a bit. cc @rphmeier @andresilva @gavofyork

**Comment by burdges** [comment]
If some relay chain blocks get slow, then we might need to address this in the relative time estimation part of BABE.  It's likely fine if block producers miss their slots due to the slow block, as BABE has considerable variance there anyways.  I'd worry more about producers rushing to make catch their recently past slot.

**Comment by rphmeier** [comment]
@Kianenigma worst case is that block producers might miss slots if they have a few assigned in a row. And for a short time, the chain would fork.

**Comment by Kianenigma** [comment]
Thanks for the info @rphmeier @burdges. 

Let's keep this issue open for now to track the re-thinking of council operations, knowing that we won't die from it in upcoming testnets.

**Comment by kianenigma** [comment]
This module is basically deprecated, and the issue mentioned can be solved if we properly weigh it.
