### ISSUE TITLE
Invalid Extrinsic

### ISSUE THREAD

**Issue by ascjones** [paritytech/substrate#3080]
I'm submitting an `Extrinsic` via rpc (see https://github.com/paritytech/ink/pull/131/files#diff-27c243a8ea077bfe4ff1b511702bcb59R301, rel https://github.com/paritytech/ink/pull/131). 

This worked previously (received `Status::Finalized(_)`) but now I get `Status::Invalid`.

I've run a `git bisect` and narrowed it down to https://github.com/paritytech/substrate/pull/3009. @thiolliere

*Edit* it's also possible that I need to change something on my side, haven't looked at that PR in detail

**Comment by thiolliere** [comment]
I'm not sure what could have changed, maybe this line can be something https://github.com/paritytech/substrate/pull/3009/files#diff-111a5a88bdeff0b7e748bb207bebbf1fL109

so previously I think if someone does a with_storage call and insert CODE key the key didn't get inserted at the end because it wasn't stored in inner field.

Apart from that some calls to child trie in are now maybe effective.

**Comment by ascjones** [comment]
This might be closed by #3244

**Comment by ascjones** [comment]
Indeed
