### ISSUE TITLE
Add APPROVALS_SET_SIZE and VOTERS_SET_SIZE as srml/elections constants

### ISSUE THREAD

**Issue by kwingram25** [paritytech/substrate#3167]
These two are needed to generate api calls for @polkadot/apps but are currently inaccessible.

**Comment by Kianenigma** [comment]
hmmm possible but I wouldn't do this right away: These are_ not configuration_, but rather _internal data-type optimization parameters_. I would say it is better for the front-end code to just assume they will be truly not-changing constant and hardcode them if they are needed.

Can you elaborate on which use cases you need to access them?

**Comment by kwingram25** [comment]
To get the global index passed to elections.retractVoter (at a minimum)

**Comment by Kianenigma** [comment]
If the rust code indicates that for example `VOTERS_SET_SIZE  = 64`. You can assume for now it is always so.

**Comment by Kianenigma** [comment]
I'd leave it open to see if anyone else has a different mindset otherwise should be closed.

**Comment by jacogr** [comment]
The issue here is that it is sprawling out of control quite quickly - i.e. to make voting work, both the polkadot-js UI and Commonwealth UI (both these are working on elections at this point), need to hard-code the values. The Substrate-light-UI will be next after this.

I suppose we can localize these in the polkadot-js API layer (which both these teams use) and provide it as constants so at least there is a single source of the information. (Which hopefully doesn't bite the users of the API at some point)

**Comment by bkchr** [comment]
I will export these values as constants. The constants are made exactly for this use case.

**Comment by Kianenigma** [comment]
you mean the ones we build with 'Get<T>'  trait etc? then I'd still say this sounds a bit strange to be exposed to the outer world. @bkchr

**Comment by bkchr** [comment]
Why is this strange?

**Comment by Kianenigma** [comment]
because it is _implementation detail_ not _configuration_. Though, seeing that there is already a PR for it I also don't have a strong objection against in and it for sure makes the UI code simpler, Sir.

Just note that once we implement sth like https://github.com/paritytech/substrate/issues/2619, this will be deprecated probably.

**Comment by bkchr** [comment]
Yeah that is okay Sir, but the constant stuff was already designed with the idea of exposing also module local constants.
