### ISSUE TITLE
Allow Enumeration of Storage Map Types

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#3675]
At the time being: 

- If a storage is defined as `map`, we do NOT keep to track whatsoever of the keys. 
- If it is a `linked_map`, it can be enumerated but: 

> To enumerate, this is what current happens (assuming staking validators) -
> get the head of the list
> get the next pointer from the head result
> query the next entry based on this pointer
> get the result, extract the next pointer, make next query
> ... repeat until you have all (i.e. next is None)
> So bsically on Alex, we are currently making around 50 RPC calls to populate the list. (serial, result indicates next pointer to retrieve) 

Which makes it quite hard for any potential UI to easily query maps like `Staking Validators` etc. 

What can be done: 

- Add an RPC call that does this linked map walk all at once and returns the set of keys. But, as I have been told, this is not really appreciated since we want to keep the `state rpc` independent of the storage type and it must always operate on _raw, key value storage_. This would introduce an RPC call which only makes sense for linked_map.

- Combined with the fact that we have a [prefix argument](https://crates.parity.io/substrate_rpc/state/struct.StateClient.html#method.storage_keys) to filter and get some keys:
 > Yeah - it’d be good to introduce a map that has a shared prefix.  (Gav)

**Comment by thiolliere** [comment]
> Add an RPC call that does this linked map walk all at once and returns the set of keys. But, as I have been told, this is not really appreciated since we want to keep the state rpc independent of the storage type and it must always operate on raw, key value storage. This would introduce an RPC call which only makes sense for linked_map.

I haven't looked at rpc but maybe we could allow to execute some logic inside.

> Combined with the fact that we have a prefix argument to filter and get some keys:

I think the point of doing the hash of the keys was to make the all storage queries having the same cost and the merkle tree being equilibrated.

Considering this I think the best would be to allow to put storages in decl_storage inside a childtrie instead of main trie.
Child trie gives many advantage:
* computing its hash root is independant to any other trie interaction
* I don't think it is implemented but theoritically we could delete in batch.
* enumeration of entry in a child trie is doable.

thus such pattern could be used.
* grouping many storages in one child trie to be able to remove them all at once.
* put some storage into one child trie to be able to enumarate its value.
* put some storage into one child trie to use proof hash easily.

## Proposal1:

a new attribute in child storage which is the childtrie:

```rust
decl_storage {
MyStorage childtrie(MyChildTriePath): u32 => u32,
}
```

MyChildTriePath would be hashed with twox_128 (same as storage value) so main trie is still equilibrated.

## Proposal2:

same as proposal1 but MyChildTriePath is not hashed.

## Proposal3:

Proposal1 or 2 ++ we can even add a fixed prefix to our storage:
```rust
decl_storage {
MyStorage behind_prefix(MyPrefix): u32 => u32,
}
```

## Critics

* the resulting api of the storage might not be handy as the function enumerate won't be inside StorageMap. user will have to call sr_io::iterate_child and sr_io::iterate_child_prefix
* also this iterate_child method in sr_io is not implemented yet
* if path to child trie is hashed or not hashed this leads to different cost in term of accessing.
  in case of a hashed path the cost to access a value in child trie is related to general cost to access a value in root trie + cost to access it in the child trie.
  in case of a not hashed path the cost to access the value in root trie is not shared by all values.

**Comment by kianenigma** [comment]
> I haven't looked at rpc but maybe we could allow to execute some logic inside.

This is actually not possible as pointed out off-band by @bkchr. But he had a replacement idea which we'll explain. 

I think the child trie, with your explanation, is a worthwhile development. I've heard it many many times that it has been named as _very nice to have_ feature. I have some questions about it:

- It looks like, as the name suggests, we the child trie can be used for anything at different levels (we also haven't implemented any of them afaik so it is all possibilities): 
  - Few or one modules can be in `child_1` and a few others in `child_2`. 
  - Few or one of the storage items of a module can be in a separate `child_1`. 

Is the above correct? 

- What are the exact tradeoffs of using it? I assume there was a reason that from day-zero we did not put each map a separate child trie? 

(In general if there are more sources if info about trie and child of, I would appreciate it :D)

**Comment by thiolliere** [comment]
related to https://github.com/paritytech/substrate/issues/3187

**Comment by xlc** [comment]
with `double_map`, the keys will share a same prefix, that means `storage_keys` can be used to get all the keys for a map.

This is an example to make a standard `map` suitable for such purpose

https://github.com/paritytech/substrate/blob/7d7e74fb77b6bee2ce9d6ebafcae09caff2d0e50/srml/system/src/lib.rs#L419-L420

If on-chain enumeration is also required, something like double_linked_map can be implemented. I actually already implemented here (just need to change `StorageMap` to `StorageDoubleMap`): https://github.com/xlc/substrate-kitties/blob/master/runtime/src/linked_item.rs

One potential issues is that if there are too many keys, the query could be slow / DOS attack vector to node. But there are workarounds available. The query can be partitioned with an additional enumerated prefix byte to reduce query size.

**Comment by kianenigma** [comment]
deprecated and should be closed.
