### ISSUE TITLE
Remove panics in srml-support on corrupted storage state.

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#3700]
In few places we panic in case of corrupted storage state.

https://github.com/paritytech/substrate/blob/429380ea7d109bce29d6aba2c66f33e79c61ea11/srml/support/src/storage/generator/linked_map.rs#L113-L114

https://github.com/paritytech/substrate/blob/429380ea7d109bce29d6aba2c66f33e79c61ea11/srml/support/src/storage/unhashed.rs#L23-L27

To remove them I see two strategy:
* silently handle those error in those functions, like get would return None in case it can't decode and enumeration will stop in case it can't continue (or even maybe update the linkage)
* provides some method with Result output. this would allow module programmer to make some logic to handle corrupted state.
* make the types implement a trait which is:
  ```rust
  trait OnCorruptedState {
    fn on_corrupted_state(state: &[u8]) -> Option<Self>;
  }
  ```
  and this function would be called on when this happens

The question is more do we want to write specific code when state is corrupted ? or should silently fix the storage state by removing values.

note that our silent fix will be somewhat inconsistent like for linked_map if enumeration is broken by a corrupted linkage then some (key, value) are still part of the map (like accessible with get) but not part of the enumeration.

**Comment by thiolliere** [comment]
also with the first strategy:

> silently handle those error in those functions, like get would return None in case it can't decode and enumeration will stop in case it can't continue (or even maybe update the linkage)

I wonder if there is some log feature in the runtime, like we could at least log than an error has happended.

**Comment by bkchr** [comment]
I like your `OnCorruptedState` idea :) 

If we could integrate this somewhat easily into the `decl_storage!` macro, we could by default just return the default value, but we could give the user the possibility to provide a closure that would be running as part of `on_corrupted_state` to give us the new value.

**Comment by kianenigma** [comment]
I reckong storage migration _could_ also be a subset of `OnCorruptedState `?

**Comment by thiolliere** [comment]
> I reckong storage migration _could_ also be a subset of `OnCorruptedState `?

I can imagine having version in the encoding of the values, like one byte for the version (`$Version++encode(value)`) and if version failed to decode then this on corrupted state could be called. But I don't feel that this is the prefered way to do migration.

**Comment by arkpar** [comment]
What's wrong with panicking? Don't we already use panics to bail out of invalid extrinsics and such?

**Comment by thiolliere** [comment]
maybe some more minor modules could panic, and we can just recover from it by some runtime upgrade. The worst thing I see is that if we can panic in some on_initialize of those kinds of minor modules. And with this PR it should be less harmfull

**Comment by gavofyork** [comment]
> What's wrong with panicking? Don't we already use panics to bail out of invalid extrinsics and such?

yes - panics are (might, actually, i haven't checked recently) (mis-)used for bailing out of extrinsics that are invalid  *before* funds are charged, but *conditionally* on their inclusion.

however, there are two reasons why we never want to panic outside of this circumstance:
- if we panic unconditionally (e.g. in on_initialize/on_finalize), then it basically means a bricked chain; by definition no block could be constructed without it panicking and therefore the chain is dead. assuming grandpa is being efficient, then this means we'd have to revert finality to fix the chain which is, well, about as problematic as it gets. 
- if we panic within a transaction, but after funds have been charged, then the panic will have the effect of creating a DoS vector for all validators. they'd be forced to execute the transaction without the possibility of including it into a block and thus getting paid for their efforts. spamming the network with well-crafted transactions that take close to a full block's weight to execute yet can never actually be included would be rather problematic.

thus, if at all possible we want to avoid panicking as a possibility and early exit in the case that we see something which doesn't add up. for transactions this means checking all your data before you write anything. for on_initialize/finalize it's tricker but i would again assume it's better to do nothing and continue with the rest of the processing because this at least allows for a governance transaction to come in and fix storage without reversion.

once we have the ability for on-chain logic to temporarily suspend finality, we should hook it into the assertion system so that a corrupted storage doesn't brick the chain but does halt finality for an extended period of time, allowing us the chance to fix with governance as well as the possibility of a non-finality-breaking reversion.

we shouldn't be attempting to proactively "repair" storage though as that's likely to create even more of a mess that governance would need to clean up.

**Comment by thiolliere** [comment]
current panic has been removed and no need for specific handling as stated above:

> we shouldn't be attempting to proactively "repair" storage though as that's likely to create even more of a mess that governance would need to clean up.
