### ISSUE TITLE
BTreeMaps are missing type information in metadata

### ISSUE THREAD

**Issue by yourheropaul** [paritytech/substrate#3795]
[BTreeMaps](https://doc.rust-lang.org/std/collections/struct.BTreeMap.html) are supported in the [SCALE codec implementation](https://github.com/paritytech/parity-scale-codec/search?q=BTreeMap&unscoped_q=BTreeMap), and they seem to work properly, but they're missing type information in the metadata output.

Storage declared for a module like this, for example:

```
decl_storage! {
    trait Store for Module<T: Trait> as Query {
        pub MyMap get(mymap) : BTreeMap<u32,u32>;
    }
}
```

results in the runtime metadata of (and of course this is a snippet):

```
{"name":"MyMap","modifier":1,"type":{"Type":"BTreeMap"}
```

Where I'd expect something like

```
{"name":"MyMap","modifier":1,"type":{"Type":"BTreeMap<u32,u32>"}
```

**Comment by xlc** [comment]
This should be an easy fix but I am bit worried that use any unbounded data structure (`Map` or `Vec`) as a `StorageValue` could be a footgun. It is too easy to make it too large and end up with a performance nightmare. I find it really hard to justify a valid reason to use `BTreeMap` as a storage value.

**Comment by bedeho** [comment]
Hi, me and @paul work on the same project where this is relevant.

1. Just to clarify, the primary use case for `BTreeMap` is actually a bit different, not the one above, e.g.

```Rust
struct Foo {
 my_field: BTreeMap
}
```
or

```Rust
struct Foo {
pub MyMap get(mymap) : u32 -> BTreeMap;
}
```

and similar. So not as a top-level storage value like this. For that, a genuine storage map would seem to almost always be better, if one leaves aside the issue of reading the whole map conveniently on the client-side/off-chain.

I am not sure if this clarification alleviates your scepticism, in case not, read on.

2. Is the fact that one _can_ get in trouble if one does not apply appropriate guards/access/metering policy a cause for not enabling something. The issue of rationing resource usage is not something one can avoid either way.

3. A principled opposition to containers would seem to make a large range of use cases impossible? And it is used in SRML in multiple places, e.g.

- https://github.com/paritytech/substrate/blob/master/srml/staking/src/lib.rs#L562
- https://github.com/paritytech/substrate/blob/master/srml/aura/src/lib.rs#L154

4. Lastly, the case for `BTreeMap` in particular is that we some times need map semantics, rather than a flat vector. We are also wanting to use `BTreeSet` in other cases.

**Comment by yourheropaul** [comment]
This is an imperfect workaround for this: https://github.com/polkadot-js/api/pull/1474#issuecomment-541049061.

**Comment by thiolliere** [comment]
Is there an issue on the rust implementation, if I add a storage valut with BTreeMap with 
`pub O: BTreeMap<u32, u32>;`

The generated runtime metadata is correct:
```
>          StorageEntryMetadata {
>            name: "O",
>            modifier: Default,
>            ty: Plain(
>                "BTreeMap<u32, u32>",
>            ),
>            default: [
>                0,
>            ],
>            documentation: [],
>        },
```

is there anything to solve here or is it just related to polkadot-js ?

**Comment by jacogr** [comment]
Ahhh... ok, then I know why. 

Since we don't have string handlers and proper parsing into `TypeDefInfo` (the JS internal representation) for it at all (there is an issue logged around it this morning), we don't parse it properly.

**Comment by paul** [comment]
Wrong @paul, but @yourheropaul has a great username too
