### ISSUE TITLE
Is telemetry websocket not has ping/pong message

### ISSUE THREAD

**Issue by freehere107** [paritytech/substrate#3807]
I try to write a monitor program, I defined a WebSocket server for with  custom ``telemetry-url``, when I send ``ping`` message, but not receive ``pong`` message

**Comment by freehere107** [comment]
And Will not reconnect when disconnecting from ``telemetry``

**Comment by bkchr** [comment]
CC @twittner I remember you talked at some point about this. I think we would need to poll the connection to send the pong message?

**Comment by twittner** [comment]
Ping handling was discussed briefly here: https://github.com/paritytech/substrate/issues/3190#issuecomment-516852452. PR https://github.com/paritytech/substrate/pull/3272 made the necessary changes to substrate so I would expect PINGs are answered since 7aa3f2c71c9766f770537106e055c5a72d23841f. Can we get some details regarding the specific versions that are used and maybe some logs? Using `-l substrate_telemetry,libp2p_websocket,soketto::connection` should include the relevant data.

**Comment by freehere107** [comment]
@twittner Thanks you reply
