### ISSUE TITLE
Validator with apparently zero backing chosen

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#4331]
At some point, a validator with zero exposure was found to be offline:

https://polkascan.io/pre/kusama-cc3/event/146198-0

If shouldn't be possible to be selected as a validator with zero exposure. Either there's something wrong with Phragmen or there's something wrong with the exposure fetching as part of im_online.

**Comment by kianenigma** [comment]
could very well be phragmen. I had it on my todo list to add a 'minimum entry barrier' parameter to it, since at the moment, it allows all candidates to be considered and potentially elected.

**Comment by kianenigma** [comment]
Meaning: Phragmen indeed allows one with zero stake to be elected. Yet, I am sure that staking should never allow someone to bond with a value [less than ED](https://github.com/paritytech/substrate/blob/f588aa53af54029c6b45f26342204482f2e946c5/frame/staking/src/lib.rs#L841), so it is even more unclear to me where the issue is. Simple patch is to add the aforementioned `minimum_entry_barrier` parameter to phragmen but I am not sure if this the concern of phragmen. Staking should never allow a validator to have zero stake. They must bond more than ED and unbonding in a way that leads to dust [is also handled](https://github.com/paritytech/substrate/blob/f588aa53af54029c6b45f26342204482f2e946c5/frame/staking/src/lib.rs#L924).

**Comment by burdges** [comment]
We want some minimum self stake I thought, which presumably gives the minimum_entry_barrier, no?  If we supported a separate minimum_exit/ellect_barrier then this requires tweaks to phragmen.

**Comment by thiolliere** [comment]
Is it nearby the last session of an era ? if so I feel it could be related to https://github.com/paritytech/substrate/issues/4121

let's say there is new era at  session 5
at end of session 4 session pallet calls OnSessionEnding::on_session_ending(4, 6),
staking module actually executes this code
https://github.com/paritytech/substrate/blob/c6fc2e6240edeb31233b07748c6bf968c7c15553/frame/staking/src/lib.rs#L1610-L1617

So new_session(5) is called and returns the new validator set.
session pallet receive the new validator set but this set in its queue because he was asking for the validator set of session 6.

Then at the end of the session 5 the value in storage `staking::Stakers` are the new validator set but the value in `session::Validators` is still the old validator set.
So if the offence ask for a validator which is not in next one its exposure is 0.

proposed fix is https://github.com/paritytech/substrate/pull/4346

**Comment by thiolliere** [comment]
I confirm:
* at block 145500 exposure is some for the given account
* at block 145621:
  * the exposure is set to none,
  * staking current era storage change: new era
  * session validators storage doesn't change.
* at block 146198:
  * session validators storage change,

**Comment by kianenigma** [comment]
Replaying the accounts transactions [from CC2](https://gist.github.com/emielvanderhoek/37ac70c8716ddab4e2c8e9a2912c9ac0) from `sudo_as()`:

- block 9082: `staking.bond`: `{value: 100,000,000,000, ctrl: oxff968774036fe8d9800cb8784cdaa4f09bf23096b2a68f589b933c4fe3c3e8d016}`
- block 9085: `session.SetKeys`: ...
- block 9085: `staking.validate`: `{prefs: {validatorPayment: 0}}`
- block 11061: `session.SetKeys`: ...
- block 11080: `staking.validate`: `{prefs: {validatorPayment: 0}}`
- block 12158: `staking.validate`: `{prefs: {validatorPayment: 1,000,000,000}}`

Nothing strange. Current status of the account seems unchanged. Still bonded with 100,000,000,000 and not elected.  FYI `ED` is 10,000,000,000.

> We want some minimum self stake I thought, which presumably gives the minimum_entry_barrier, no? If we supported a separate minimum_exit/ellect_barrier then this requires tweaks to phragmen.

This is implicitly forced via staking; See my previous comment: 

> Meaning: Phragmen indeed allows one with zero stake to be elected. Yet, I am sure that staking should never allow someone to bond with a value [less than ED](https://github.com/paritytech/substrate/blob/f588aa53af54029c6b45f26342204482f2e946c5/frame/staking/src/lib.rs#L841), so it is even more unclear to me where the issue is. Simple patch is to add the aforementioned `minimum_entry_barrier` parameter to phragmen but I am not sure if this the concern of phragmen. Staking (or any other caller of phragmen) should never allow a candidate to have zero stake, if desired.
> 
> Also, unbonding in a way that leads to dust [is also handled](https://github.com/paritytech/substrate/blob/f588aa53af54029c6b45f26342204482f2e946c5/frame/staking/src/lib.rs#L924).

Thanks @thiolliere for following up; Your explanations makes sense.  I'm online is falling into `default()` getter of `Exposure`. Would be good if we could add some optional logs to warn in such cases where the default value of a map is being used? We do have some `map`s that, despite supporting returning a default, should always be fetched with existing values.

**Comment by kianenigma** [comment]
As for phragmen's internal code: as mentioned, unless if further problems pop up, I rather not make it involved in such details. The API is defined as: if a code calls `elect(A)`  with candidate set `A`, it means that any member of `A` could be elected, even if they have very little or no backing support. ATM, both staking and elections take care of this: 
- https://github.com/paritytech/substrate/blob/97d653108cb4dfb6a697c1762e1187f1094481cc/frame/elections-phragmen/src/lib.rs#L627-L630
- in staking since all validators vote for themselves we know that we have the entry barrier.

**Comment by thiolliere** [comment]
Close by https://github.com/paritytech/substrate/pull/4474
