### ISSUE TITLE
CLI: Telemetry URL & Verbosity Flags

### ISSUE THREAD

**Issue by jack-kearney** [paritytech/substrate#4372]
As it stands, the `--telemetry-url` flag expects both the URL of the `substrate-telemetry` server & the desired verbosity of logs to that service. This is confusing and fails silently when misconfigured.

For instance, running a node with `--telemetry-url 'ws://telemetry:8000/submit 5'` will appropriately set the verbosity to a level of `5`, but running a node with `--telemetry-url ws://telemetry:8000/submit 5` will set the verbosity to the default level (`0`) and will silently drop the `5`.

Ideally, a new flag like `--telemetry-verbosity` could be introduced here to add clarity around this configuration.

**Comment by pscott** [comment]
So I see three different ways of addressing this:
1. Having an associated `--telemetry-verbosity` flag for each `--telemetry-url`  (remember the `--telemetry-url` can get repeated to add additional urls).
2. Actually requiring the verbosity to be added (i.e. raising an error instead of defaulting to 0).
3. Keeping this as it is.
4. Modifying this flag to take a vec, and adding `--telemetry-verbosities` -> `... --telemetry-urls [url0, url1] --telemetry-verbosities [verb0, verb1]

3 should not even be in this list.
1 and 4 are actually more complicated and error-prone versions of 2.

So I would go with number 2. Thoughts?

**Comment by bkchr** [comment]
Sounds good.
