### ISSUE TITLE
Improve substrate factory

### ISSUE THREAD

**Issue by marcio-diaz** [paritytech/substrate#4533]
Extend `substrate factory` command to also:

- [ ] Execute using wasm mode.
- [ ] Create all kind of transactions.
- [ ] Have the ability to express dependencies between tx, etc.
- [ ] Report stats about execution time.
- [ ] Support grafana.

Part of #1408.

**Comment by bkchr** [comment]
I would really to get rid off most of the implementation. The problem is that `factory` builds blocks by manually replicating the consensus etc. I think that with https://github.com/paritytech/substrate/pull/4143 we could have a much better implementation that hopefully does not require to have all these hacks in it.
