### ISSUE TITLE
Don't require re-activation of nominations when no slash occured

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#4636]
Currently, if a validator offends, then they are booted, possibly slashed and must seek renomination from each of their nominators. This isn't especially reasonable when a validator accidentally gets caught offline (possibly due to faulty software) and no slash actually happens. Instead, in this circumstance, they should be booted but not require renomination.

**Comment by rphmeier** [comment]
We should extend `SlashingSpans` to store the highest era index where a non-zero slash was applied and compare to that when filtering validators as opposed to the start index of the most recent slashing span.

The only difficulty is in amending the `SlashingSpans` struct. We can't do a migration of all `SlashingSpans` because it is stored in a regular map. An ad-hoc migration that initially sets the value of `last_non_zero_slash` to `self.last_start()` would work.
