### ISSUE TITLE
offchain::http_response_wait() fatal executor error: SpawnError { is_shutdown: true } 

### ISSUE THREAD

**Issue by jingleizhang** [paritytech/substrate#4647]
When I use `offchain` methods:

```
let id: HttpRequestId = sp_io::offchain::http_request_start(method, uri, &[0]).unwrap();
let deadline = sp_io::offchain::timestamp().add(Duration::from_millis(100_000));

match sp_io::offchain::http_response_wait(&[id], Some(deadline))[0] {
	HttpRequestStatus::Finished(200) => (),
	_ => {
		return Err("Request failed");
	}
}
```
it will  return `HttpRequestStatus::IoError`,  runtime logs are:

```
main WARN hyper::common::exec  executor error: SpawnError { is_shutdown: true }
main WARN hyper::client  error spawning critical client task: executor failed to spawn task: tokio::spawn failed (is a tokio runtime running this future?)
```

Substrate Version: commit 39db16e213d92db4f0bffc9dae715ad9c59d2a0c

Is there something wrong with `offchain http_request` or just not the right methods I used ?

Thanks.

**Comment by bkchr** [comment]
CC @tomusdrw

**Comment by tomusdrw** [comment]
@jingleizhang what's the context in which you use those methods? Is it part of `fn offchain_worker` function of your runtime module?

**Comment by jingleizhang** [comment]
yes, the entrance is fn offchain_worker of runtime module, part of it.
If reproducing this bug needs anything else pls let me know, thanks very much.

**Comment by tomusdrw** [comment]
So to be clear, the code returns `HttpError::IoError` and these messages are being printed, right? I think the behavior is correct, the code is missing `http_request_write_body` with empty chunk, which finalizes the actual send (the docs for this are only on for `http_request_write_body` method, happy to review a PR that adds more details to `request_start` too).

Is there any reason why you're using a low-level API instead of the wrapper types from here:
https://github.com/paritytech/substrate/blob/1e0c6794e5f996c78ef1df996d04c3acff5347ae/client/offchain/src/lib.rs#L66

Your code could be greately simplified.

**Comment by jingleizhang** [comment]
Thank you!!

Sorry about this, we implemented this wrapper function about two months ago and did not have time for any refactoring, but now it seems like outdated:

fn http_request_get(uri: &str, header: Option<(&str, &str)>) -> Result<Vec<u8>, &'static str> {
		let id: HttpRequestId = sp_io::offchain::http_request_start("GET", uri, &[0]).unwrap();
		let deadline = sp_io::offchain::timestamp().add(Duration::from_millis(10_000));

		if let Some((name, value)) = header {
			match sp_io::offchain::http_request_add_header(id, name, value) {
				Ok(_) => (),
				Err(_) => return Err("Add request header failed"),
			};
		}

		match sp_io::offchain::http_response_wait(&[id], Some(deadline))[0] {
			HttpRequestStatus::Finished(200) => (),
			_ => return Err("Request failed"),
		}

		let mut result: Vec<u8> = vec![];
		loop {
			let mut buffer = vec![0; 1024];
			let _read = sp_io::offchain::http_response_read_body(id, &mut buffer, Some(deadline))
				.map_err(|_e| ());
			result = [&result[..], &buffer[..]].concat();
			if _read == Ok(0) {
				break;
			}
		}
		if result.len() > 0 {
			return Ok(result);
		} else {
			return Err("Parse body failed");
		}
	}

Sorry about the incorrect usage of low-level API, for both http GET and POST, my questions is must call http_request_write_body() to set chunk data?

I haven’t read through the implementation  of these high level wrapper types, they look very great indeed.

**Comment by tomusdrw** [comment]
@jingleizhang No worries, the API is lacking on some documentation, I wasn't really expecting anyone to be using it and rather using the high-level wrappers.

Yes empty `write_body` is necessary for both GET and POST, as that's when we actually know that the request can be sent (i.e. you won't add any more headers, etc). I guess we could assume that as well if you call `response_wait`, so perhaps the host implementation should take that into account.

Can you test if writing this empty chunk resolves your issue?

Let's keep that issue open and:
1. [ ] Add more documentation to low-level APIs, especially a suggestion to use high-level wrapper instead.
2. [ ] Have `http_response_wait` write an empty body chunk if it hasn't been written already. I think perhaps it is not possible due to different error types that may occur, but worth checking anyway.

**Comment by jingleizhang** [comment]
Thanks for those references, but still not working using these codes:

```
	fn http_request_with_header(
		uri: &str,
		method: &str,
		header: Option<(&str, &str)>,
		data: &[u8],
	) -> Result<Vec<u8>, &'static str> {
		let id: HttpRequestId = sp_io::offchain::http_request_start(method, uri, &[0]).unwrap();
		let deadline = sp_io::offchain::timestamp().add(Duration::from_millis(100_000));

		if let Some((name, value)) = header {
			match sp_io::offchain::http_request_add_header(id, name, value) {
				Ok(_) => (),
				Err(_) => return Err("Add request header failed"),
			};
		}

		match sp_io::offchain::http_request_write_body(id, data, Some(deadline)) {
			Ok(_) => (),
			Err(_) => return Err("Add request write body failed"),
		};

		match sp_io::offchain::http_response_wait(&[id], Some(deadline))[0] {
			HttpRequestStatus::Finished(200) => (),
			_ => return Err("Request failed"),
		}

		let mut result: Vec<u8> = vec![];
		loop {
			let mut buffer = vec![0; 1024];
			let _read = sp_io::offchain::http_response_read_body(id, &mut buffer, Some(deadline))
				.map_err(|_e| ());
			result = [&result[..], &buffer[..]].concat();
			if _read == Ok(0) {
				break;
			}
		}
		if result.len() > 0 {
			return Ok(result);
		} else {
			return Err("Parse body failed");
		}
	}
```

```
call fn http_request_with_header with empty data:

Self::http_request_with_header(uri, "GET", None, b"")
```

**Comment by jingleizhang** [comment]
Also not working with these codes:

```
fn http_request_get(url: &str) -> Result<Vec<u8>, &'static str> {
		let pending = http::Request::get(url)
			.send()
			.map_err(|_| "Request http GET failed")?;

		let response = pending
			.wait()
			.map_err(|_| "Request waiting http response failed")?;

		if response.code != 200 {
			return Err("Request Non-200 status code returned");
		}

		let result: Vec<u8> = response.body().collect::<Vec<u8>>();
		return Ok(result);
	}
```

got same runtime WARN logs.

**Comment by tomaka** [comment]
The update to tokio 0.2 probably broke it.

**Comment by jingleizhang** [comment]
used another version that's in master: 6688c3be1ff71803d5963935df7a0d646b2d50d2, then  it looks like fine.

**Comment by tomusdrw** [comment]
@jingleizhang Yeah, it's most likely what @tomaka said, the recent update to tokio 0.2 broke this stuff.
I believe having an integration test is definitely what we need to prevent that from happening.
