### ISSUE TITLE
support crypto primitives to verify X.509 certificates in runtime API

### ISSUE THREAD

**Issue by brenzi** [paritytech/substrate#4664]
For [substraTEE](https://github.com/scs/substraTEE) to be able to run as a parachain, we'll need to be able to verify certificates (of the Intel attestation service) within a runtime call.

Right now we do that with custom host_calls:
* https://github.com/scs/substraTEE-node/tree/master/host_calls

This is not allowed for parachains because relay-chain validators just know the wasm runtime, not the custom host calls.

The following primitives would be needed for substraTEE (maybe we could settle on a smaller set. but that's what substraTEE supports right now):
```
static SUPPORTED_SIG_ALGS: SignatureAlgorithms = &[
    &webpki::ECDSA_P256_SHA256,
    &webpki::ECDSA_P256_SHA384,
    &webpki::ECDSA_P384_SHA256,
    &webpki::ECDSA_P384_SHA384,
    &webpki::RSA_PSS_2048_8192_SHA256_LEGACY_KEY,
    &webpki::RSA_PSS_2048_8192_SHA384_LEGACY_KEY,
    &webpki::RSA_PSS_2048_8192_SHA512_LEGACY_KEY,
    &webpki::RSA_PKCS1_2048_8192_SHA256,
    &webpki::RSA_PKCS1_2048_8192_SHA384,
    &webpki::RSA_PKCS1_2048_8192_SHA512,
    &webpki::RSA_PKCS1_3072_8192_SHA384,
];
```
Moreover, we'd need **base64** decoding

Our minimum requirement is the [actual Intel certificate](https://github.com/scs/substraTEE-node/blob/master/host_calls/AttestationReportSigningCACert.pem) which has these properties:
```
...
hashAlgo: 1.2.840.113549.1.1.11 (sha256WithRSAEncryption)
keyType: 3072 bit RSA
....

```
*edit:* moreover, we need ECDSA with secp256 & SHA256 (not secp256k1 which is already supported).
So, from the above webpki set, we need at least:
* **RSA_PKCS1_2048_8192_SHA256**
* **ECDSA_P256_SHA256**

This would fix the main obstacles in https://github.com/scs/substraTEE-node/issues/17

**Comment by brenzi** [comment]
@bkchr: That's now finally the issue we were talking about at sub0.1

**Comment by burdges** [comment]
It's risky for an execute block function to forward cert verification to the system.  It'll need some certificate pinning scheme so that everyone verifies against the same certificate.  

There is a much simpler first step however: You create the session keys in the TEE, modify all the APIs so that the TEE cannot expose the session secret keys or import session secret keys, only export the session public key and import the certificate by a controller key.  

At this point, you can attest that the session secret key is controlled by a TEE, but other validators cannot verify this attestation from WASM, but nominators can manually validate this attestation when making their nomination votes.  In fact, this already permits validator operators to attest to their session key management practices to nominators.  As slashes shall commonly stem from poor session key management, this helps significantly. 

You might already have this much but I wanted to reiterate that this adds a lot of bang for the buck.

**Comment by brenzi** [comment]
@burdges I our case, the Intel root certificate would be stored on-chain, so it is up to governance to change this key when necessary (revocation by Intel). 

Your suggestion would be a "trusted certificate verification oracle" right? That of course is an option (as we choose to trust SGX anyway and the process can be verified by anyone) 

However: This feature request goes beyond substraTEE, so I'm not sure we should rely on SGX here. The question is how much legacy web2 security should be supported.

**Comment by bkchr** [comment]
If I understand the code correctly, you only need the following function from inside your runtime:
```
fn verify_ra_report(cert_der: &[u8], signer_attn: &[u32], signer: &[u8]) -> Option<Vec<u8>>
```

And this will verify that `cert_der` is signed by `signer`? What does this function returns?

**Comment by brenzi** [comment]
@bkchr  correct, verify_ra_report should be entirely part of consensus and therefore part of the runtime if it is to run as a parachain.

The function verifies a few things more: 
1. It [verifies the certificate from Intel Attestation services (RSA 3072)](https://github.com/scs/substraTEE-node/blob/98e31c983a59e2b4a03287374fa300a951a07d9c/host_calls/src/remote_attestation.rs#L167)
1. it [parses content](https://github.com/scs/substraTEE-node/blob/98e31c983a59e2b4a03287374fa300a951a07d9c/host_calls/src/remote_attestation.rs#L200) and returns them to the runtime to verify
1. it verifies an [additional signature](https://github.com/scs/substraTEE-node/blob/98e31c983a59e2b4a03287374fa300a951a07d9c/host_calls/src/remote_attestation.rs#L266) coming from an ephemeral key (ECDSA)
1. it [returns some parsed and verified metadata](https://github.com/scs/substraTEE-node/blob/98e31c983a59e2b4a03287374fa300a951a07d9c/host_calls/src/remote_attestation.rs#L278) for further processing in the runtime

**Comment by brenzi** [comment]
actually, I realize that I omitted the ephemeral key ecdsa verification in my OP

**Comment by brenzi** [comment]
@bkchr May I ask you for a statement? 
* Does this have a chance to be implemented by parity? 
* If no, would you support a PR for these new primitives?
* Would you have a preference on what crypto libraries would be used?

**Comment by h4x3rotab** [comment]
At Phala Network we have the exact same requirement -- validate x509 on-chain. Currently our solution is to port `ring` to the wasm runtime:

https://github.com/Phala-Network/phala-blockchain/blob/b99c021c2b7a1fa3eebaec86182796cab583fde0/node/runtime/src/execution.rs#L98

**Comment by burdges** [comment]
I think folks want a ring port that runs in wasm for several reasons, so maybe someone should do a ring-wasm crate that work with `[patch]` in cargo.

**Comment by folsen** [comment]
@brenzi why does this need to be on the host interface? I'd first like to prove that it's not possible to do this in wasm before going to adding things to host interface (something that is fundamentally not socially scalable).

**Comment by brenzi** [comment]
@folsen: Even if it is possible in wasm I think that wasm should be kept as lightweight as possible. AFAIU, parity chose to use host calls for all crypto primitives exactly for this reason. I'm just asking to extend the set of supported primitives that are of wide general use (for web2 at least).

What do you mean with socially scalable?

**Comment by folsen** [comment]
> AFAIU, parity chose to use host calls for all crypto primitives exactly for this reason

No, I don't think that's completely accurate. I would prefer to do everything in wasm when possible, but for some things it's just not possible. If it's not possible to do it in wasm then indeed one might have to open up a host function, but something like a hash function might get called thousands of millions of times during sync and needs to be as close to asm speed as possible, is that really the case for X.509 verification?

> What do you mean with socially scalable?

This is the exact same problem Ethereum is suffering with it's governance around pre-compiles. Everyone and their grandmother want their own pre-compile and see it as critical to the success of the platform. However, if we add everyones own custom pre-compiles then why did we even build a generic compute platform to begin with?

**Comment by brenzi** [comment]
Ok, point taken. X.509 will be verified a few hundred to few thousand times within a year worth of blocks on our chain I guess. (not more than once per day per substraTEE-worker)

Shall I take this as a decision against this feature request? Then we can close this.

**Comment by burdges** [comment]
Is intel attestation service really doing RSA signatures?  Jeez, surely side channel attacks could extract that key!?!

Anyways..

I do not know the right abstraction boundaries here.  An interface like ring?  I've no idea about the Web Crypto API but normally the W3C botches everything it touches.

We already have ECDSA signature verification, but restricted to secp256k1 and/or ecRecover.  AMCL implements curves rather generically https://github.com/miracl/amcl/tree/master/version3/rust/src/roms so maybe provide curve arithmetic with user supplied curve parameters, except doing this requires many functions and the generic implementations run slower.

We've no performance reason for parsing certs, etc. in native code.  Annoying restrictions might help discourage parachains from using annoying crypto, but probably the reverse.

I think RSA verification becomes even more complex because actually many interesting protocols work in similar ways:  Rabin-Williams gives fast VRFs.  RSA blind signatures use FDH padding.  We could even expose a bignum library, except those come with an array of performance characteristics.  

I'm not opposed to providing something here, maybe useful for oracles too, but I'm not sure about the best choice.

**Comment by brenzi** [comment]
It seems @h4x3rotab is already at it (porting ring to wasm), so we might just wait for their solution:
https://github.com/Phala-Network/phala-blockchain/tree/b99c021c2b7a1fa3eebaec86182796cab583fde0/ring

**Comment by brenzi** [comment]
Thanks to the work by @h4x3rotab on [porting ring to wasm](https://github.com/Phala-Network/phala-blockchain/tree/master/ring) we could drop our host-calls and move all the certificate validation into the runtime. The wasm blob grew from 255k to 352k which I think is nothing to worry about.
[substraTEE-node v0.6.0 (2.0.0-alpha.6)](https://github.com/scs/substraTEE-node/releases/tag/v0.6.0) onwards. See our [ias-verify crate](https://github.com/scs/pallet-substratee-registry/tree/master/ias-verify) as an example.
