### ISSUE TITLE
check-block sometimes Segmentation fault: 11

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#4913]
```
$ ./target/debug/substrate check-block --dev 2 --pruning=archive
2020-02-13 22:59:06 Importing 1 blocks
2020-02-13 22:59:08 Imported 1 blocks. Best: #6
Completed in 1256 ms.
Segmentation fault: 11
```

But seems working regardless. I guess some exit handler not configured correctly?
Also saw a few instance where it didn't seg fault, so some timing / ordering issue.

And it will complain pruning mode is not achieve if I didn't specify `--pruning=archive`, which seems redundant.

**Comment by arkpar** [comment]
This is caused by https://github.com/rust-lang/futures-rs/issues/1470  (duplicate of https://github.com/rust-lang/futures-rs/issues/1349)
The fact that `ThreadPool` leaves threads running after being dropped is totally unexpected. Main thread terminates while the thread pool tasks are still being cleaned up.
I'll see if a workaround is possible.

**Comment by cecton** [comment]
oh yes this is the same bug! On my machine it displays like this:
```
[134] [17:04:39] ~/r/substrate cecton-cli-service-configurations > ./target/debug/substrate check-block --dev 2 --pruning=archive
2020-02-13 18:04:42 Importing 1 blocks
2020-02-13 18:04:44 Imported 1 blocks. Best: #3
Completed in 1213 ms.
pure virtual method called
terminate called without an active exception
fish: “./target/debug/substrate check-…” terminated by signal SIGABRT (Abort)
```

**Comment by cecton** [comment]
Related issue: https://github.com/paritytech/parity-ethereum/pull/7695
