### ISSUE TITLE
Inflation 10% higher than set

### ISSUE THREAD

**Issue by philipstanislaus** [paritytech/substrate#4964]
On our testnet Amber, inflation is at 3.35% even though it is set to a static 3% in code. Is there a simple explanation why that might be the case? 

Details:
Amber is now running since 14.28 days. We have a current supply of 400.516M ARAD, and started with 400M ARAD. That means that we have an annual inflation of around 3.35 %. ((400,516/400)^(1/14,28)^(365)).

Here is how we set inflation to a static 3%: https://github.com/centrifuge/centrifuge-chain/blob/master/runtime/src/lib.rs#L275 

Links: 
Telemetry: https://telemetry.polkadot.io/#list/Centrifuge%20Testnet%20Amber
Portal: http://35.198.185.220/

**Comment by bkchr** [comment]
CC @thiolliere

**Comment by philipstanislaus** [comment]
@thiolliere short follow up – any thoughts on this?

**Comment by thiolliere** [comment]
Hmm I see an error in the way we compute the payout.

this is the code:
https://github.com/paritytech/substrate/blob/5b41575012e935ffefee03d39ae5d925ac7992fd/frame/staking/src/inflation.rs#L24-L46

so this formula:
```
payout = yearly_inflation(...) * total_tokens_at_start_of_era / era_per_year
```
is false. instead it should be:
```
payout_for_era = total_tokens_at_start_of_era * (( 1 + yearly_inflation(..)) ^ ( 1 / era_per_year) - 1)
```
because of we want this equation:
```
total_tokens_at_start_of_the_year*(1+c)^N = total_tokens_at_start_of_the_year*(1+yearly_inflation(..))
c = payout_for_era/total_tokens_at_start_of_era
```

thanks @AlfonsoCev for equations

**Comment by philipstanislaus** [comment]
Great find, thanks @thiolliere !

**Comment by thiolliere** [comment]
Some reasearch:

implementing a exponent without using float can be consuming, the current formula does an approximation of the function using taylor serie with only the first derived.
we could just add more terms.

I draw some function here https://www.desmos.com/calculator/irdkafljuq
Dn is difference between payout and the approximation with `n` term
in abscissa it is the yearly inflation.

also:

I still want to figure out if this is the only reason why inflation is wrong, is there a reason I can't access block below 100_000 ?

**Comment by thiolliere** [comment]
looking at what this approximation cost, it seems it doesn't explain the whole error here.
the error shouldn't be that big it seems: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=be9a820b0c7d18f456e177110ad36606

**Comment by thiolliere** [comment]
So the approximation shouldn't lead to that much error considering that the yearly inflation is close to 0.

But I can't debug further as I can't query state for block before 10 days ago on the portal provided , it returns
```
Error: getStorage(key: StorageKey, at?: BlockHash): StorageData:: -32603: Unknown error occured: Client(UnknownBlock("State alread
```

Should I start an archive node on my machine ?

**Comment by philipstanislaus** [comment]
Thanks for diving into this. 

> Should I start an archive node on my machine ?

That would be easiest – you should be able to do it like this: 

```
docker run -p 30333:30333 -p 9933:9933 -p 9944:9944 --rm -it centrifugeio/centrifuge-chain:20200203153054-c2132bb \
    centrifuge-chain \
    --validator \
    --name="{name}" \
    --node-key={node-key} \
    --chain=amber \
    --bootnodes=/ip4/35.242.216.93/tcp/30333/p2p/QmeoT4nzw5QDRaqdkBfnaqW9grMTLiEuYUpu4hSbseKB8C \
    --bootnodes=/ip4/34.89.161.185/tcp/30333/p2p/QmbNXcLkbD7Z2BaSUTfqb1VEkEDTij9rhS79b8F2uiJ3Ki \
    --bootnodes=/ip4/35.246.201.166/tcp/30333/p2p/QmX1hSCYFgeW876VQvWYkkmxon91ofvsnmk8ceCk1i8Tyv \
    --bootnodes=/ip4/35.242.226.138/tcp/30333/p2p/QmW2NQVT1nLqAJCsxXixHkuCN93bCbbdminYKNSGyEX77R \
    --unsafe-rpc-external --unsafe-ws-external --rpc-cors=all
```

**Comment by thiolliere** [comment]
OK I looked at the chain and here is my conclusion:
indeed payout is the only responsible for increased of total_issuance, (though total issuance has been decrease also).
at the end of each era the payout is slighty wrong as it compute a payout for a using the formula expressed above.

Also your chain start with a balance of 400.060 and not 400.000 which explains why I thought something else was responsible for this error.

So the payout is slightly off because of this approximation of payout. 
you can see the difference on this playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7e90000a7e1f5377f49bbae43ad29f69

I think approximating the equation with taylor serie is good enough for small inflation rate, see https://www.desmos.com/calculator/irdkafljuq

**Comment by thiolliere** [comment]
issue confirmed and is due to current arithmetic of staking module, one solution that solve this for your case is implementing more term of taylor serie.

Superseeded by https://github.com/paritytech/substrate/issues/5096

**Comment by philipstanislaus** [comment]
Awesome, thanks for the help @thiolliere !
