### ISSUE TITLE
Configurable storage hasher

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#5040]
I am updating the storage hasher for our ORML https://github.com/laminar-protocol/open-runtime-module-library/pull/101

For the oracle module, I am using `twox64_concat` for `T::OracleKey`, which is an enum for Acala and LamianrChain, so it is safe as there will be only < 10 possible values.

However this may cause issue if someone is using `u128` as `T::OracleKey`.

Without the ability to configure hasher, it is not possible to implement efficient and reusable pallet.

**Comment by thiolliere** [comment]
to make hasher configurable in the current macro we could change decl_storage to get a type instead of one of the defined variant as such:
```rust

decl_storage! {
	trait Store for Module<T: Trait> as System {
		Account: map hasher(MyHasher) T::AccountId => ();
	}
}
```
MyHasher will then have to implement `StorageHasher`
and also we have to add a metadata function (probably in StorageHasher trait) to retrieve metadata at runtime.
