### ISSUE TITLE
sc-offchain tests stuck on macos

### ISSUE THREAD

**Issue by arkpar** [paritytech/substrate#5102]
When running `cargo test --all --release` on a mac I'm getting tests stuck with this output:
https://gist.github.com/arkpar/16025decce13360118bc5f3af7acac70
Macos has lower handle limit than linux, so that's why it is probably mac specific. 

This raises a few questions.

1. Does it really need a lot of file/socket handles in tests? Could be they are leaking?
2. `Worker has crashed` - is this handled? Looks like the test is stuck, so probably not.
3. Lots of `Worker has crashed` messages suggests there are a lot of workers? Why are there so many?
There's way more "Worker has crashed" messages than actual panics.

**Comment by tomusdrw** [comment]
CC @Xanewok could you take a look? It might be related to your last changes migrating those tests to new tokio? Perhaps we are spawning a huge amount of threads for the runtime for every test?

**Comment by Xanewok** [comment]
The looping happens when the http worker has crashed but the test code continuously keeps asking until it gets the response (which it never will), e.g.:

https://github.com/paritytech/substrate/blob/0c8e05928d9d50e20df4388b9294fadc21058dce/client/offchain/src/api/http.rs#L896-L898

We talked about this with @arkpar and one approach is to programmatically increase the FD limit in a test scenario.
