### ISSUE TITLE
Reuse wasmtime instances

### ISSUE THREAD

**Issue by arkpar** [paritytech/substrate#5141]
`WasmtimeInstance::call` currently spins a new actual instnace of `wasmtime::Instance` for each `call`. Instead it should keep and re-use the same instance. The only thing that's preventing this currently is that the global variables can not be reset to the original state for an instance. So I see two ways of fixing this:

1. Require runtime not to use any mutable globals.
2. Reset globals to the original state on each call. This will require some changes in `wasmtime` probaly.

Re-using the same instance should make wasmtime-based calls significantly faster.

**Comment by pepyakin** [comment]
Actually, the API for manipulating globals exists. The more pressing problem is that we don't have API for    manipulating the linear memory, i.e. we cannot do magic tricks that we are doing with wasmi - i.e. just `munmap` and `mmap` again.

Related issue is this: https://github.com/paritytech/substrate/issues/5036#issuecomment-606011950. It turns out we already have a "bug" that the memory (or more specifically, the heap part) is not cleared for imported memories. There is a discussion about if we actually want to clear this part of the memory at all.

**Comment by arkpar** [comment]
`mmap` on each call is not great, as it  appears to be degrading over time, at least on macos. I'd suggest to skip memory clearing by default. And only do so for
* Authoring blocks
* Retrying block import if there's consensus error
