### ISSUE TITLE
Subtrie API for contracts

### ISSUE THREAD

**Issue by Robbepop** [paritytech/substrate#5215]
# Subtrie API for Contracts

## Insights

The below list marks some insights we gathered throughout the discussion.

- The gas costs and compute costs of the subtree removal should ideally be constant.
    - This is meant from the perspective of the runtime. The lazily performed computation of the actual removal scales with the subtree input.
- Deletion of a subtree should generally be a lazy or deferred operation.
- Operating on a subtree from within a contract should result in a trap.
- We already assume to have lazy subtree removal for the contract self destruct mechanism (`ext_terminte`).
- Maybe we could extend even this proposition to allow some subtree to be payed by another account. (@thiolliere)
- Building up huge subtrees via contracts is very costly (gas) and can often probably not be done in a single execution so deletion of big subtrees can be considered to be an uncommon operation.
- The `Stash` data structure could be used to efficiently implement the subtrie/childtrie ID mapping for contracts on the SEAL side.
    - O(1) `put` (insert new element)
    - O(1) `take` (remove element)
    - O(1) random access
    - Automatically reuses old identifiers (easy to adjust to lazy pruning)
    - Vector-like iteration

## Open Questions

- How can we efficiently transfer ownership of those contract subtries?
    - This is needed for tombstone mechanics.
- Which of the two competing API designs to we prefer?
    1. With `ext_allocate_subtrie` API
        - Slightly more complex API on the contracts side.
        - Pro: We have a clear separation between subtrie creation and storage manipulation and therefore clear vision about their respective gas costs.
        - Not in need of a mapping between subtrie ID and childtrie ID. Contract's would simply be given with the already mapped ID.
    2. Without `ext_allocate_subtrie` API
        - Slightly simpler API for the contracts side. However, for ink! specifically it won't be a big difference in complexity for the implementation of such a feature compared to having `ext_allocate_subtrie` API.
        - How to charge gas costs for the initial subtrie construction that implies creation of a new subtrie? Gas costs must be higher in this case.
        - How to perform the efficient mapping from contract-side subtrie ID and substrate-side childtrie ID?
        - Worse for static analyzers because of implied behaviour of subtrie creation. 
- Do we want to support hierarchical subtries?
    - There is no support for hierarchical child trie (although it would be nice). However, with bulk removal  where you remove based on the child trie specific prefix directly in `rocksdb`, you can do that by defining subtrie child trie unique ID to start with the child trie contract unique ID; then mechanically batch delete of all keys prefixed by contract prefix will also delete the subtrie ones.
    - An API on the contracts side could look like the following:
        - `ext_allocate_root_subtrie() -> TrieId`: Allocates a new root subtrie.
        - `ext_allocate_child_subtrie(parent: TrieId) -> TrieId`: Allocates a new child subtrie for the given parent.
        - A call to `ext_deallocate_subtrie(id: TrieId)` would delete all nested subtries under `id` recursively from the perspective of a contract.
    - Children need to be resolve in the SEAL pallet which could inhibit a performance penalty for subtries with many nested child subtries.

## High-level Problem

During the course of a smart contract execution there is often the case that a contract accumulates a lot of storage over a span of time until some final message performs some calculations based on the accumulated storage which renders this accumulated storage unnecessary.

In Solidity and Ethereum based smart contracts where there is no storage rental fees contracts would simply not perform any clean up of the no longer needed storage and would instead garbage the whole system because that's simpler for them seen in isolation.

However, with contracts that have to pay fees for their used storage this strategy no longer works out and clean-up of storage becomes important.

## Central Question

How do contracts get rid of a lot of associated storage efficiently?

Currently there is no way to implement this efficiently since a contract would be required to clear every associated storage entry in isolation via `ext_clear_storage`. If there are a million of accumulated storage entries that should be cleaned-up ... good luck!
Not only will this cost an immense amount of gas but it will also incur a lot of overhead for the communication between contract and SEAL.

What we need to is an API that efficiently cleans up associated storage entries and an API to allow association of storage entries. More on this in the proposed Subtree solution section ...

### ink! could forbid this kind of usage

This is what ink! currently does. However, it has severe consequences for smart contract writers and the expressivity of contracts. Also this makes writing of some more advanced contracts very difficult or adds a giant overhead to the whole interfacing or internal operations dealing with something similar to garbage collections.

You might argue that you could simply tell smart contract writers to "simply" redesign how they write smart contracts but until we cannot provide them with some base rules or fundamental design guidelines for even the simple cases we should actually not do this since this would rather cause demotivation to use storage rental fees based smart contract chains in the first place.

### Incremental destructing inside ink!

Theoretically we could implement some data structures and algorithms that would try to incrementally destruct `drop`ped ink! storage data structures to distribute their performance impact across several execution contexts. This has not been tested and would definitely require some research but I guesstimate it to be possible in the end.
However, it would have significant drawbacks:
1. It would probably require some storage to manage the storage that should be cleaned-up which is against the principles of ink! to have the lowest possible storage footprint compared to handwritten contract code.
2. The algorithms to clean-up storage would run on the contract side which incurs performance and gas cost penalties to users which is against the principles of ink! to be as efficient as possible in regards to hand-written contract code.
3. It would be way harder or even impossible to guesstimate gas costs of certain routines if this implicit garbage collection mechanism is run in the background.

### Sectioning storage entries

This feature has been discussed a whole while ago already and proposes to allow contracts efficient dissecting access to contract storage entries. For example a contract could query contract storage of key `K` but only of a subset of bytes in the queried entry. The same for write and clean operations. This obviously just introduces another indirection (abstraction layer) in the contract entries and also introduces significant additional complexity into ink! and SEAL and thus was not further considered.

### Adding subtree API for contracts

A very similar solution to the one above but a more natural solution as to how the underlying storage work is the introduction of a subtree API for contracts. There is already a momentum in Substrate to provide something similar to runtimes.

A potential API for contracts could look like the following:

```rust
/// Allocate another subtree (by SEAL) and return its tree ID.
///
/// The tree ID is an identifier to a subtree similar to a Key being the identifier
/// to a concrete storage entry. A tree ID must be provided to the other subtree
/// APIs.
fn ext_allocate_subtree() -> TreeId;
/// Deallocates the subtree.
///
/// Querying or modifying a subtree after deallocation triggers a trap.
fn ext_deallocate_subtree(tree_id: TreeId);
/// Sets the storage of the entry identified by `key` of subtree `tree_id`.
fn ext_set_subtree_storage(tree_id: TreeId, key: Key, bytes: Bytes);
/// Clears the storage of the entry identified by `key` of subtree `tree_id`.
fn ext_clear_subtree_storage(tree_id: TreeId, key: Key);
/// Returns the value of the entry identified by `key` of subtree `tree_id`.
fn ext_get_subtree_storage(tree_id: TreeId, key: Key);
```

The above API could further be simplified by unifying it with the current storage API for contracts:

```rust
fn ext_set_storage(tree_id: TreeId, key: Key, bytes: Bytes);
fn ext_get_storage(tree_id: TreeId, key: Key);
fn ext_clear_storage(tree_id: TreeId, key: Key);
```

With `tree_id` having some pre-defined default value that is considered by SEAL to be the root subtree ID, e.g. `0`.
Given the modified `ext_{set, get, clear}_storage` APIs the only new APIs are the already mentioned:
```rust
fn ext_allocate_subtree() -> TreeId;
fn ext_deallocate_subtree(tree_id: TreeId);
```

Technically a contract could then have 2 layers of storage:

1. Root storage entries.
2. Subtree storage entries.

But those can easily be viewed as a single layer of subtrees living under the root node that identifies with a single contract: Every contract has a subtree (as it is right now?) and this subtree would only have subtrees as child nodes instead of storage entries directly. One of the subtrees would be what is currently the subtree of a contract.
This way removing a subtree via `ext_deallocate_subtree` would be a simple removal while `ext_terminate` would also be a simple subtree removal. This proposal considers this operation to be efficient in the way that everything that might be expensive associated to it to be deferred (lazily evaluated/executed).

## Drawbacks

During some discussion with @pepyakin some points were raised that the implementation of the above proposed system of a subtree API could lead to a significant refactoring of SEAL contracts. This is a serious issue and while I currently do not see a better solution we should really make sure that there are no better solutions that incorporate less amount of work on the very fragile SEAL contracts side.

## Design

It has to be determined if those subtree APIs can be implemented efficiently so that they are actually worth it. Note that there is a certain cost associated to the size of such a subtree upon dropping it. However, this cannot easily be modelled as a constant gas operation if the operation was performed eagerly. So this definitely needs an implementation that defers the high-costs of a potentially large subtree to some time in the past and definitely cannot perform an immediate clean up in all cases.

#### Before

Every contract has its own tree node root and stores its storage entries directly under it.

![subtree_api_before_2](https://user-images.githubusercontent.com/8193155/76406168-91711c80-6389-11ea-98fc-b8578fac4c6f.png)

#### After

Every contract has its own tree node root and stores its storage subtrees directly under it. One of the subtrees is considered to be the default, cannot be deallocated and is always present - in this case for example the `0` subtree.

![subtree_api_after_3](https://user-images.githubusercontent.com/8193155/76406304-cb422300-6389-11ea-8e5d-f3103efb1982.png)

**Comment by athei** [comment]
So you would create every high level collection like `storage::Vec` in its own sub tree in order to drop them with one syscall? I am understanding that correctly?

**Comment by Robbepop** [comment]
> So you would create every high level collection like `storage::Vec` in its own sub tree in order to drop them with one syscall? I am understanding that correctly?

Must not necessarily be a high-level structure. But one possible implementation (out of many) could for example put every combined data structure into their own subtree. I have not yet made concrete design steps into this direction to explore how to actually implement this in ink! since I first want to sort out if something like this can practically be implemented in SEAL and how a potential API for this would look. The above mentioned APIs are just made up by me without precisely knowing the underlying implementation details of SEAL and are just a floating idea. So take those with a big grain of salt for now.

I see a huge potential in having an API similar or equal to the above described subtree API in ink! and other languages and this allows to operate on whole sets of storage entries instead of only single entries at a time. Also it has to be determined if those subtree APIs can be implemented efficiently so that they are actually worth it. Note that there is a certain cost associated to the size of such a subtree upon dropping it. However, this cannot easily be modelled as a constant gas operation if the operation was performed eagerly. So this definitely needs an implementation that defers the high-costs of a potentially large subtree to some time in the past and definitely cannot perform an immediate clean up in all cases.

**Comment by thiolliere** [comment]
### Notes on implementation

The implementation seems doable to me and doesn't seem to involve a big refactor:

*The generation of the TrieId for a contract is only computed at the end of extrinsic, (this is to avoid modifying AccoutCounter during the contract execution because this execution could be reverted but not the cost of AccountCounter modification).
  So instead of generating the TrieId we could generate the TrieIdPrefix which will be used to compute the trieid for each subtree.
  For instance each subtree would be assigned a unique id (unique for the contract, two contract can have same a subtree with same unique id) and the actual TrieId of the subtress would be `concat(contract_trie_id_prefix, subtree_unique_id)`.

* We have to modify slightly account_db.rs to account writing to different subtree

* The contract info instead of having the fields `trie_id` and `storage_size` it would have `trie_id_prefix` and `storages: Vec<subtree_id, storage_size>`.

* instead of StorageSizeOffset (default size payed for an empty storage, supposed to be the price of having an empty alive contract on chain). We probably wants StorageSizeOffset to be the offset for each subtree. and maybe a global offset for when there is no subtree allocated at all.

So I might have missed something but it seems not too difficult.

### Notes about gas pricing

* ext_allocate_subtree: I'm not sure writing to an empty childtrie for the first time cost something different from writing to a childtrie with few values (cc @cheme ). writing to a childtrie should cost depending on how full it is, and where do we write (if it is unbalanced), but if it is a new one or not might not be any difference.
  Maybe this call could be even removed and we should allow contract to use any trie id it wants, probably like any u32.

* ext_deallocate_subtree: Currently batch deletion for childtries is not implemented yet in substrate so the removal of a child trie should be I suppose a function of its size.

### Additionnal thoughts

Something that came to my mind was maybe we could extend even this proposition to allow some subtree to be payed by other account.
For example the contract would allocate a subtree and define the caller must pay for it. (or some other mecanism to make sure the contract can't assign an account that didn't opt-in to pay for it).
And during the rent system we would just remove the subtree if the rent can't be payed. (we could think about some tombstone as well, with tombstone payed by the contract for example using it subsistence threshold).

I don't know if it is not better to allow contract to use any u32 as an identifier of a subtree. Otherwise it will need to store inside the its storage the TrieId like this
```
let a = ext_allocate_subtree();
ext_set_storage("mytrieida", a);

/// and whenever it want to use the subtree
let a = ext_get_storage("mytrieida");
```
which seems a bit costy and it might not be a constrain for SEAL to use any u32 as trieid identifier

**Comment by cheme** [comment]
> ext_allocate_subtree: I'm not sure writing to an empty childtrie for the first time cost something different from writing to a childtrie with few values 

No, as you say it shall cost less as it is an empty child trie. Still in your model you need to increment a `contract_subtrie_counter` to generate the `subtrie_unique_id`. 

Also I guess we consider the possibility to delete a subtrie at some location and spawn a new one at another location, so an indirection similar as the contract one is needed (` Vec<subtree_id, storage_size>` is certainly such indirection).
So it is seems like ` ext_allocate_subtree` is a needed operation to write the new indirection to the new subtrie.

About `concat(contract_trie_id_prefix, subtree_unique_id)` I did firstly think that `hash(contract_trie_id_prefix, subtree_unique_id)` was better in order to have smaller subtrie unique id. That would mean that batch deletion of contract would not be simply the removal of all trie nodes starting with `contract_trie_id`, but would need to be as many subtrie removal as there is ids.
Since this model makes subtrie standard child trie (their root is store in top trie, not in the contract child trie), managing everything as a independent subtrie is fine.
On a second thought the subtree_unique_id does not have to be long, we should simply use  subtree_unique_id as the serializing of an integer counter, so the additional node prefix size would not be that costy and we could batch delete the subtrie with the child contract trie (it seems rather hacky and is probably a bad idea as we want one entry for every child trie batch deletion in the change trie). So I slightly prefer `hash(contract_trie_ide_prefix, subtree_unique_id)` variant.

So I think your model is rather good as it is doable immediatly with the current child trie implementation we got (the one that use storage_key as a unique id).
Still I wonder if using a node per subtrie instead of the `Vec<subtrie_unique_id, storage_size>` could be better (the storage path would be `contract_storage_path ++ serialized_subtrie_counter` so we can allways access the subtrie with trie iteration with prefix `contract_storage_path`)?
Surely I would like to make some hierarchical subtrie where the subtrie root is written in the contract child trie, and where we do not have indirection but this does not seems reasonable (we still have the contract indirection and implementing batch deletion should be the priority one (maybe I will try to revive one of my past pr over or into #4827).

**Comment by thiolliere** [comment]
>>    ext_allocate_subtree: I'm not sure writing to an empty childtrie for the first time cost something different from writing to a childtrie with few values
>
> No, as you say it shall cost less as it is an empty child trie. Still in your model you need to increment a contract_subtrie_counter to generate the subtrie_unique_id.

no the idea is that contract_trie_id_prefix is generated using the counter and subtrie_unique_id can actually just be direclty a u32.

So we would have `trie_id = concat(contract_trie_id, u32)` with contract_trie_id blake2_256 of something.

Thus we don't need to increment anything to allocate new subtree

**Comment by cheme** [comment]
Doesn't your u32 still need to be initiated with some counter value or the size of `Vec<subtrie_unique_id, storage_size>` (in this case the counter increment correspond to writing an additional Vec entry)?

**Comment by thiolliere** [comment]
> Doesn't your u32 still need to be initiated with some counter value or the size of Vec<subtrie_unique_id, storage_size> (in this case the counter increment correspond to writing an additional Vec entry)?

I was thinking we can remove `fn allocate_new_subtree() -> TrieId` and just let contract use whatever u32 it wants.
If we keep `allocate_new_subtree() -> TrieId` it might involve some write in the contractInfo indeed.

**Comment by cheme** [comment]
I understand now, the contract can manage the choice by itself, that's smart.
We still need a way to feed the `Vec` of subtries or a dedicated subtrie node, so it may be easier to use a sequential id managed by the runtime. It would also make the assumption that an id is not used twice more sound.

**Comment by athei** [comment]
I guess this dream is dead because without constant time / bulk deletion (#5280) of child tries this is moot. Additionally, ink3 already implemented its new storage without this API.

We should close here. What do you think @Robbepop ?

**Comment by Robbepop** [comment]
ink! 3.0's `ink_storage` crate could still add and profit from a future subtrie API. I want to note though that this feature is not critical since we developed the dynamic storage allocation schemes. They are far from optimal compared to a built-in subtrie approach and have some unfortunate overhead but they work for the same use cases.

**Comment by athei** [comment]
As @Robbepop pointed out we can implement this with the recently implemented #7740 instead of bulk removal. Moving this to TODO.

**Comment by Robbepop** [comment]
The only concern here is the associated costs for the lazy removal of some subtrie. generally it is nice for a blockchain to be freed from some storage but the main problem so far is that if a contract accumulated too much storage it cannot be freed at once due to block weight limitations. So how do we go about this one here?

**Comment by athei** [comment]
This is the reason why lazy storage removal was introduced. It will remove the trie over the course of multiple blocks then.

**Comment by atenjin** [comment]
so if you are planning to add more api for subtrie, why not add more?

for example, for now
```rust
fn ext_set_storage(tree_id: TreeId, key: Key, bytes: Bytes);
fn ext_get_storage(tree_id: TreeId, key: Key);
fn ext_clear_storage(tree_id: TreeId, key: Key);
```

just provide put/get, however for substrate runtime level, it also provide `next` which can be used for mapping.

ink! has change the Btreemap to Mapping which reduces iter feature, why not add `next` for subtrie api, so that ink! can also iter map just like substrate runtime

**Comment by athei** [comment]
There is an issue for that: https://github.com/paritytech/substrate/issues/11410

**Comment by athei** [comment]
Closing here as it does not make sense anymore since we removed the high level data structures that could benefit from it from ink! for size reason.
