### ISSUE TITLE
Prime member selection in Phragmen Elections

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#5290]
Phragmen doesn't allow preference voting among the approvals, so prime member selection will need to be done independently of the Phragmen election. For now it can just select according to https://en.wikipedia.org/wiki/Borda_count, since it's O(m.n) in candidates/voters and computable progressively with a state O(n) in candidates. [Ranked pairs](https://en.wikipedia.org/wiki/Ranked_pairs) or [Schulze](https://en.wikipedia.org/wiki/Schulze_method) might be a better choice at some point in the future.

**Comment by AlfonsoCev** [comment]
I had a look on the ranked pairs and Schulze methods. I great source is Chapter 4 of [this book](https://www.cambridge.org/files/5015/1077/0783/9781107060432AR_final3.pdf). Both methods take time O(n.m^2) and require space O(m^2), for n voters and m candidates. If we run either method only on the elected council members, so that m <= 24, then the complexities are not too bad. The runtime would likely still be dominated by the seqPhragmen algorithm to elect the council members.
 
The best method seems to be ranked pairs, as it satisfies a bunch of desirable criteria, see [here](https://en.wikipedia.org/wiki/Schulze_method#Comparison_table).
