### ISSUE TITLE
on_initialize should return weight consumed

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#5372]
Currently, `on_initialize` and `on_finalize` have a separate weight functions, and declaring these weight functions follows the API for dispatchables.

This is a suboptimal API. It encourages consideration of `on_finalize` as a peer of `on_initialize` for weight calculation, including the possibility of determining weight through inspection of state, which is not possible. It also precludes the possibility of using computation done in `on_initialize` to contribute towards the weight calculation.

Instead, `on_initialize` should simply return the non-negotiable weight consumed in the block. `on_finalize` should return nothing and have no specific weight associated with it (any weight it needs should be part of the value returned by `on_initialize`). `on_runtime_upgraded` should also return the weight it consumes.

The results should be aggregated through the runtime modules through simple addition.

**Comment by kianenigma** [comment]
should be doable without issues: 

1- remove macro expansions that add the annotation. 
2- remove `pub trait WeighBlock<BlockNumber>` and all of its occurrences
3- add and use the return value in the original `pub trait OnInitialize`. a
4- consider merging with https://github.com/paritytech/substrate/pull/5357 as well but that would be optional and this issue is higher priority.
