### ISSUE TITLE
pallet-contracts: audit allocator usage

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#5379]
Currently a Substrate Runtime allocates memory with the allocator provided by Substrate Runtime Interface. That allocator is actually pretty simple and it might be abused. In nutshell, it has free-lists for different orders (for different allocation sizes that are powers of two) and a linear slab of memory that it reserves for the incoming allocation requests if the corresponding freelists are empty.

That means if the contract can make the Seal Contracts (or, thanks for `ext_dispatch_call` any dispatchable function really) to make allocations with a vulnerable pattern then it can induce out-of-memory which in turn leads to a trap, creating a vector to DoS.

For now, I am a bit concerned about the `AccountDb` abstraction which should be removed with tx storage. The rest seems to be fine (except, of course, `ext_dispatch_call` since it brings open-ended possibilities for exploiting this). We still need to audit that.

- [x] Remove `ext_dispatch_call` and `ext_read_runtime_storage`
- [x] Remove AccountsDb
- [x] Make sure that all places where contracts can trigger allocations are capped

**Comment by athei** [comment]
To expand on that: This issue is about verifying that contracts cannot abuse our allocator as a DoS vector. Given that we will remove `ext_dispatch_call` and `ext_read_runtime_storage` the attack surface will be much smaller than initially expected.

**Comment by athei** [comment]
With the dangerous stuff gone the last thing missing is to go through all places where a contract can trigger allocations (of runtime memory) and properly cap them.

The cap is necessary because the runtime panics when either one allocation is larger than 16MiB or the sum of all allocations is larger than what was made available to the runtime by the node via `--heap-pages`.

Please note that this is different from the memory that is available to the contract itself that is already capped by `Schedule::memory_pages`.

Places that need checking:

- [ ] Dispatchables
- [ ] Reading contract memory (`read_sandbox_memory_*`)
- [ ] Allocations triggered by contract chosen parameters (`seal_restore_to`)

**Comment by athei** [comment]
## Dispatchables

## update_schedule
No allocations are triggered by user data

## put_code
The passed code blob is limited by a schedule imposed limit. Allocations happen during instrumentation of the code. The instrumentation is found safe and a maximum sized contract is instrumented during benchmarking in order to exercise the limits.

## call
The `data` passed does not trigger any allocation dependent on its size and is merely passed through and copied to contract memory which itself is of capped size.

## instantiate
The `data` is handled in the same way as for call. The `salt` is hashed and therefore triggers an allocation of roughly the same size (+ code_hash, sender_id). The size of the passed salt is capped by the block size which is well below the maximum allowed allocation.

## claim_surcharge
No allocations are triggered by user data.
