### ISSUE TITLE
Infinite off-chain pragmen election

### ISSUE THREAD

**Issue by akru** [paritytech/substrate#5530]
**Description**

If, for some reason, off-chain workers miss election `Open` block they can't vote later because of strict equal on election off-chain worker code:

https://github.com/paritytech/substrate/blob/master/frame/staking/src/lib.rs#L1193
```rust
		fn offchain_worker(now: T::BlockNumber) {
			use offchain_election::{set_check_offchain_execution_status, compute_offchain_election};

			if Self::era_election_status().is_open_at(now) {
				let offchain_status = set_check_offchain_execution_status::<T>(now);
				if let Err(why) = offchain_status {
					debug::native::warn!(
						target: "staking",
						"skipping offchain worker in open election window due to [{}]",
						why,
```

This situation is important because off-chain workers disabled for synching state, that's mean that voting is required to be correct finished at `Open` block only.

**Propose**

Use `>=` instead of `==` in off-chain worker runner code.

**Comment by kianenigma** [comment]
This was intentional in the first draft to keep things as simple as possible. Note that there is a fallback mechanism and even if all validators miss this slot, election will happen on chain.

I am mainly waiting for https://github.com/paritytech/substrate/issues/5214 and then ideally validaotrs would randomly start running, some unknown time after the election window is open, effectively eliminating the `==` as you recommended. 

> This situation is important because off-chain workers disabled for synching state, that's mean that voting is required to be correct finished at Open block only.

Can you elaborate more on this? I don't get how it is related to sync. In sync time we don't care about any of this and we never want to execute any offchain worker since previous nodes/validators have already elected the set at that era.

**Comment by akru** [comment]
@kianenigma got it, waiting for updates. On-chain voting isn’t available now, right?

I just mean when validators miss voting block it’s impossible to launch voting again by resync chain.

**Comment by kianenigma** [comment]
> I just mean when validators miss voting block it’s impossible to launch voting again by resync chain.

right, yeah for now this is intentional to prevent duplicated solutions. 

> @kianenigma got it, waiting for updates. On-chain voting isn’t available now, right?

it is available and it is used, if no solutions are received (signed and/or unsigned).

**Comment by akru** [comment]
Ok, in most cases it's elected on-chain.
