### ISSUE TITLE
unsafe-rpc-expose is confusing

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#5710]
https://github.com/paritytech/substrate/pull/5233#issuecomment-616843323

This makes CLI super confusing.

We have `--unsafe-rpc-external`, which is "unsafe" "rpc-external" and now
`--unsafe-rpc-expose`, which is "unsafe-rpc" "expose", not "unsafe" "rpc-expose"

I suggest rename it and improve the docs.

**Comment by tomusdrw** [comment]
CC @Xanewok - please address.

I think the unsafe RPCs should be exposed by default IFF the RPC is not exposed externally. Might be best to use a regular option instead of boolean flag:
`--rpc-methods={Default,Unsafe,Safe}` and `Default` variant would mean: `Unsafe` when no rpc-external and `Safe` when RPC exposed externally.

**Comment by Xanewok** [comment]
I agree with the sentiment and planned to tackle that in a follow-up.

Just to be clear, I beliece we propose to do the following:
|                     	| --rpc-external=false 	| --rpc-external=true 	|
|---------------------	|------------------	|-----------------	|
| --rpc-methods=Default 	|                  	| unsafe calls denied               	|
|  --rpc-methods=Safe   	| unsafe calls denied           	| unsafe calls denied               	|
| --rpc-methods=Unsafe  	|                  	|                 	|

**Comment by tomusdrw** [comment]
@xlc wdyt?

**Comment by xlc** [comment]
sounds good
