### ISSUE TITLE
Show better message when RPC method is disabled

### ISSUE THREAD

**Issue by bkchr** [paritytech/substrate#5903]
Currently when a RPC method is disabled, we only return that the RPC method is not available. I think it would be much better to tell the user that this RPC method exists, but is disabled.

CC @Xanewok

**Comment by niklasad1** [comment]
This should be fixed now, closing

**Comment by bkchr** [comment]
@niklasad1 how does the output look like when you call such a method?

**Comment by niklasad1** [comment]
This was fixed by Jan recently and ported back to the jsonrpsee branch 

for example `system_peers` in polkadot-js reports:

v0.9.22
 `RPC-CORE: peers(): Vec<PeerInfo>:: -32601: RPC call is unsafe to be called externally`

v0.9.21
`RPC-CORE: peers(): Vec<PeerInfo>:: -32601: Method not found`

then I tested it myself I got:

```bash
author_rotateKeys
{"jsonrpc":"2.0","error":{"code":-32601,"message":"RPC call is unsafe to be called externally"},"id":1}
```

So I think should be sufficient to close this issue right? 
I should have explained that when I closed the issue
