### ISSUE TITLE
Publish latest wasm-builder

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#5933]
We need https://github.com/paritytech/substrate/pull/5131 for runtime benchmarking but the latest version 1.0.9 on crates.io does not have it

https://docs.rs/crate/substrate-wasm-builder/1.0.9/source/src/wasm_project.rs

Please make a new version for wasm-builder and publish it.

And are there any docs of how to actually running the benchmarking? Is this the correct command to build? 

```
CARGO_FEATURE_RUNTIME_BENCHMARKINGS=1 cargo build --release --features runtime-benchmarks
```

@bkchr

**Comment by bkchr** [comment]
@xlc published.

You don't need to set `CARGO_FEATURE_RUNTIME_BENCHMARKINGS`. This env variable is set automatically by cargo, otherwise there would have been some documentation on how to use it :D 

Basically, the `wasm-builder` will enable every feature that is enabled for the normal build of the crate, except the `default` and `std` feature. I hope that makes sense!
