### ISSUE TITLE
Support TLS for RPC

### ISSUE THREAD

**Issue by Demi-Marie** [paritytech/substrate#6259]
Currently this must be provided externally via nginx or similar, which is inconvenient.  By using TLS mutual authentication, it is possible to securely and safely make RPC calls over the public Internet.

**Comment by kianenigma** [comment]
Can you elaborate more? You can make an RPC call either through http or https, the latter is basically TLS under the hood without any proxy.

**Comment by DemiMarie-parity** [comment]
I was not able to find documentation for using TLS for RPC.  In particular, I was not able to find any way to provide a certificate and private key.

**Comment by kianenigma** [comment]
won't all of this happen under the hood if you use https anyhow? It seems like you want a custom https in which you can provide your own certificates rather than the ones generated for you in the application layer. 

Is this needed in a specific project or were you asking based on your own requirement?

**Comment by DemiMarie-parity** [comment]
There are a few reasons for providing an external certificate:

* Using the same certificate & secret key used by a web server running on the same system.
* Client authentication
* Importing the server certificate into a client, so that I can send secrets over non-loopback RPC calls.

**Comment by tomusdrw** [comment]
@DemiMarie-parity no it doesn't, but it's trivial to add, since `jsonrpc` library does support that.
@bkchr Last time I checked the IPC transport was the fastest (by orders of magnitude) and also it's the most secure if you use your app locally. But since the priority was to be able to connect from the browser, since that's where it's easiest to build a user-friendly clients, there wasn't really that much requests to include that.

**Comment by DemiMarie-parity** [comment]
@tomusdrw Then I am making such a request :smile:.  IPC also makes writing a native messaging host (for use by browser extensions) very easy, and can be used by Electron apps.

**Comment by tomusdrw** [comment]
@DemiMarie-parity 
The code here just needs `start_ipc`:
https://github.com/paritytech/substrate/blob/55843cea2ea47871ff77e17653e352a439c2ff8b/client/rpc-servers/src/lib.rs#L73
Then you start it here:
https://github.com/paritytech/substrate/blob/55843cea2ea47871ff77e17653e352a439c2ff8b/client/service/src/lib.rs#L550

And the implementation of `start_ipc` should be more or less this:
https://github.com/paritytech/jsonrpc/blob/df1e1ddafd171560f3540fc28f63f3425614a134/ipc/examples/ipc.rs#L9

We will need one CLI option `--jsonrpc-ipc <path>` that will enable the server when configured (imho no need to enable by default).

PRs welcome. Also I think this issue should be closed (or renamed) and the IPC discussions should continue in a more specific one.

**Comment by cecton** [comment]
Since we added IPC, can we close this issue?

**Comment by Demi-Marie** [comment]
@cecton We can.
