### ISSUE TITLE
Network worker might miss wake ups

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#6311]
See the discussion here: https://github.com/paritytech/substrate/pull/6247#discussion_r437280146

This is probably not very important because under heavy load the network worker will wake up anyway at some point, but should still be investigated.

**Comment by romanb** [comment]
I looked into this a bit and from what I could tell, the large variations in runtime of the test from that discussion is not due to task wake-ups but rather because connections often get closed due to an upgrade failure in the ping protocol when reading the response. Ultimately the problem seems to be https://github.com/paritytech/yamux/pull/81 and the fact that the outbound upgrade of the ping protocol [issues an early half-close of the substream](https://github.com/libp2p/rust-libp2p/blob/master/protocols/ping/src/protocol.rs#L90) exarcabates this problem, i.e. makes it much more likely to occur. In any case, with the linked patch the test takes consistently ~6 seconds for me with 32 peers and ~9 seconds with 256 peers, without seeing any unexpected errors or closed connections in the logs.

**Comment by twittner** [comment]
I think the problem with ping is that [this socket](https://github.com/libp2p/rust-libp2p/blob/9aaf04241008a7de9007c644ffec15a3bacbb24b/protocols/ping/src/protocol.rs#L70) is not closed.

**Comment by romanb** [comment]
Feel free to reopen if you think this still isn't resolved.
