### ISSUE TITLE
[CI] publish docker substrate is broken

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/substrate#6380]
seeing [this](https://gitlab.parity.io/parity/substrate/-/jobs/557079#L75) on substrate master lately:
```
 /bin/sh: cd: line 145: can't cd to ./artifacts/substrate/: No such file or directory
$ cd ./artifacts/$PRODUCT/
```

Looks like some path is borked.

**Comment by TriplEight** [comment]
Investigating.
This is funny, because there is [no difference](https://github.com/paritytech/substrate/compare/17be6fd5e5dec2b358dbffa9ce07e4bc1d3e01e2...b02101e9f9424251cb9f965dbf6ff66268d4fa93) in CI config between [the build from your pipeline](https://gitlab.parity.io/parity/substrate/-/jobs/557074) and [another build where everything was fine](https://gitlab.parity.io/parity/substrate/-/jobs/558570).

Restarted the build job.

**Comment by TriplEight** [comment]
So the restarted job has [managed](https://gitlab.parity.io/parity/substrate/-/jobs/559847#L1488) to produce artifacts. Now [publish docker](https://gitlab.parity.io/parity/substrate/-/jobs/560004) is successful.

Maybe it's because of the heavy load on CI lately, but I didn't find any changes.

Please reopen if it happens again.
