### ISSUE TITLE
Add an alternative to sc-network-gossip for parachains

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#6583]
Address points (1) and (2) of https://github.com/paritytech/polkadot/issues/1348

We can add a crate similar to `sc-network-gossip`, except that it keeps track of the number of valid/invalid messages for each peer and pulls messages at a slower rate for peers whose ratio is too low.
The slower pulling rate should in turn apply back-pressure on the connection, and force the sending side to slow down the sending rate.

"Stops processing messages" requires some modifications to the API of `sc-network` in addition to https://github.com/paritytech/substrate/issues/6403. https://github.com/paritytech/substrate/issues/6403 itself depends on https://github.com/paritytech/substrate/pull/5938.

Not strictly-speaking concerned by this issue, but related: #5481 will cause issues on the sending side if we back-pressure the connection.

**Comment by rphmeier** [comment]
Not all of the protocols for Parachains networking are gossip protocols. And actually, many that are currently gossip protocols, we would prefer not to be as there would be major efficiency gains to be made by having validators communicate via direct messaging.

`substrate-network-gossip` is also not async-friendly, so for Parachains networking (https://github.com/paritytech/polkadot/pull/1344 & https://github.com/paritytech/polkadot/pull/1326 ) we have just been rolling our own components that do handle asynchrony & backpressure, although not in a particularly intelligent way.

Because of that, all of the backpressure work on networking can happen behind the scenes, from the Parachains codebase perspective. It would make most sense to me to focus on refactoring the network service to make `write_notification` an `async fn`. The safest assumption to me right now is then to just assume that there are no messages that we can block, and then pause any networking task on `await`ing this function. 

Behind the scenes one layer down in libp2p we would want to be dropping peers who are not accepting messages fast enough, which, as I understand it, has not actually been a problem in practice.

**Comment by tomaka** [comment]
I'm going to close this issue as it's unclear what exactly to do.
#6403 is still relevant, though.
