### ISSUE TITLE
Fixed-point integer types display incorrectly

### ISSUE THREAD

**Issue by DemiMarie** [paritytech/substrate#6869]
The `Display` impl for fixed-point integer types ignores the decimal point.

**Comment by bkchr** [comment]
Please provide an example of how it looks and how it should look like.

CC @kianenigma

**Comment by kianenigma** [comment]
I think this is fine

```rust
                 #[cfg(feature = "std")]
		impl sp_std::fmt::Display for $name {
			fn fmt(&self, f: &mut sp_std::fmt::Formatter) -> sp_std::fmt::Result {
				write!(f, "{}", self.0)
			}
		}
```

There's a `Debug` impl that shows you more accurate internals, as expected, this is a raw representation without any computation. 

I think if you really think it is confusing, change it to

```diff
- write!(f, "{}", self.0)
+ write!(f, "Fixed({}/{})", self.0, Self::DIV)
```

So you know you should not interpret it as a integer number. Otherwise, I think it is fine as it is.

**Comment by DemiMarie** [comment]
@kianenigma I would expect that the decimal place would be positioned correctly.  I had to implement that manually in Ledgeracio: <https://github.com/paritytech/ledgeracio/blob/c21db21f16b5151a10a580fd6c58ca18d831c3f3/src/common.rs#L116-L140>.

**Comment by kianenigma** [comment]
ahh well this is _not_ about the `Fixed` (e.g. `Fixed128`) types in substrate, you simply want to put a decimal point in a u128. I don't think we have an appropriate type for this in substrate, so doing it in your repo is the best.
