### ISSUE TITLE
not found in `self::sp_api_hidden_includes_IMPL_RUNTIME_APIS::sp_api`

### ISSUE THREAD

**Issue by AurevoirXavier** [paritytech/substrate#6898]
If I change the node-template's features to below. But I think the two styles of features should be equivalent.

```toml
[features]
default = ["std"]

std = ["crates-std", "substrate-std", "custom-std"]

crates-std    = [
	"codec/std",
	"serde",
]
custom-std    = [
	"template/std",
]
substrate-std = [
	"aura/std",
	"balances/std",
	"frame-executive/std",
	"frame-support/std",
	"grandpa/std",
	"randomness-collective-flip/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-aura/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"sudo/std",
	"system/std",
	"timestamp/std",
	"transaction-payment/std",
]
```

**Comment by AurevoirXavier** [comment]
I'm not sure is this a rust bug?

**Comment by mbrubeck** [comment]
It looks like this happens because `wasm-builder` parses the `[features]` section itself, and has a hard-coded rule to exclude the `"std"` list but not any other lists.  So any project that uses `wasm-builder` must place all features that depend on libstd in a single list with this hard-coded name:

https://github.com/paritytech/substrate/blob/master/utils/wasm-builder/src/wasm_project.rs#L324-L349

**Comment by bkchr** [comment]
What is the reason for splitting the features like this?

But as @mbrubeck said, this currently does not work.
