### ISSUE TITLE
`system::set_code` is un-callable due to impossible weight

### ISSUE THREAD

**Issue by adamdossa** [paritytech/substrate#7064]
Currently the `set_code` extrinsic has its weight defined as:
```
		#[weight = (T::MaximumBlockWeight::get(), DispatchClass::Operational)]
		pub fn set_code(origin, code: Vec<u8>) {
```

When validating transactions, the maximum weight a single (operational) extrinsic can have is actually:
`MaximumBlockWeight - (ExtrinsicBaseWeight + BlockExecutionWeight)`
(as per `check_weight.rs`, assuming an operational ratio of 1 in the block)

Unless the `ExtrinsicBaseWeight` and `BlockExecutionWeight` are both 0, the extrinsic cannot be directly executed.

This can be bypassed by using `sudo::sudo_unchecked_weight`, but this may be worth referencing in the comment for the `set_code` extrinsic.

**Comment by bkchr** [comment]
CC @shawntabrizi

**Comment by shawntabrizi** [comment]
@adamdossa It does not really make sense to me to write documentation about `sudo` in the `system` pallet.

The way that `set_code` is properly used in the runtime is through the scheduler, which can handle extrinsics with more than `T::MaximmBlockWeight::get()`. If anything, the Sudo would be where such documentation lives, and it does exist already as the text for why `sudo_unchecked_weight` exists.

If you have other ideas on how we can better spread this awareness, I am open ears.

**Comment by shawntabrizi** [comment]
It is also quite intentional that this `set_code` cannot be dispatched through an extrinsic. It should not be that an extrinsic can take more time than the allocated block time, and in the case of `set_code`, it often takes more than the allocated block time. `sudo_unchecked_weight` is a workaround for devs, but in reality, `scheduler` is the only "safe" way to do an upgrade.

**Comment by adamdossa** [comment]
Thanks for the info. Quick question on the `scheduler` - is there a reason this is considered more safe than executing an extrinsic immediately (i.e. through `sudo_unchecked_weight`)?

It looks like in any case, the block where an upgrade executes might run long, and the `scheduler` will allow through a large extrinsic (i.e. one with a weight greater than the block weight) based on the conditions:
```
					// - It's priority is `HARD_DEADLINE`
					// - It does not push the weight past the limit.
					// - It is the first item in the schedule
```

Trying to understand why executing `sudo_unchecked_weight(system::set_code(...))` would be considered less safe than scheduling a `system::set_code(...)` for a few blocks in the future?

**Comment by shawntabrizi** [comment]
@adamdossa its a great question.

The specific reason scheduler is safer is that it executes it's logic during the `on_initialize` of a block, which means it executes before any other external operations come in, and thus if items in the on_initialize already take up the space of the block, no further external transactions will be executed. (Mostly)

Furthermore, it does a best effort load balancing, so that if a dispatch takes a whole block, the next scheduled dispatches will happen the next block.

I think if you step back, you should hopefully agree on the following:
* It is pretty important that our blockchain's blocktime stay constant. (every once and a while is not a huge issue)
* An extrinsic that takes more than the available block time of the chain is invalid. i.e. if you have a function that get's too complex, it is perfectly okay to say this function is not valid for my blockchain. An example of this would be a fibonacci calculator, where at some value of N, the function would no longer be callable due to its heavy weight.
* A Runtime upgrade takes more than the block time.
* Runtime upgrade is a system level operation that must occur at some point.
* Thus is should not be allowed that a user can directly trigger this operation, or that other txs in the queue should be able to push it out.

The `sudo_unchecked_weight` is totally a hack function that gets around all the things we try to achieve with weights, but it is a necessary evil for development and debugging.

But it really should not be used frivolously.

**Comment by adamdossa** [comment]
Thanks - that makes a lot of sense.

We actually implemented a similar approach to the scheduler for runtime upgrades (my use of `sudo_unchecked_weight` was on a local dev chain just to save time going through the full governance process locally) but we'll look into migrating over to using the scheduler pallet instead for consistency.
