### ISSUE TITLE
PeerId inconsistent between subkey and the printout when starting the node

### ISSUE THREAD

**Issue by kaichaosun** [paritytech/substrate#7082]
The subcommand (`generate-node-key`) of subkey prints a PeerId.
Starting the node with `--node-key` specifying the generated private key printout another PeerId.

![image](https://user-images.githubusercontent.com/10568673/92851284-f6ccc580-f41f-11ea-9838-8f60b3aab270.png)

**Comment by romanb** [comment]
This is caused by a bug / regression in `generate-node-key`, which at some point started to hex-encode the key it writes to the file. When the node is started with `--node-key-file` there is no hex-decoding taking place, so in effect the node gets a different secret key and thus a different keypair and peer ID than what was seen by `generate-node-key`. See https://github.com/paritytech/substrate/pull/7052#issuecomment-689572467.

**Comment by tomaka** [comment]
Closing as duplicate of https://github.com/paritytech/substrate/issues/7045
