### ISSUE TITLE
sp-arithmetic  error while doing "cargo build"

### ISSUE THREAD

**Issue by Harman-singh-waraich** [paritytech/substrate#7282]
error[E0282]: type annotations needed
      --> /home/harman/.cargo/registry/src/github.com-1ecc6299db9ec823/sp-arithmetic-2.0.0/src/fixed_point.rs:541:9
       |
  541  |                   let accuracy = P::ACCURACY.saturated_into();
       |                       ^^^^^^^^ consider giving `accuracy` a type
  ...
  1595 | / implement_fixed!(
  1596 | |     FixedI64,
  1597 | |     test_fixed_i64,
  1598 | |     i64,
  ...    |
  1601 | |     "_Fixed Point 64 bits signed, range = [-9223372036.854775808, 9223372036.854775807]_",
  1602 | | );
       | |__- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by bkchr** [comment]
That is a rustc bug. Please downgrade your nightly.

https://github.com/rust-lang/rust/issues/77653

**Comment by hayesgm** [comment]
This isn't hasn't been fixed since this was closed over a month ago, and if I'm reading correctly, it doesn't look like Rust has any open issues to address. Should we just fix the issue here instead of permanently staying on an old version of rust? I believe the fix should be just... adding three type annotations?
