### ISSUE TITLE
How do we calculate storage key of contract storage?

### ISSUE THREAD

**Issue by thashimoto1998** [paritytech/substrate#7347]
Pallets contracts API provide get_storage to query storage of a specified contract under a specified key. This API is used when smart contract read data from its contract storage. 
So I have a question. 
- Is it possible to runtime module call this API for read smart contract storage?
- Is it possible to calculate storage key of contract storage at runtime module(pallets) layer?

**Comment by AtenJin** [comment]
This is a strange question...
In my opinion, obviously, if you implement same rule which is related to generate offset position of storage in `ink!`, you could do this...
But I think a better way is to do `call` in your module, call a contract directly(when you have this contracts address and the call selector) in runtime... rather then try to calculate storage key and use `get_storage` in `pallet-contracts` to get raw storage.

**Comment by thashimoto1998** [comment]
Yes, I know my system design is unusual.
In my design, runtime module function process data(u32 or bool) which is stored in smart contract. 
Call pallets contracts API returns DispatchResultWithInfo<crate::weights::PostDispatchInfo> so this does not return u32 or bool type.

**Comment by bkchr** [comment]
CC @athei

**Comment by athei** [comment]
> Yes, I know my system design is unusual.
> In my design, runtime module function process data(u32 or bool) which is stored in smart contract.

You could still create a getter function in your contract and call that via `pallet_contracts::Module::bare_call()`. So this fact does not mandate your design.

> Call pallets contracts API returns DispatchResultWithInfocrate::weights::PostDispatchInfo so this does not return u32 or bool type.

You should use `bare_call` instead of `call` which returns the `ExecResult` containing the result of the contract call as byte buffer. You can decode that to your `u32` then.  `call` is the the API to be called by extrinsics not other runtime modules.


That being said, I think that querying the storage directly (your original question) is the right thing to do. To answer your original question:

Have a look at the [public API](https://substrate.dev/rustdocs/v2.0.0/pallet_contracts/struct.Module.html) of the `pallet_contracts::Module`. There is the aptly named function `get_storage` which you can use for this exact purpose. The `key` you pass there is exactly the same that the contract would pass when querying the storage.

**Comment by thashimoto1998** [comment]
> You should use bare_call instead of call which returns the ExecResult containing the result of the contract call as byte buffer. You can decode that to your u32 then. call is the the API to be called by extrinsics not other runtime modules.

`bare_call` meats the requirement for my design. Thank you.
Is the value of input_data for specifying a function and arguments in the contract correct at vec![function index, args]? 
Is the function index sequence of messages or selector of messsages in metadata.json?

**Comment by athei** [comment]
What you are asking is completely opaque to substrate and the contracts pallet. It is each and every contract language's discretion how to encode input and return data. 

> Is the value of input_data for specifying a function and arguments in the contract correct at vec![function index, args]?

I think so that this is the case for ink!. I am not sure what the exact encoding is, though.

> Is the function index sequence of messages or selector of messsages in metadata.json?

Yes, the selector are in the metadata. In ink3 you can add explicit 4-byte selectors to your contract:

```rust
impl Flipper {
    #[ink(constructor)]
    #[ink(selector = "0xDEADBEEF")] // Works on constructors as well.
    pub fn new(initial_value: bool) -> Self {
        Flipper { value: false }
    }

    /// Returns the current value.
    #[ink(message, selector = "0xFEEDBEEF")] // ... or specify selector inline.
    pub fn get(&self) -> bool {
        self.value
    }
}
```
For more click [here](https://paritytech.github.io/ink/ink_lang/attr.contract.html).

I am closing here as this is not substrate specific and further questions should be directed to the contract language you are using (I figure ink!).

Support Chat:
https://riot.im/app/#/room/!tYUCYdSvSYPMjWNDDD:matrix.parity.io
