### ISSUE TITLE
Improve benchmark output upon error

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#7386]
Currently when benchmark failed, it will just print the dispatch error message without the context. i.e. the pallet, the extrinsic, the parameters.

It will be helpful to print more context along with the error message when a benchmark failed.

**Comment by ropottnik** [comment]
@shawntabrizi I'd like to take this one over in order to get into the code base.

**Comment by shawntabrizi** [comment]
@ropottnik sounds good! This should be a really easy one, just need to generate the appropriate error message with the info about current pallet and extrinsic being benchmarked, and wrap the actual error so that is seen too.

**Comment by ropottnik** [comment]
Thanks, like I said, I want to use it as a means to get a bit into the code base. I will probably pn you on discord for some general questions on setting things up (like how to actually benchmark something and provoke a failure :D)

**Comment by shawntabrizi** [comment]
From discord chat:

to start, i would clone and compile a local version of Substrate, using the runtime benchmarks features:

```
cd bin/node/cli
cargo build --release --features runtime-benchmarks
```

then i would go and edit one of the benchmarks to have an error
For example comment out this line should be enough: https://github.com/paritytech/substrate/blob/master/frame/balances/src/benchmarking.rs#L88

then if you build again and run the benchmark:

```
./target/release/substrate benchmark --pallet balances --extrinsic "*" ...
```

you should see an error show up
your goal would be to improve that error, which right now does not say anything besides directly what the error is.

I think you need to change this line: https://github.com/paritytech/substrate/blob/master/frame/benchmarking/src/lib.rs#L1082

and the same line in the else statement below, so rather than directly doing `?`
you need to do `.map_err(|e| "new error message here...")?`

i think something like that
your setup to test what the error looks like shoudl help you figure out the details
