### ISSUE TITLE
How to calculate proper weight when one extrinsic relies on existing storage

### ISSUE THREAD

**Issue by MyronFanQiu** [paritytech/substrate#7488]
Benchmarking system is good and easy to calculate proper weights for most extrinsic. However, some extrinsic of our runtime would loop the existing storage and update some status of them. The execution time depends on the size of the existing storage. Weight system can accept the param of the extrinsic already. Is there a proper way to deal with our scenario? Thanks very much!

**Comment by apopiak** [comment]
If you cannot enforce a bound on this execution you will run into problems eventually so in order to determine the weight you will have to figure out how you can determine the complexity of this call before it happens. This is one of the unavoidable constraints when working in the runtime: You need predictable execution time to make it secure (non DoS-able).
One strategy is enforcing an upper bound on the amount of items in your storage. So e.g. bump a counter any time an item is inserted and disallow inserting when the maximum count is reached. That way you can estimate the worst case execution complexity.

**Comment by apopiak** [comment]
See e.g.
https://github.com/paritytech/substrate/blob/78fa1b8062218f1ee5a61c499f433a26ca1783aa/frame/collective/src/lib.rs#L143-L148
and
https://github.com/paritytech/substrate/blob/78fa1b8062218f1ee5a61c499f433a26ca1783aa/frame/collective/src/lib.rs#L322-L326

**Comment by MyronFanQiu** [comment]
@apopiak I see. Maybe we need reconsider our design. Thank you very much.
