### ISSUE TITLE
List of genesis indices?

### ISSUE THREAD

**Issue by alecalve** [paritytech/substrate#7510]
I've noticed that some indices ([like this one](https://polkascan.io/polkadot/indices/account/1kk)) can be created during the genesis of a chain.

There's no `IndexAssigned` event fired for these indices. Furthermore, it seems that they were created with a 0-value deposit which means that freezing them doesn't slash any currency.

In order to simplify logic on my end, I wonder if there's any way to get the full list of these indices easily. So far I've managed to detect whether or not an index was created during the genesis (it is in storage at height 0).

**Comment by bkchr** [comment]
Yeah, we don't send events at genesis.

CC @shawntabrizi @thiolliere

**Comment by shawntabrizi** [comment]
@alecalve You want to get all indices that exist at genesis?

You can look at the genesis file or query the blockchain at block 1 right?

What is the issue or problem you are having? sorry but i feel I am missing something :)

**Comment by alecalve** [comment]
I wanted to be able to follow the lifecycle of indices using events only.

Since genesis-created ones don't have `IndexAssigned` I had to result to query the node at height 0 to see if the index existed back then. That works but it adds special cases which is never a good thing.

Ideally, the genesis block would have resulted in `IndexAssigned` events but I guess it's too late for that.

**Comment by shawntabrizi** [comment]
@alecalve there used to be events in genesis, but it was removed because it added a huge ton of bloat to the first block.

Imagine that every user that has a genesis balance would emit the following events:

* New account created
* Balance transfered
* total issuance updated
* etc...

Then on top of that, events for all the indexes, and then events for any other genesis state. We noticed actually a significant performance issue because of this, so we opted to have events only fire starting after the genesis state.

So yes, there is kind of a "special case here", but that i would think to be pretty normal for any kind of genesis state. You can imagine other parts of the genesis state which would not emit an event at all, and you might need to discover in this way only. So I think this kind of split logic between genesis state and the rest of the blocks is the right practice.

**Comment by shawntabrizi** [comment]
feel free to reopen if there is more to talk about
