### ISSUE TITLE
Support sending and storing multiple Justifications per block

### ISSUE THREAD

**Issue by octol** [paritytech/substrate#7556]
For bridges and BEEFY it will be useful to be able to send and store multiple `Justifications` per block. That is, we want to change
`Justification = Vec<u8>` to `Vec<(ConsensusEngineId, Vec<u8>)>`.

Probably we would keep the protobuf schema the same (`Vec<u8>`), but we might want to evolve the schema to handle this change gracefully

**Comment by tomaka** [comment]
When it comes to changing the protocol, there are three possibilities:

- We silently change the meaning of the `justification` field, in which case older clients will not be aware of the change in meaning, and try parse "new" justifications and fail.
- We add a new field to the schema. Since both `justification` and this new field would be optional, it would be possible to fill one or the other or both. Older clients will simply ignore the new field. If the current `justification` field is empty, older clients will think that there is no justification.
- We change the protocol version. Before the actual request, a protocol name is negotiated, and it is thus possible to support both a protocol named `/dot/sync/2` (which is the name of the existing one) and a protocol named `/dot/sync/3` which would support multiple justifications. Older clients would request `/dot/sync/2`, in which case the listening side has to answer with one justification only.

If we want to keep backwards compatibility, there is the question of what to do if a block contains multiple justifications. Whatever we do on the network layer, older clients will only ever assume one justification only.

**Comment by octol** [comment]
Thanks for the feedback :)

Btw you mention your favourite being option 3, but added a forth option in an edit. Sorry just to confirm, is it the old 3 or new 3 that you're referring to?

**Comment by tomaka** [comment]
The new 3!

**Comment by burdges** [comment]
I just assumed we'd do 1 but okay. :)

**Comment by octol** [comment]
With #8266 merged we can probably close this
