### ISSUE TITLE
noteFinalityStalled doesn't do anything when your network never finalises blocks

### ISSUE THREAD

**Issue by drewstone** [paritytech/substrate#7603]
We've been struggling to finalise blocks on Edgeware over our last few upgrades and especially since [merging this PR](https://github.com/hicommonwealth/edgeware-node/pull/141).

In our last upgrade, we were able to execute noteFinalityStalled which seems to only have ushered in a new authority set and nothing else, no fix to the finality process, quite useless for our current issue. Beyond that, it's quite unclear why we're still having these issues after many updates to the node and runtime.

Looking into bringing the forced finality feature back while we continue to do more investigating, it appears that the trait is also removed upstream in Substrate now, since the finality tracker has been removed entirely.

- Are there other recommended ways for using that functionality in another location?
- Are there other ways to jumpstart finality beyond bringing that feature back (and holding our version behind master)?

**Comment by bkchr** [comment]
CC @andresilva

**Comment by andresilva** [comment]
The only thing that changed upstream was the removal of the finality-tracker. The only thing this component did was to trigger forced authority set changes automatically (if finality was lagging). Now forced changes need to be triggered manually with `noteFinalityStalled`.

> which seems to only have ushered in a new authority set and nothing else

If this happened then it's done its job correctly and I don't see how having the finality tracker would have led to a different result.

The question should be: why is the authority set not finalizing? The most obvious answer is that 2/3 of the voters are not actually voting (could be because they are offline or because of some bug). I suggest you use the RPC `grandpa_roundState` to figure if any authorities at all are voting, and if some are missing votes then figure out who they are and if they are actually online.

**Comment by drewstone** [comment]
@andresilva so this sounds like a client issue rather than runtime?

**Comment by andresilva** [comment]
Looking at telemetry for Edgeware it seems that a lot of nodes are not on the latest finalized block (#3820124 vs. #3138297). Since you were already using forced changes I think this could be related to a bug that was fixed recently and isn't in 2.0 I think (https://github.com/paritytech/substrate/pull/7321). Any node that was affected by this bug (i.e. isn't on the latest finalized block) will need to resync with the fix.

Either way, as I said above the way to actually figure out what to do is to know if any validators are voting at all, and in case some aren't to figure out why they aren't doing it (are they online? are they on the latest finalized block?). This can be done with the `grandpa_roundState` API.

**Comment by drewstone** [comment]
Interesting! I hadn't looked at telemetry in a day. Will keep an eye out and instruct others to resync and update.

**Comment by andresilva** [comment]
Finality seems to be working again in the Edgeware chain.
