### ISSUE TITLE
Equivocation

### ISSUE THREAD

**Issue by akaryaginUSETECH** [paritytech/substrate#7664]
**Description**

Equivocation will not occur unless node has been restarted 

**Steps to Reproduce**

Validators must be in separate VMs 

start first validator with config 

./node-template \
  --base-path /tmp/alice \
  --chain local \
  --alice \
  --port 30333 \
  --ws-port 9944 \
  --rpc-port 9933 \
  --node-key 0000000000000000000000000000000000000000000000000000000000000001 \
  --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' \
  --validator

start second validator with config 

./node-template \
  --base-path /tmp/alice \
  --chain local \
  --alice \
  --port 30333 \
  --ws-port 9946 \
  --rpc-port 9934 \
  --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' \
  --validator \
  --bootnodes /ip4/10.211.55.11/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp

**Expected vs. Actual Behavior**

Expected: to get warning about equivocation

Actual: No warning no matter how long 

**Environment**

- Operating system:
        Parallels VM
        Host - MacOS
        Guest - Ubuntu
- Template version/tag: v2.0.0
- Rust version (run `rustup show`): 

Default host: x86_64-unknown-linux-gnu rustup home:  /home/alexei/.rustup

installed targets for active toolchain

wasm32-unknown-unknown
x86_64-unknown-linux-gnu
active toolchain

nightly-2020-10-01-x86_64-unknown-linux-gnu (default)
rustc 1.48.0-nightly (ef663a8a4 2020-09-30)

**Logs, Errors or Screenshots**

Unless node is restarted there's no warning 
![Screenshot 2020-12-03 at 01 06 38](https://user-images.githubusercontent.com/74534681/101020171-2272ce00-357f-11eb-95ab-932dca2ff0b6.png)

**Comment by bkchr** [comment]
You don't need to open duplicate issues.

**Comment by andresilva** [comment]
The reason there were no equivocation warnings is that on a local network the two nodes will most likely be voting on the same thing since they will import new blocks almost instantly. After you restart the node you need to sync new blocks and this extra time will probably make you vote on something different, hence creating an equivocation.

You can run both nodes with `-lafg=trace` and you should see log messages like:
`"Announcing block {} to peers which we voted on in round {} in set {}"`, and you can confirm that they are indeed voting on the same thing.

**Comment by akaryaginUSETECH** [comment]
> The reason there were no equivocation warnings is that on a local network the two nodes will most likely be voting on the same thing since they will import new blocks almost instantly. After you restart the node you need to sync new blocks and this extra time will probably make you vote on something different, hence creating an equivocation.
> 
> You can run both nodes with `-lafg=trace` and you should see log messages like:
> `"Announcing block {} to peers which we voted on in round {} in set {}"`, and you can confirm that they are indeed voting on the same thing.

How to enable all possible traces and logs? Which type of chain to choose (local, stageing). I can try again with nodes running on different physical machines

**Comment by andresilva** [comment]
To enable all trace logs you can do it with `-ltrace` but this will generate too much information as you'll see. By default the GRANDPA voters will always restrict their votes up to 2 blocks behind the best block, i.e. if the best block is #10 they will only vote to finalize block #8. This will make it harder for you to cause equivocations, since we are always 2 blocks behind and can re-org in the meantime (hence we will vote on the same thing afterwards). You can change this line https://github.com/paritytech/substrate/blob/master/bin/node-template/node/src/service.rs#L204 to `voting_rule: ()`. This will remove that restriction and voters will always be voting on the latest block which should make it more likely to cause an equivocation.

**Comment by akaryaginUSETECH** [comment]
ok thanks
