### ISSUE TITLE
How to extend a runtime module?

### ISSUE THREAD

**Issue by JKingdom** [paritytech/substrate#767]
Hi:
I'm confused in how to extend a runtime module?
In my mind, I consider "substrate" as a framework as what we do in web developing like "Spring" in java or Asp.net in c# or else. So when the framework module not satisfy our requirements we would extend(or override) the module, just for a project.
For example in our project, which is a parachain using "substrate", due to some feature, we need to extend the balance module, like add some storage fields in `decl_storage!` or some calls in `decl_module!` or some functions in `struct Module<T>`.
Thus, I want to know what is a current way to add some feature to a module.

In my way, there is a simplest way that I can copy the all balances module into my project, and in my project `runtime/lib.rs`, I use my balances module instead of the module in substrate.
However the substrate are updating so quickly, It's stupid that always coping files.
So I figure out a way like this:
1. create a project, which would be a **sub git module** in my project.
2. git init this project, and set the git remote as substrate.
3. **only** checkout the `srml/balances` folder as the source code.
4. do my own changes for this project, and also can catch up the newest substrate

Is there any better way to extend a module?

**Comment by gavofyork** [comment]
If balances doesn't do what you want, there are two approaches:
- Write your own `balances` module, copying and pasting code as necessary. This gives you the most freedom, is the least amount of work but means that without continuous merging you'll quickly become incompatible and lose an new functionality delivered in the module.
- Implement a second module that contains the additional logic and functionality and which requires and uses `balances`. This is what `staking`, `treasury` and `contract` modules do. If you need to alter the internal logic of `balances`  substantially, then you'll need to introduce appropriate hooks into the `balances` module (for example, see `OnFreeBalanceZero`, which is how the `staking` and `contract` module "extend" the `balances` module so that each account has other associated items that get deleted along with the account). If you do need to extend `balances` in such a way, then you can chat to us in the `substrate_technical` riot channel to advise and submit a PR to the substrate modules repo.

**Comment by JKingdom** [comment]
thank you very much!
I did a lot of trials yesterday, and figure out a way like this:
we all know that the substrate provide a lot of runtime modules like `balances`, `staking`, `contract` and so on. On the other hand, if some one want to extend a module, in fact the requirements could divide into two type:
1. add more feature to the module, but not change the origin module logic, for example we need to add some storage to `balances` module.
2. modify origin module logic, for example, we need our own staking logic, or we have to modify some part of the `staking` module.

and  on the other hand, the all substrate module can also divide into two type depending on the dependency relationship:
1. the module is depended by other module, for example, `balances` is depended by `staking`, `treasury` and `contract`.
2. the module is not depended by other module(is the leaf of the module dependency tree), for example, the `staking` module is not depended by other module.

and then if we want to extend a module, first we should decide if we need to modify the module logic:
1. if we do not need to modify the logic, what we need to do is to create a new module like the second point that gavin wood said on the upper, "Implement a second module that contains the additional logic and functionality and which requires and uses balances. "
2. if we need to modify the logic:

    - the module is the first type that is depended by other modules on the upper like `balances`, we need to do like the first point, write own module, but not enough. the modules depends on the `balances` also need to be copied to own, like `staking`, `treasury` and `contract`, due to the macro `construct_runtime!` in the runtime/lib.rs
     - the module is the second type that is not depended by other modules like `staking`, we just need to do like the first point, write own module is enough.

That's all

**Comment by gavofyork** [comment]
There may be a third way, too. Technically only the *configuration trait* forms the dependency graph. So the `treasury` module itself is not dependent on the `balances` module but rather only the `treasury` trait is dependent on the `balances` trait.

This means that you can create a completely new module, using the exact same configuration as the `balances`
