### ISSUE TITLE
DKG and Randomness Beacon pallets

### ISSUE THREAD

**Issue by mike1729** [paritytech/substrate#7820]
Together with my colleagues, we implemented a pallet for Distributed Key Generation (DKG) and a randomness beacon pallet using keys generated by the DKG. Our work was founded by [a web3 grant](https://github.com/w3f/General-Grants-Program/blob/727a960f3965c07ba6cc51722d499d27328cdce9/grants/speculative/Threshold%20BLS%20Randomness%20Beacon%20for%20Substrate.md).

[Here](https://github.com/Cardinal-Cryptography/substrate/tree/randomness-beacon-m3/frame/dkg) is a description of the architecture of the dkg pallet, [here](https://github.com/Cardinal-Cryptography/substrate/tree/randomness-beacon-m3/frame/randomness-beacon) of the randomness beacon pallet, [here](https://docs.google.com/presentation/d/1DGCx_bqurKBfJUW28vkxBNHo_1mRvSfsqLqcEt-rgbU/edit#slide=id.gaefe3aef82_0_173) are some slides explaining a high level overview of both pallets, and [here](https://github.com/Cardinal-Cryptography/substrate/blob/randomness-beacon-m3/RB-Documentation/Documentation.md) are some benchmarks results and further details on how to use the pallets.

This is our first-time working with substrate, so while we did our best to learn it from your excellent docs, by reading your high quality code, and asking questions on riot, we are sure that our architecture and code is not perfect, and would love to fix/adjust whatever you believe is missing or not optimal.

The main question is however, whether you are at all interested in merging such pallets. Possibly just the DKG pallet? (There is no point in merging just randomness beacon as it needs DKG for the setup.)
If you would be interested in merging, but require us to make even substantial changes, then we would be more than happy to introduce them.

I assume you are well aware of the benefits of such general purpose pallets as DKG and randomness beacon but let me recall some of the most popular ones: threshold cryptography, privacy preserving messaging services, e-voting protocols, gambling and lottery services.

**Comment by bkchr** [comment]
I think from a high level we don't want to merge external pallets. The problem with that is that it increases our maintenance load and that is already relative high.

However, I think that we can find someone who can give you some tips on what can be improved.

CC @shawntabrizi @danforbes

**Comment by danforbes** [comment]
I have conferred with @shawntabrizi on this topic and we are in agreement with @bkchr; in fact, I would amplify his statement by adding that we intend on _minimizing_ the number of pallets in the Substrate `frame` directory. The mental model I would assume may be similar to C++, where the `std` library provides a relatively narrowly defined set of capabilities while making room for community-maintained "add-ons" like [Boost](https://www.boost.org/) (I don't know if there would ever be an exact analogue for Boost because it's pretty fully-featured, but think in terms of individual pallets providing those types of capabilities). Community-maintained FRAME pallets may be exposed via package manager-type services, such as [Substrate Marketplace](https://marketplace-staging.substrate.dev/) (still in staging). The [Open Runtime Module Library (ORML)](https://github.com/open-web3-stack/open-runtime-module-library) is a great example of a set of community-maintained pallets, and in fact may be the closest thing we have to Boost. You may even want to consider transferring this Issue to the ORML repo, to see if its maintainers would be interested in including your pallet(s). For now, I am going to close this Issue; please feel free to reopen it if you believe I have closed it in haste, or add comments if anyone disagrees w/ anything I've said. Thank you very much for your interest in contributing, @mike1729 🙏🏻 I would also be very happy to list your pallet(s) on [Awesome Substrate](https://github.com/substrate-developer-hub/awesome-substrate) 😎 if you'd care to make a PR.

**Comment by mike1729** [comment]
Thanks for the exhaustive answer. If you consider substrate as `std` lib in C++ then indeed it makes little sense to integrate external pallets that don't provide basic functionality.

We'll try our luck in ORML then and will make a PR to the awesome list:)  Thanks!

**Comment by burdges** [comment]
As an aside, I'd suggest basing production randomness beacons off some future production version of https://github.com/kobigurk/aggregatable-dkg which implements https://eprint.iacr.org/2021/005.pdf

**Comment by burdges** [comment]
I only looked superficially but https://github.com/Cardinal-Cryptography/substrate/blob/randomness-beacon-m3/primitives/dkg/src/threshold_signatures.rs does not look like Feldman's VSS scheme.
