### ISSUE TITLE
Expose SignedExtension's implications on transaction construction in metadata.

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#7850]
While discussing how to build transactions with the least dependency on substrate packages with @emostov: 

The metadata already exposes something like this: 

```
extrinsic: {
        version: 4,
        signedExtensions: [
          CheckSpecVersion,
          CheckTxVersion,
          CheckGenesis,
          CheckMortality,
          CheckNonce,
          CheckWeight,
          ChargeTransactionPayment,
          PrevalidateAttests
        ]
 }
```

What it does not expose is what implications these extensions have on the extrinsic construction. Given that (to the best of my knowledge) the aforementioned implication is always either one of: 

1. Cause some data to be appended to the to tx payload
2. Cause some data to be appended to the signed_payload
3. (or simply no effect)

I assume we can extend the metadata to expose this information as well. Unless if `SingedExtension` trait changes significantly, this should be stable and will make a lot of people building transactions offline happy. 

```
extrinsic: {
        version: 4,
        signedExtensions: [
          { name: 'CheckWeight', data: 'None', signed_data: 'None' },
          { name: 'ChargeTransactionPayment', data: 'Balance', signed_data: 'None' },
          // ------------------------------------------^^ This type must be defined elsewhere in the metadata though
        ]
 }
```

cc @thiolliere @bkchr

**Comment by bkchr** [comment]
I'm not convinced by this request.

What does it brings you when you know that `data` == `Balance`? IMHO that doesn't tell you anything. 

After we added that, someone will come with the idea, hey what is the algorithm for X to add it to the signed extensions? Could we not expose this via metadata? This is some never ending rabbit hole.

The idea behind adding the signed extensions to the metadata was that each extension has a known implementation. And we just expose which signed extensions the runtime is using. The user facing side just needs some sort of registry of known extensions where it looks up a particular extension.

**Comment by kianenigma** [comment]
> What does it brings you when you know that data == Balance? IMHO that doesn't tell you anything.

But isn't this how the storage definitions work metadata as well? Somewhere in the metadata of a pallet, it is defined that `Balance = u128` and therefore anywhere you see `Balance` you can replace it. Although, I am aware that I am making an assumption here: 

That all the types that signed extensions need in their data or signed_payload, have types that are already defined in some pallet's storage item. Else that type will be undefined and need to be declared as well. 

> Could we not expose this via metadata? This is some never ending rabbit hole.

I get the point and mostly agree. What I want to point out is that there's spectrum here, and our definitions of what "should" and "should not" be provided to the user can differ, and is very fuzzy tbh. In this case, one end of the spectrum being "our ease" and the other end "user-friendliness". I could have argued the same 2 years ago and convince you that you don't need to expose pallet storage types via metadata, rather just their names, and an external repo should maintain them, right? But then we opted to make things easier for the user. I wonder why not now? 

> The user facing side just needs some sort of registry of known extensions where it looks up a particular extension.

@emostov for your case it might be worth at giving this a shot then :)

**Comment by bkchr** [comment]
> But isn't this how the storage definitions work metadata as well? Somewhere in the metadata of a pallet, it is defined that `Balance = u128` and therefore anywhere you see `Balance` you can replace it. Although, I am aware that I am making an assumption here:

Nope that is not defined, at least for now and that brings some huge problems ;) That should be solved by scale-info.



> I get the point and mostly agree. What I want to point out is that there's spectrum here, and our definitions of what "should" and "should not" be provided to the user can differ, and is very fuzzy tbh. In this case, one end of the spectrum being "our ease" and the other end "user-friendliness". 

Yeah, it is true that the barrier is relative fuzzy. The point is that we could put much more stuff into the metadata, like how are the fees calculated, but this is really a never ending story. There will always be some stuff you need to be aware of from the application side. You can also have your own signed extensions and if you just know that some custom signed extension takes a `Balance`, would not help you for anything. 

> I could have argued the same 2 years ago and convince you that you don't need to expose pallet storage types via metadata, rather just their names, and an external repo should maintain them, right? But then we opted to make things easier for the user. I wonder why not now?

We already currently maintain a type definition per chain, because we only see names for types and have no fucking clue what they are actually :D In the future this will also hopefully be solved by scale-info. However for storage types this is a little bit different, because you don't need to know any algorithm for this. When the user wants to read from any random chain a storage field that has as type `Balance` and you can generate a type info for that, you will be able to decode it and show it as a string. Yes, we still need more metadata to say for example that a certain type is a `Balance` and some other type is `X`. Something for the future. However, for all this stuff we don't need any knowledge on how to calculate the value that should be added to the transaction.

**Comment by bkchr** [comment]
> > The user facing side just needs some sort of registry of known extensions where it looks up a particular extension.
> 
> @emostov for your case it might be worth at giving this a shot then :)

polkadot-js is doing the same and since we have support for it, I know that @jacogr life is much easier in this aspect :D

**Comment by jacogr** [comment]
The api has a registry for known extensions which contains the payload-only and transaction types. (That is what gets used to build the extrinsic against what the metadata defines)

**Comment by kianenigma** [comment]
I wonder of #8370 would help with this? If the `data` field of each extension (i.e. what needs to be encoded) is already described elsewhere in the metadata formally, that would solve the issue, right?

**Comment by bkchr** [comment]
No this will not be solved by the linked issue. You still need a way to provide semantic information on how the data is fetched for these types.

Imo this is already solved by the identifiers of the signed extensions.

**Comment by kianenigma** [comment]
My opinion is that we don't need to tell the semantic information, and it is the responsibility of the offchain user to know that. But providing some types to help is better than nothing. 

Although you can say knowing the type is also their responsibility, I see the point in that as well :D

**Comment by kianenigma** [comment]
> My opinion is that we don't need to tell the semantic information, and it is the responsibility of the offchain user to know that. But providing some types to help is better than nothing.
> 
> Although you can say knowing the type is also their responsibility, I see the point in that as well :D

Thinking a bit further, I think there's no way around this, and Basti is right that even if we provide the type, the semnatics of how to fetch it still needs to be hardcoded in each application, so they might as well hardcode the whole thing. 

What comes to mind is maybe an RPC call that is like a _payload builder/helper_, to which you give a call, and some typed parameters to build the entire payload from. This is slighly better, as that RPC is at least somewhat typed, and you need to know which types of data you need to pass in.

But even this won't solve the main objective of this issue, which is to allow offline signing, with depending only on metadata, not potentially some unknown node. 

I won't close this yet, but kinda see that this is a deadlock.

**Comment by bkchr** [comment]
> What comes to mind is maybe an RPC call that is like a _payload builder/helper_, to which you give a call, and some typed parameters to build the entire payload from. This is slighly better, as that RPC is at least somewhat typed, and you need to know which types of data you need to pass in.

And then you got a chain that supports tips, so the rpc needs to gets the tip passed. Then there is a chain that doesn't has tips. (tips are clearly just an example here and this is entirely chain dependent)

**Comment by emostov** [comment]
> What comes to mind is maybe an RPC call that is like a payload builder/helper, to which you give a call, and some typed parameters to build the entire payload from. This is slighly better, as that RPC is at least somewhat typed, and you need to know which types of data you need to pass in.

This functionality sounds awfully close to some talk of adding an endpoint to sidecar (or making a new service. The endpoint would build a transaction for you given the call, call params, and signing info, then take your signature and give you back a tx to submit. ([see discussion here](https://github.com/paritytech/substrate-api-sidecar/issues/419)). This way you just only need to be able to pass in some JSON info and implement the signing crypto, but all other details of creating the tx could be abstracted by the service.

IMO the primary hurdle to something like this is limiting MIM attacks where the attacker gets you to sign there payload because you do not have the ability to decode it and check. You could implement some system like having a shared secret with the service, but requires an attentive and thoughtful sysadmin.

**Comment by kianenigma** [comment]
seems like we're fine with just putting the name of the extension there, and asking the 3rd party client to just infer the rest. Not happy, but will close.
