### ISSUE TITLE
Allow to use path in construct_runtime.

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#8085]
Currently construct_runtime only allows to have an identifier for the path of the pallet, this result in code like this:
```rust
use pallet_session::historical as pallet_session_historical;
construct_runtime!(
	...
	Historical: pallet_session_historical::{Module},
);
```
instead we should be able to do stuff like this:
```rust
construct_runtime!(
	...
	Historical: pallet_session::historical::{Module},
);
```

Maybe `impl_outer_*` should be reimplemented in procedural macro so that this issue is easier to do.
Or we can make construct_runtime note using them and instead use its own code (which shouldn't be a lot of code actually, but would be great to share code generation for stuff like `impl_outer_inherent`).
Or maybe we can just handle path in `impl_outer_*` but this is probably tricky and doesn't worth the pain.

**Comment by bkchr** [comment]
We should deprecate these old macros with the old decl_module macro.

**Comment by bkchr** [comment]
And rewrite them as a procedural macro.

**Comment by KiChjang** [comment]
So, getting the old macros to work with paths, while seemingly straightforward and simple, is in fact not, due to the limitations of what syntactical constructs can be appended to path fragments, i.e. if I matched a `$module:path` fragment, we are not allowed to generate the following code:

```rust
$module::<Runtime, Instance>
$module::Type
$module::path_segment::Type
$module::function
$module::constant
```

In summary, appending additional path segments during macro expansion is prohibited. So in order to get paths working with the overall `construct_runtime` macro, the path of least resistance does seem to be, at the very least, rewriting `impl_runtime_metadata`, since this is the only macro so far that needs to be aware of the path of where the pallet is located.
