### ISSUE TITLE
Conditional compilation doesn't work with new `pallet::storage` macro

### ISSUE THREAD

**Issue by shaunxw** [paritytech/substrate#8102]
With a conditional compilation attribute used on runtime storage type defined via `#[pallet:storage]`, for example:

```
#[cfg(not(feature = "disable-tokens-by-owner"))]
#[pallet::storage]
#[pallet::getter(fn tokens_by_owner)]
pub type TokensByOwner<T: Config> =
	StorageDoubleMap<_, Twox64Concat, T::AccountId, Twox64Concat, (T::ClassId, T::TokenId), (), ValueQuery>;
```

Compiling with `disable-tokens-by-owner` feature would fail with error:
> error[E0412]: cannot find type `TokensByOwner` in this scope
   --> orml/nft/src/lib.rs:142:11
    |
142 |     pub type TokensByOwner<T: Config> =
    |              ^^^^^^^^^^^^^ not found in this scope
error: aborting due to previous error

The above example code could be found in [`orml_nft`](https://github.com/open-web3-stack/open-runtime-module-library/blob/8c150f34a5b305103438e93337e1b9e7868dd1f3/nft/src/lib.rs#L141-L145)

**Comment by shawntabrizi** [comment]
Do you mean to not have `not` in the attribute?

Currently, that type will exist for anything that is NOT that feature.

**Comment by thiolliere** [comment]
but it didn't work with old `decl_storage` either, no ?

This is because the conditional compilation happens after the macro expansion, so if we want to support conditional compilation we have to parse them in some way or to have a wrapper macro which does it.

### 1- parse conditional compilation

Something I could see is that pallet::storage could parse for attribute like `cfg` and then copy this attribute for the prefix ident generated. Same for pallet::call, we could parse for such attribute on calls, and then copy this attribute on the call variant and call dispatch implementation. But all those stuff have to be manually implemented.
(I guess the best would be to have a newly introduce attribute for when the macro allows it, like `#[pallet::cfg(...)]`)

### 2- use a wrapper macro

we can introduce some wrapper function. Maybe we can create a macro which does take some input with `cfg` attribute and result in each different possible output with only one `cfg` at the top:
```rust
#[do_cfg_up_front]
#[pallet]
mod pallet {
	#[cfg(feature = "abc")]
	#[pallet::storage]
	type Foo;

	#[cfg(not(feature = "abc"))]
	#[pallet::storage]
	type Bar;
}
```

```rust
#[cfg(feature = "abs")]
#[pallet]
mod pallet {
	#[pallet::storage]
	type Foo;
}

#[cfg(not(feature = "abc"))]
#[pallet]
mod pallet {
	#[pallet::storage]
	type Bar;
}
```
But this might be very tricky do to or it might even be impossible actually.

**Comment by shaunxw** [comment]
> Do you mean to not have `not` in the attribute?
> 
> Currently, that type will exist for anything that is NOT that feature.

I mean while building with `--features=disable-tokens-by-owner`, that type should not exist, and everything would be fine. But instead there is a compiling error from the type definition.

**Comment by shaunxw** [comment]
> but it didn't work with old `decl_storage` either, no ?

Actually It works with old `decl_storage`. ([This](https://github.com/open-web3-stack/open-runtime-module-library/blob/098811dac6a49e559f553458208cf3e5fd26fecb/nft/src/lib.rs#L120-L122) is the code before pallet attribute macro migration.)

Syntax in solution 1 looks more straightforward and it's doable, IMHO the manual work worth it. :]

**Comment by thiolliere** [comment]
> > but it didn't work with old `decl_storage` either, no ?
> 
> Actually It works with old `decl_storage`. ([This](https://github.com/open-web3-stack/open-runtime-module-library/blob/098811dac6a49e559f553458208cf3e5fd26fecb/nft/src/lib.rs#L120-L122) is the code before pallet attribute macro migration.)
> 
> Syntax in solution 1 looks more straightforward and it's doable, IMHO the manual work worth it. :]

If I read correctly, decl_storage is simply discarding the attribute and generate the storage anyway.
I agree manual work for such stuff seems the good direction
