### ISSUE TITLE
Multisig pallet ignores extrinsics errors

### ISSUE THREAD

**Issue by anstill** [paritytech/substrate#8247]
When I perform an extrinsic transaction on behalf of multisig account its ignores any Substrate Errors after final approval. 

I expect that errors will be submitted after final approval if the payload contains an invalid date or in other cases. 

Steps to reproduce: 

1. Create multisig account wuth threshold 2
2. Submit some extrinsic on behalf of this account with invalid data signed by one of the accounts presented in multisig account 
2. Submit the same extrinsic with the same data but signed by another account. 

Actual result: 
Substrate doesn't submit any errors and just showed the event that multisig has been executed.
<img width="349" alt="Screen Shot 2021-03-02 at 18 42 27" src="https://user-images.githubusercontent.com/16906128/109675150-93c71a80-7b88-11eb-81e3-9601697bd2b5.png">

Expected result: 
Error submitted
<img width="344" alt="Screen Shot 2021-03-02 at 18 54 43" src="https://user-images.githubusercontent.com/16906128/109675375-ca9d3080-7b88-11eb-84d0-381830126c0c.png">

This could probably be a UI issue of https://github.com/polkadot-js/apps I'm not sure.

**Comment by bkchr** [comment]
The extrinsic is only executed after it was approved, so you can not know if is successful when the first account approves it.

**Comment by andrew-polyansky** [comment]
@bkchr Yep, I understand that. I mean after final approval, when threshold reached. In this case after second approval when extrinsic is expected

**Comment by bkchr** [comment]
So what should be changed than?

**Comment by andrew-polyansky** [comment]
@bkchr That extrinsic will be executed after final approval. I understand why I can't know if is successful when the first account approves it. However, I want to know if there are any errors after the final execution when extrinsic is executed. 

It works well if an extrinsic call doesn't contain any error. In this case, extrinsic will be successful, and the corresponding event will be showed. However, if the extrinsic call contains any error I can't know about it, because receive only the event that `MultisigExecuted`.  

What's wrong behavior because extrinsic was actually executed with errors.

**Comment by bkchr** [comment]
https://github.com/paritytech/substrate/blob/5f056830a85f33c5628e6a3fac5c8e3270514bfe/frame/multisig/src/lib.rs#L182

The event itself contains the result of the inner call. The multisig call itself was successful, so the result is correct. To know the result of the inner call, you need to check the event.

I never used this, but if that is your problem, this is indeed some UI improvement.

**Comment by xlc** [comment]
The approve action successes the event is success. Otherwise how will you distinguish between failed approve vs failed execution?

This is same for proxy / batch.
