### ISSUE TITLE
Remove Offence delay API

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#8343]
With https://github.com/paritytech/substrate/pull/8113 being merged, we won't need to delay offences anymore. We can remove the `can_report` api from `OnOffenceHandler`, and there's a small queue in the pallet-offence that keeps queued Offences, and that needs to also get removed.

**Comment by hirschenberger** [comment]
I'd like to do it.

**Comment by kianenigma** [comment]
We're planning to use this task for an internal interview process, could you wait until next week please? I'll keep you posted.

**Comment by hirschenberger** [comment]
Oh, I'm nearly finished. May I get the job? ;-)

**Comment by shawntabrizi** [comment]
@hirschenberger if you are serious about trying to get a job at Parity, please apply online here: https://www.parity.io/jobs/

We are actively hiring in a number of areas :)

**Comment by Lohann** [comment]
@kianenigma @shawntabrizi
WIP PR related to this issue:
https://github.com/paritytech/substrate/pull/8414

Just to check if my reasoning is correct:
 1 - If I assume that **DeferredOffences** is empty or its data is not important, I just have to kill the storage
 2 - If all cached offences have to be emitted before clean the storage, in this case it can a be trick because we don't know how big the queue is, so if it is too large will not be possible to migrate everything using `on_runtime_upgrade` hook without exceeding the weight limit.

To address the second case, I'm calling the migration in batches on `on_runtime_upgrade` and `on_initialize` hooks, but I would like to check if I'm in the right path before starting fixing the unit/benchmarks tests.
