### ISSUE TITLE
Add RPC to query a contract's custom sections

### ISSUE THREAD

**Issue by athei** [paritytech/substrate#8423]
WebAssembly allows to embed arbitrary data into a wasm module as a so called [custom section](https://webassembly.github.io/spec/core/binary/modules.html#custom-section). This data is transparent to the contracts module and deployed as-is to the chain. It is not parsed at all.

This information could be used by contract languages to embed metadata than can be used by UIs or other off-chain actors. One notable example is embedding the hash of the ABI file so that UIs can be sure to have the correct ABI file as long as they trust the contract.

In order to make use of this data it has to be exposed to the off-chain world (to javascript). A new RPC that queries the contents of any custom section should be enough. The contents and semantics are of no concern to the contracts module and should be implemented by contract languages just like the ABI file itself. WebAssembly defines the custom section names as utf8 strings.

```rust
fn query_custom_section(name: &[str]) -> Result<Vec<u8>>;
```

cc @Robbepop

**Comment by atenjin** [comment]
interesting... must of time, the custom section is used for name section. but on chain contract does not contain any name section for `cargo-contract` optimization level does not contains this part , otherwise the wasm will be very large. 

If the custom section is used for the example "embed metadata hash", I think this rpc maybe useful. But I do not think the metadata hash could be embeded into the wasm custom section, for if inject the wasm custom section, the code hash will be changed, then the code hash in metadata is not same as the embeded wasm code hash. If you guys decide to agree on a protocol which like cargo-contract, all 3rd parities and pallet-contracts all decide to treat the "embed metadata hash" section is needed to be removed when calculate code hash, I think it's very confuse for other people to understand this thing...

I think a better way is to store the metadata hash in a storage in `pallet-contracts`, not store it in the wasm custom section.

Thus, all in all, I do not figure out how to use this rpc... maybe it could be used in other case.

It seems that this idea is from your part @Robbepop , what is your opinion?

**Comment by athei** [comment]
> But I do not think the metadata hash could be embeded into the wasm custom section, for if inject the wasm custom section, the code hash will be changed, then the code hash in metadata is not same as the embeded wasm code hash.

Not entirely sure what you mean but breaking those "hash cycles" is usually accomplished by excluding certain fields by defining them as "all zeros" when calculating the hash. For example, the code_hash embedded in the metadata would be defined with "metadata hash" as all zeros in the custom section.

**Comment by atenjin** [comment]
> > But I do not think the metadata hash could be embeded into the wasm custom section, for if inject the wasm custom section, the code hash will be changed, then the code hash in metadata is not same as the embeded wasm code hash.
> 
> Not entirely sure what you mean but breaking those "hash cycles" is usually accomplished by excluding certain fields by defining them as "all zeros" when calculating the hash. For example, the code_hash as embedded in the metadata json would be calculated with the "metadata hash" being set to all zero or removed.

yes, what I mean is this "hash cycles". And what I say in following is the method you mentioned, excluding this field when calculate hash. But I do not thing this is a good way, for excluding this field will become a potential rule for all people, not just for `pallet-contracts`, but also for all 3rd parities. This is confuse for all people.

**Comment by athei** [comment]
It would be defined by the ABI together with all the other rules. It is not defined by `pallet-contracts` but by the user space as the rest of the ABI.

Why would that any more confusing as for example how the call identifier of ink! or ask! functions is encoded? @Robbepop  what do you think?

**Comment by atenjin** [comment]
If the code_hash is just calculated by hashing directly, any 3rd parities could just calculate it directly. It's simple and directly. But if it has this rule, then the 3rd parities need to bring in the wasm feature to decode the code, remove/override this part and encode, then calculate hash. 

Generally speaking, all calculations of the hash of a piece of code are performed directly, such as obtaining a hash of an execution file for verification. Therefore, most people may not notice that special processing is required before hash calculation. This is the hidden rule I am talking about, and it will be confusing. If it is just for the introduction of this feature that all third-party tools need to understand this rule and accept it, I think the price/performance ratio is not high. To do this, it is better to directly add a storage to store the hash of metadata in pallet-contracts, while this storage is optional.

**Comment by athei** [comment]
> If the code_hash is just calculated by hashing directly, any 3rd parities could just calculate it directly. It's simple and directly. But if it has this rule, then the 3rd parities need to bring in the wasm feature to decode the code, remove/override this part and encode, then calculate hash.

I think we can define it in a way that only compilers like cargo contract need to deal with the wasm and they need to do it anyways:

The `abi_hash` is calculated first over the ABI json without the `code_hash`. Then the `code_hash` is calculated over the wasm blob which already includes the final `abi_hash`.  This leaves the `code_hash` defined over the whole wasm. Only when verifying the `abi_hash` field needs to be removed from the **json** but this should be reasonable.

> To do this, it is better to directly add a storage to store the hash of metadata in pallet-contracts, while this storage is optional.

This would require adding a new set  of `instantiate` dispatchables that accept something like an `associated_data` argument. I really like to keep those things to the userspace. Letting the contracts define the semantics.

**Comment by yjhmelody** [comment]
>Only when verifying the abi_hash field needs to be removed from the json but this should be reasonable. 
how to remove？？If the fields are disordered？ and json is text，json lib can add whitespace arbitrarily.

**Comment by yjhmelody** [comment]
And user still cannot know the final abi_hash is correspond to the metadata.json because it changed

**Comment by athei** [comment]
I have no idea what you are talking about. Can you give more constructive feedback than thumbs down?

**Comment by yjhmelody** [comment]
The wasm code and abi hash must be separated.
The third party wants to get the final metadata hash instead of the temporary metadata abi, because it may be forged. Of course, cargo-contract can simply remove the code_hash from the metadata.json and then base it on the new metadata.json To generate `abi_hash`, but the user must use the new metadata.json, but the hash value of the new metadata.json is not on the chain. It is assumed here that the two times of `metadata.json` generated by the compilation process are A/B before and after, and the two times of `wasm` generated by the compilation process are code1/code2.

Why must it be the new metadata.json? Because metadata.json may need to be updated (but the code wasm is not updated, for example, metadata.json needs to update the docs field), then this obviously requires wasm code and abi_hash to be stored naturally separately. Because the current design is that the update of metadata.json will affect wasm code_hash.

More importantly, what you describe is all the functions that the contract language itself should provide, and you don't let the chain help. Then the method you describe here can't restrict other contract languages ​​(except ink), that is, there is no specification.

Third, the current metadata.json is based on json. Generate code_hash for the new wasm code 1 and fill it in metadata to generate metadata B, then the so-called
`Only when verifying the abi_hash field needs to be removed from the json but this should be reasonable.`What exactly did it do? Just removed this `abi_hash`? The json text is very random. After I remove it and regenerate the metadata.json, how can I ensure that the text is equivalent to metadata A? Of course, you can also guarantee that, then you have to have requirements for the json library, such as ensuring a certain order, but Obviously this will be more troublesome.

The third party uses metadata B, but the hash of metadata A is stored on the chain. In fact, third parties have no simple way to verify whether they correspond.
First of all, the third-party verification logic here should be standardized and as simple as possible.

**Comment by yjhmelody** [comment]
The idea you mentioned makes the compilation phase of a language very complicated, which will seriously hinder other languages as smart contract languages. And what you describe is still very ambiguous. I don't think that developers of other smart languages don't need to communicate with you in a lot of details if they want to achieve what you say.

**Comment by athei** [comment]
> And what you describe is still very ambiguous. 

This issue is about providing an RPC that returns data placed inside custom sections. The metadata thing was merely an example but is in complete control of the users of pallet_contracts. I provide mechanism not policy. It is merely a way to attach auxiliary information to a contract that can be queried cheaply.

This means that your post is actually off topic here. It would need to go towards the ink! authors if they decide to use the RPC in this way. But let me break down your text and comment on it anyways. I think you have 3 points there.

1.  You cannot update the metadata after the contract is deployed.

I think this is a valid point. I am not sure if a metadata update is an important use case, though @Robbepop 

2. There is no specification of the metadata.json and hence forming a hash over this is not well defined

The definition of the hash will need to include a proper specification like the ordering of the fields and so on. I don't think this is a problem.

3. It makes the compilation process complicated

Come one.  It is embedding a value into a custom section of a wasm module. That can be easily accomplished with readily available libraries you would be using anyways in your compiler tooling. Also it only has to be implemented once per compiler. I don't think that will "seriously hinder" any language author.


> the chain only needs to provide an rpc to store the metadata hash, then all the troubles just described have disappeared, and all contract languages are consistent, regardless of whether their metadata format is customized or uses the ink standard. 

How would that solve the second point? How does the location where you store the hash influence the viability of metadata customizations?

**Comment by ascjones** [comment]
> I consider this a feature. By being immutable like the contract itself you only need to trust the contract to provide the correct metadata hash. But I also see that this can become a problem when the metadata format evolves. What are your thoughts @ascjones ?

I suppose you could add a metadata version as an additional field for this use case. Client tooling could then handle any forward compatible conversions. Any breaking changes would likely accompany a major `ink!` release anyway, so would require a rebuild/update of the contract anyway. 

That said, as I understand this is just an example use case of this feature and not necessarily something that we are currently planning on doing. Though if we do we would obviously think it through properly.

As a general feature I think it is very good idea to have an RPC to query arbitrary data from custom sections, I assume that having the custom section will not be mandatory so it would not place any immediate burden on any language or tooling targeting the contracts pallet.

**Comment by athei** [comment]
> As a general feature I think it is very good idea to have an RPC to query arbitrary data from custom sections, I assume that having the custom section will not be mandatory so it would not place any immediate burden on any language or tooling targeting the contracts pallet.

Exactly. I think it makes sense to defer this metadata discussion because that is not the point here. We should discuss this once ink tries to make use of this feature.

**Comment by Robbepop** [comment]
> You cannot update the metadata after the contract is deployed.

I see one major pain point with respect to upgradeable smart contracts that use a delegator contract for entry-level messages that simply forwards them to the upgradable contract logic layer.
So if you upgrade the contract layer you won't upgrade the delegation layer but will potentially require new metadata to be associated to the contract as a whole since while the users are targeting the delegator layer the logic layer is the one that actually defines the metadata.

**Comment by yjhmelody** [comment]
I think this is meaningful to provide a rpc to query custom sections, but it has no meaning for metadata hash. Can you point out some benefits? Or the downside of the way I mentioned storing metadata hash?

**Comment by athei** [comment]
I am closing this issue because any information included in wasm blob is essentially non verifiable. The use case we were thinking of is not properly implemented by just including a code hash in the wasm blob as it could be used by a malicious wasm to reference a misleading ABI. For example, naming a `transfer_from` function as `transfer_to`.

What actually needs to be done is making use of deterministic compilation to verify the source code of a contract which will also verify the metadata.

cc @cmichi @achimcc
