### ISSUE TITLE
Enforce arbitrary score-related criteria to election submissions

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#8600]
> This discussion applies to both signed and unsigned submissions. 

We are lacking an absolute measure of solution quality at the moment. In the future, we hope approaches such as #8160 will solve this. So theoretically, if a bug causes all Offchain worker solutions to fails submission, any low-score solution is acceptable. 

A very easy -- yet sensible -- way to prevent this is to put a _governance-controllable_ score-dependent-criteria onchain as a configuration. All solutions must at least fulfil this criteria in order to be accepted. To keep it generic, the API could be as such: 

```
/// Convert an election socre into a bool, saying wether it should be accepted or not.
type ScoreValidation: Convert<RawSolutionOrSolutionScore, bool>;
```

A chain that does not care about this, would simply do: 

```
struct Accept;
impl<T> Convert<T, bool> for Accept { fn convert(_: T) -> bool { true } }

type ScoreValidation = Accept;
```

An open question is what should be the input of the convert: is just the score enough? or the whole 
`RawSolution`? 

A good example here is what kusama's governance is doing; @rrtti can you explain the checks that you guys do prior to increasing kusama's validator count? 

--- 

A related note is that this might increase the chance of an onchain election. We should keep an eye on https://github.com/issues

cc @coriolinus wdyt?

**Comment by coriolinus** [comment]
> put a governance-controllable score-dependent-criteria onchain as a configuration.

I think this is a good idea in principle. We need to ensure the messaging around this is clear: this can be dangerous, and if governance sets this value too high, they can get their chain into a state where no election results are ever accepted. 

> is just the score enough? or the whole `RawSolution`?

We want this function to be cheap, so I want it to be just the score, if possible. However, that depends on the score being independent of the election specifics: if scores vary according to the number of candidates, number of voters, etc, then we need to submit the whole `RawSolution`. That variance doesn't matter as long as it's only a relative number, but it matters a lot if governance can set some absolute floor. I don't know enough right now about how the score is computed to say whether it exhibits this variance or not.

> this might increase the chance of an onchain election

Yes, and we want to have some indication on-chain in that event that an otherwise valid solution was rejected for score as opposed to no valid solution was submitted. Possibly an event is appropriate for this.

If an unsigned election solution is ever rejected for having too low a score, we probably want maximum severity logs saying "this is likely a misconfiguration".

**Comment by kianenigma** [comment]
This is already closed.
