### ISSUE TITLE
pallet-contracts: Gas estimation is too low

### ISSUE THREAD

**Issue by cmichi** [paritytech/substrate#8693]
@athei We thought it's an UI issue at first (https://github.com/polkadot-js/apps/issues/5156, https://github.com/paritytech/canvas-ui/issues/95), but now it seems like a `contracts` pallet bug.

The estimated "max gas value" which the UI's pre-fill for contract calls is for some calls significantly lower than the required gas. So the pre-filling is actually incorrect and the call cannot be executed with the default settings (breaking e.g. our tutorials, which should work with default settings).

## How to reproduce

We've found that at least the ink! examples `delegator` and `contract-terminate` are affected. `contract-terminate` is the easiest to reproduce the bug with. I've attached the contract which can be used for deployment here: [contract_terminate.contract.zip](https://github.com/paritytech/substrate/files/6393496/contract_terminate.contract.zip).

The contract has only one method `terminate_me`, the polkadot-js UI suggests a default `Max Gas Allowed` of 1417, but the contract then fails with `system.ExtrinsicFailed: contracts.OutOfGas`.

It works if the max gas is set manually to 2500.

You can e.g. use the latest [`canvas-node`](https://github.com/paritytech/canvas-node), it has been adjusted to the Substrate `HEAD` just this week. `canvas-ui` is also affected by this.

![screenshot-polkadot js org-2021 04 28-10_51_34](https://user-images.githubusercontent.com/241530/116379622-7c687e80-a813-11eb-8c6a-835711d106e6.png)

For the simple contracts (`flipper`, etc.) the estimation seems to work fine. Those two affected contracts do either cross-contract calls or call `seal_terminate`.

**Comment by athei** [comment]
The issue arises from the fact that sometimes we need to pre-charge some weight that is based on some kind of maximum because we do not know the real size of the operation before performing it. That happens at these two actions:

- Loading a wasm blob from storage
- Reading data from sandbox (contract) memory

The weight is corrected directly after performing those operations but they will fail if the gas limit is too low to allow for this temporary "spike" in weight consumption.

The former reason (loading a wasm blob) is triggered when calling a contract or terminating one. This is why you see it happen on those occasions.

This behaviour leads to a situation where the `gas_consumed` can be lower from the `gas_limit` that needs to be supplied because the latter needs to account for weight spikes.

The fix would be to add another field to the return value like `required_gas_limit` that includes those weight spikes.
