### ISSUE TITLE
Confusing error message when peer ID mixed between relaychain part & parachain part of a parachain node

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#8868]
I am running a parachain local testnet and I am passing bootnodes to allow parachain nodes to discovery each other. But I passed the relaychain peer id instead of parachain peer id to the parachain node. Now I am getting this confusing error message

`
[Parachain] 💔 The bootnode you want to connect to at /dns/parachain-2000-1/tcp/30333/p2p/12D3KooWN6S4KHT2jCs9M84UJgWJ6xLV14QQDWnuBXN4HgFC8dapprovided a different peer ID than the one you expect:12D3KooWN6S4KHT2jCs9M84UJgWJ6xLV14QQDWnuBXN4HgFC8dap.
`

Note that the peer ID in the error message are the same.

cc @tomaka

**Comment by tomaka** [comment]
To add details, the problem here is that the address of the node is the address that we dial.
As of the latest libp2p version, the address that we dial includes the expected `PeerId`.

In other words, with an older version of Substrate, the message would have been `The bootnode you want to connect to at /dns/parachain-2000-1/tcp/30333 provided [...]`, which was less confusing.

**Comment by tomaka** [comment]
Issue still relevant and important.
