### ISSUE TITLE
Hardware performance metrics in telemetry

### ISSUE THREAD

**Issue by emostov** [paritytech/substrate#8944]
In order to better understand the performance characteristics of nodes in a particular network (especially validators), it would be helpful to have some indication of their hardware capabilities in _substrate-telemetry_. This could be particularly helpful if client/runtime designers  are considering changes that may increase validator resource usage.

The trickiest part of this would likely be coming up with a system of measurement that works cross platform and stays relevant over time; i.e. how would you measure QEMU VMs, or a node running in a VM on a shared host with resource competition. One initial idea here by @dvdplm is to run a benchmark at startup, or intermittently (to catch a node running on a shared host among other VMs all competing for resources, making the host perform very differently sometimes).

Another likely consideration is how to provide adequate data but not make it super easy to fingerprint the node. One option is providing a `HardwareAdequate` enum that would be relative to a standard established by the client/runtime maintainers: `Adequate`, `Insufficient`, `Unknown`.

**Comment by bkchr** [comment]
Why do we need the telemetry for this?

For benchmarking you already need to choose a fixed machine type, meaning the best validator machine is already specified. Based on this you already can check the performance of the network, no need to check the telemetry for this?

**Comment by emostov** [comment]
> For benchmarking you already need to choose a fixed machine type, meaning the best validator machine is already specified.

This assumes validators are using hardware comparable to the benchmark hardware or better. But I think the incentives for many validators is to get the cheapest machine they can get away with while not missing rewards (anecdotally I see this as a significantly below benchmarking hardware; I consistently see people recommend lower hardware specs in validator chat rooms). 

If the optimal cost efficiency choice for a validator setup is significantly below the benchmarking hardware and the network maintainers are not aware of the discrepancy, this could lead to issues like a large amount of machines going offline, the network stalls, etc. While we have the mechanism of slashing to potentially penalize those who are underpowered, I think it would still be helpful to get idea of network hardware composition to catch these issues before a change is rolled out on a  live network. 

Alternatively I think network maintainers could provide a hard recommended lower limit for validator hardware and make it very clear that operators should at minimum provision those specs; atm though I don't this is very clear to node operators.

**Comment by bkchr** [comment]
There are no "network maintainers", otherwise it would be a centralized network ;) 

If you run a validator and use a machine with not enough power, you will get slashed. As you already said. 

What you want to do when validators are not running the recommended machines? Stop an upgrade? The incentivization should come from the rewards and if your machine is underpowered, you get less or no rewards.

**Comment by burdges** [comment]
> If you run a validator and use a machine with not enough power, you will get slashed. As you already said.

Unclear.  It'll be possible to get yourself slashed by being so slow you think a block times out when actually it's fine, but being slow might manifest elsewhere first.  We do not penalize no shows currently, possibly how nodes with shitty networking manifest. 

We'll want running time reports in candidate validity statements for https://github.com/paritytech/polkadot/pull/1656 anyways, so we could move the reports forward somewhat if we think that information helps elsewhere.

**Comment by dvdplm** [comment]
> There are no "network maintainers", otherwise it would be a centralized network ;)

For the time being Polkadot/Kusama is a single-client network and we're the maintainers of the software running the (decentralised) network, so like it or not, when there's a problem we're the ones fixing it (more often than not, it's actually you fixing it. ;)).
 
> What you want to do when validators are not running the recommended machines? Stop an upgrade? The incentivization should come from the rewards and if your machine is underpowered, you get less or no rewards.

We do have a blind spot when it comes to planning though. If, for any reason, we need to change the specs of the validator minimal viable hardware, we'd be fairly blind.

I see this featurette as useful in two ways:
- inform our own planning and debugging
- provide a "social rewarding/shaming" mechanism with a green badge saying "runs adequate hardware" on polkadot.js staking and telemetry. It'd be in the same vein as providing a descriptive name for your validator is encouraged (but not required).

I'm on the fence on this feature myself. I think it has some merit but I also think it could be a fair amount of work to maintain over time. I'd be reluctant to use the "hw_adequate" bool for anything other than a rough idea of where we're at.

**Comment by bkchr** [comment]
> > If you run a validator and use a machine with not enough power, you will get slashed. As you already said.
> 

I expressed myself really badly here. I mean you can get slashed when you don't report of being online. Currently that is relative easy to fake, but later it will be more complicated. 

> Unclear. It'll be possible to get yourself slashed by being so slow you think a block times out when actually it's fine ala [paritytech/polkadot#1656](https://github.com/paritytech/polkadot/pull/1656) but being slow might manifest elsewhere first, not sure. We do not penalize no shows currently, possibly how nodes with shitty networking manifest.
> 

Actually I would like to see some feature for validators to opt-in some sort of decentralized logging (don't ask me how this should work). Especially with parachains it is otherwise almost impossible to debug anything. 


@dvdplm I see your point. Any idea what you want to run and how we want to conclude from this benchmark to what is needed to run a validator?

**Comment by emostov** [comment]
> Actually I would like to see some feature for validators to opt-in some sort of decentralized logging (don't ask me how this should work). Especially with parachains it is otherwise almost impossible to debug anything.

+1

**Comment by dvdplm** [comment]
> Actually I would like to see some feature for validators to opt-in some sort of decentralized logging

Could be run and paid for by the treasury perhaps.

> Any idea what you want to run and how we want to conclude from this benchmark to what is needed to run a validator?

We'd need metrics on RAM, network, CPU and disk I'd say. 
The last two are easier (CPU: calculate a few hashes?, disk: lookup a set of known keys perhaps), but RAM and network bandwidth/latency is harder to get right I think (cross-platform, stable-ish over time etc). Run the benchmark at somewhat random  intervals and submit a moving average of, say, the last 3 runs?

**Comment by burdges** [comment]
We can make anyone in the 1000 validators programs give us whatever logs you like.

**Comment by emostov** [comment]
> We can make anyone in the 1000 validators programs give us whatever logs you like.

This still requires asking operators for x amount of logs and parsing whatever formats they choose to expose their logs. I would guess it would be nicer to just have nodes sending logs in a standardized format that can be easily parsed with whatever tools are being used.

A bit of a tangent but what about adding a flag a too validators that allows them to submit logs (prometheus or otherwise) to some endpoint? 

I think in the current prometheus setup you have to scrape the nodes prometheus port and potentially deal with auth that may be put up in front of it. But maybe an egress only setup for submitting logs is 1) easier to scale since the log client does not have to explicitly setup scraping and 2) maybe egress only is safer? 
The log client could whitelist IPs to known nodes active in the set, since we can assume static IPs.

However I think there is still the issue of specifying log targets and I assume it would quickly be a huge amount of data.

**Comment by koute** [comment]
I can take this.

My proposal here would be roughly something like this:
- Keep it simple; we don't want this to become a maintenance burden.
- When starting the node grab basic info regarding hardware *and* software on which the node's running:
   * The exact CPU model; cloud providers sometimes lie about it, but that's fine because of the next point and the benchmarks.
   * Whether the node is running under a VM or on bare metal.
   * The number of cores.
   * The amount of RAM.
   * Kernel version.
   * OS distribution.
   * Rough effective CPU speed calculated using some simple benchmark (hashes/sec or something along those lines)
   * Rough effective memory bandwidth calculated using some simple benchmark (memcpy a block of memory should be reliable as long as we copy significantly more than what can fit in CPU's L3 cache)
   * Rough effective disk read and write bandwidth calculated by writing a dummy file to disk and then reading it back (I think this should be doable with appropriate use of fsync and flushing the page cache so that the file's actually being read from disk/written to the disk)
 - Keep this Linux-only for now. (Maybe except the CPU and memory benchmarks, since those should be OS agnostic.) Other OSes could always be added in the future; on Linux at least gathering everything I've mentioned is pretty easy and simple.
 - Keep the benchmarks themselves short, simple and ideally under 1 second each (so they could be ran on startup).
- Add an easy way for people to opt out of this (`--disable-hwsw-telemetry` or something like that?)
- Don't display any of this publicly (unless aggregated/anonymized), not only because of privacy, but also because it could in theory help a potential attacker. (Security by obscurity is bad, but that doesn't mean we should make it easy.)
- For now concentrate on the "inform our own planning and debugging" part, and punt the "provide a social rewarding/shaming mechanism with a green badge" part for later.

The reason why I'm piggybacking telemetry regarding the OS here is that this *is* actually relevant to performance, and would make issues like https://github.com/paritytech/polkadot/issues/4744#issuecomment-1026881474 easier to investigate. I'm currently testing two nodes, both on fresh VM, using the same `polkadot` binary, with the same flags, using exactly the same database (I've `rsync`d the same files to both); the only difference is that they're running on a different Linux distribution, and I'm seeing that their memory usage differs by *several hundred megabytes*. So this is clearly something that could be useful to us.

Does this all sound good to you?

**Comment by bkchr** [comment]
> The reason why I'm piggybacking telemetry regarding the OS here is that this _is_ actually relevant to performance, and would make issues like [paritytech/polkadot#4744 (comment)](https://github.com/paritytech/polkadot/issues/4744#issuecomment-1026881474) easier to investigate

How would that help with this issue?

**Comment by koute** [comment]
> > The reason why I'm piggybacking telemetry regarding the OS here is that this _is_ actually relevant to performance, and would make issues like [paritytech/polkadot#4744 (comment)](https://github.com/paritytech/polkadot/issues/4744#issuecomment-1026881474) easier to investigate
> 
> How would that help with this issue?
> 
> I mean you would run these benchmarks at startup and then? How would that tell you anything about the issue you linked?

Indeed, just gathering data at startup wouldn't be enough to help with that issue. But if we'd also add runtime gathering of the current memory usage (which I would also like to bring back) then that coupled with the extra OS information I've just described *could* help as then we could see how widespread such issues are and whether they're actually coupled to the OS or not.

**Comment by koute** [comment]
> Okay, then you see these kind of information but still don't really know what is happening. Someone is using more memory. Maybe the have increased the db database cache or whatever. There are thousands of factors.
> 
> IMO, the better way is that we have proper metrics and proper ways for these people to report problems. They already opening issues if there are problems. We just need to give them the correct tools to report errors. Maybe some tool that scrapes their grafana and fetches all the relevant data we need for a proper bug report.

I don't think this is a black-and-white either-do-nothing-or-go-pedal-to-the-metal issue. (:

Yes, you're right, the information we automatically gather might not be enough to comprehensively analyze everything, but that's not the point. The point is to 1) be able to *very roughly* guess what might be the problem (or to be able to see that there *is* a problem in the first place, and potentially know where to start when investigating), and 2) have a general idea of what people are running in the wild (so that e.g. we know what we're supposed to be running on our nodes).

This telemetry is not supposed to be a comprehensive tool to report and diagnose problems. It's supposed to be only a simple baseline to give us just a general overview. Right now we're flying blind. For anything more detailed we should - as you've said - give people tools to generate a report which they could attach to their bug reports.

**Comment by wpank** [comment]
> This telemetry is not supposed to be a comprehensive tool to report and diagnose problems. It's supposed to be only a simple baseline to give us just a general overview. Right now we're flying blind. For anything more detailed we should - as you've said - give people tools to generate a report which they could attach to their bug reports.

Agreed - imo this is low hanging fruit that helps us get a _rough_ idea of the state of the network. The goal shouldn't be to get perfect, accurate, info, but just a slightly better idea of things, because at the moment we have no idea what this even looks like.

**Comment by bkchr** [comment]
@koute okay, fine then let's do this.

**Comment by koute** [comment]
I've just merged the last piece of this in `substrate-telemetry`; it'll still most likely require some tweaks, but the initial MVP implementation is done, so I'll close this issue. Any further tweaks/fixes/extensions to this we can file under a new, more specific issue.
