### ISSUE TITLE
Removal of network_state going to telemetry

### ISSUE THREAD

**Issue by gilescope** [paritytech/substrate#8999]
@tomaka has agreed that prometheus is the better place for network metrics (See #5235). As such we can remove the network state column from telemetry.

**Comment by gilescope** [comment]
(network_state is only sent on non-default telemetry verbosity levels.)

**Comment by maciejhirsz** [comment]
Telemetry server accepts network_state as an optional value already (since it doesn't appear on every interval message, or at least didn't use to), so it being absent won't break anything. Removing it will actually make things much simpler since I had to jump through some hoops to make sure we don't parse the whole JSON and bloat the memory, so happy to get rid of it.
