### ISSUE TITLE
Feature flags to disable docs in metadata

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#9235]
Docs in metadata is useful for development purpose but I see no reason why it needs to be exposed for mainnet. We want to keep the wasm as small as possible while having good doc comments coverage.

Should have a way to exclude of the docs in metadata.

**Comment by thiolliere** [comment]
there also was the idea of putting only the hash of the metadata in the wasm-blob instead of the full metadata. And instead distribute the metadata offchain.

The other advantage of having just the hash on chain is that currently building the metadata in wasm takes some time (it was a regression when we introduced the last metadata with full type info). So querying it takes some time. While fetching the hash would be faster.

Should we superseed this proposal with just having the hash of metadata on chain ?

Maybe @ascjones can give more opinion ?

**Comment by xlc** [comment]
Remove docs will be an easy and quick short term solution. And we can also discuss in parallel on what will be the right long term solution.

**Comment by ascjones** [comment]
I agree that the docs shouldn't all be stored in the metadata. Would need to still make it easy to produce the docs for UIs cc @jacogr.

Existing work: https://github.com/paritytech/frame-metadata/pull/21, and also https://github.com/paritytech/scale-info/pull/120 which reduces the docs slightly.

I'm quite busy at the moment so not sure I will get around to following up on these this year though. Happy to review any contributions though.
