### ISSUE TITLE
Potentially get rid of `Pays::No` in weight annotation

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#9252]
Using this in the weight annotation is pretty much an invitation to DoS. All transactions should refund after successful execution, if desired (using a `PostDispatchInfo`). 

We only use this for claims, but even that is solvable by claiming into an existing account. 

It should be either removed, or heavily documented with warnings.

**Comment by bkchr** [comment]
> We only use this for claims, but even that is solvable by claiming into an existing account.

IMHO this is bad. You can not claim your coins, without having more coins. This would also not have worked at Polkadot genesis, because you could not move any funds. The point is that you need an extra `SignedExtension` to make the `Pays::No` safe. Maybe we could make it possible to signal through a `SignedExtension` to the `TransactionPayment` extension that the call should be free?

**Comment by xlc** [comment]
Should just use unsigned transaction for unpaid transaction. Unsigned transactions requires custom validation logic anyway.

**Comment by bkchr** [comment]
Good point :)
