### ISSUE TITLE
Withdraw unbounded possible before slash is applied

### ISSUE THREAD

**Issue by ERussel** [paritytech/substrate#9469]
Staking pallet applies slashes up to but not including active_era - slashing_defer_duration (27)

<img width="724" alt="Screenshot 2021-08-01 at 11 29 05" src="https://user-images.githubusercontent.com/570634/127764670-d8a06dcc-9086-4f0f-b6fe-ae47ddfd58e5.png">

But withdraw unbonded is allowed starting from current_era = unbonded_era + bondig_duration (28). 

<img width="914" alt="Screenshot 2021-08-01 at 11 31 07" src="https://user-images.githubusercontent.com/570634/127764693-cf4f378a-3c0c-4808-ab72-df5d9861cfdc.png">

Taking into account that current_era is set before active_era i think it is possible to unbond in the era when unapplied slash is created and perform withraw unbonded when corresponding current era is set before active_era changes (so before slash is applied).

**Comment by kianenigma** [comment]
The current_era and active_era are always the same except for 1 session, since the session pallet has 1 session delay. Only when we elect a new validator set, the current era is `active_era + 1` for 1 session, and then they become the same again.  

First glance, this does not seem like an issue for me.

Withdrawing happens on the basis of `current_era`, and you can only withdraw if `current_era` has been incremented at least 28 times after you called `unbond`.

Slashing happens on the basis of `active_era`, and your slash will be applied after `active_era` has been incremented 27 times.

While current_era and active_era can be phase-shifted, the progress at the same pace, so the slash should always happen before withdrawing is possible.

**Comment by ERussel** [comment]
That's right. But what I noticed is that the slash is not applied for the `active_era - 27` in the `active_era` but one can withdraw unbonded chunk from `current_era - 28` when `current_era` is set

**Comment by kianenigma** [comment]
> but one can withdraw unbonded chunk from current_era - 28 when current_era is set

Hmm yeah this seems to be the case: https://github.com/paritytech/substrate/blob/master/frame/staking/src/lib.rs#L447

The `BondingDuration` is not inclusive, but `SlashDeferDuration` is inclusive. This could cause issues, have to look into it more.

**Comment by kianenigma** [comment]
(I haven't had time to confirm this yet, but added it to our backlog so eventually we get to it. )

**Comment by kianenigma** [comment]
This was fixed as a part of https://github.com/paritytech/substrate/pull/11823
