### ISSUE TITLE
private key files managed by keystore are `644` permissions

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/substrate#9886]
I asked this [in element](https://matrix.to/#/!HzySYSaIhtyWrwiwEV:matrix.org/$1632752282187836qcICo:matrix.org?via=matrix.parity.io&via=corepaper.org&via=matrix.org) but didn't get an reply, so I'll ask here.

It seems that when I insert a new private key into the keystore the permissions on the filesystem are 644 which means it can be read by other users on the system. Is this by design?

**Comment by bkchr** [comment]
Not really by design, but also having validators running on a multi user system sounds like something that should not be done.

Nevertheless, we can fix this.

**Comment by NukeManDan** [comment]
I am curious about thought on what files that exist in the `--base-path` need permissions set to anything other than `600` (so only the owner can read and write).

My only (naive) worry would that containerized services like indexers alongside the node might have unexpected issues reading the DB directly, but AFAIK all read/write is intended to be managed through the RPC/API, right? Otherwise those could be read only for others.
